// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/timeout/iface.go
// Plugins:   golang 1.0.0, suite 1.0.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/iface/mixin/timeout/...

package timeouttest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/timeout/timeouttest"
)

// Every generated check for Mixed, driven against a stand-in built
// to violate it.
//
//	Proved:   5 checks
//
// Each guard asserts the *reason* the check rejected, not merely that it did. A
// stand-in that failed for some unrelated reason — a nil map, a closed channel
// — would satisfy a guard reading only the fact, which is the vacuity this file
// exists to catch, one level up.

// TestAssertMixedSlowSmokeCanFail holds AssertMixedSlowSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertMixedSlowSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := timeouttest.DefaultMixedFixture()
	subject := timeouttest.NewMixedStub(t,
		timeouttest.WithMixedSlow(func(context.Context, string) error {
			panic("Mixed.Slow: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			timeouttest.AssertMixedSlowSmoke(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedSlowCancelsCanFail holds AssertMixedSlowCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertMixedSlowCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := timeouttest.DefaultMixedFixture()
	subject := timeouttest.NewMixedStub(t,
		timeouttest.WithMixedSlow(func(context.Context, string) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			timeouttest.AssertMixedSlowCancels(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("must report a cancelled context",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedSlowHonoursDeadlineCanFail holds AssertMixedSlowHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertMixedSlowHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := timeouttest.DefaultMixedFixture()
	subject := timeouttest.NewMixedStub(t,
		timeouttest.WithMixedSlow(func(context.Context, string) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			timeouttest.AssertMixedSlowHonoursDeadline(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("must report an expired deadline",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedSlowToleratesNilContextCanFail holds AssertMixedSlowToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertMixedSlowToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := timeouttest.DefaultMixedFixture()
	subject := timeouttest.NewMixedStub(t,
		timeouttest.WithMixedSlow(func(context.Context, string) error {
			panic("Mixed.Slow: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			timeouttest.AssertMixedSlowToleratesNilContext(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedSlowCompletesInBudgetCanFail holds AssertMixedSlowCompletesInBudget to being able to fail.
//
// The stand-in spends twice its declared budget. A check that let that pass
// would leave the duration in the directive as documentation, which is the one
// thing the mixin exists to stop.
func TestAssertMixedSlowCompletesInBudgetCanFail(t *testing.T) {
	t.Parallel()

	fixture := timeouttest.DefaultMixedFixture()
	budget, err := time.ParseDuration("5s")
	if err != nil {
		t.Fatalf("the timeout mixin declares %q, which is not a duration: %v", "5s", err)
	}

	// One clock, held here and handed to the check. A stand-in advancing a
	// clock the check does not read would overrun nothing.
	clk := clock.NewTestClock(time.Time{})

	subject := timeouttest.NewMixedStub(t,
		timeouttest.WithMixedSlow(func(context.Context, string) error {
			clk.Advance(2 * budget)
			return nil
		}))

	got := testkit.Rejects(t, "a method that spends twice its declared budget",
		func(tb testing.TB) {
			tb.Helper()
			timeouttest.AssertMixedSlowCompletesInBudget(tb, clk, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("over its declared budget",
		"and rejects it for the reason the check is about")
}

// testkit: end of generated content.
// testkit:provenance 2b2c4cee15c2e173358f8cdc90ee03a0920971d97a42d3d4e15b20ca5bb0c03f
