// Code generated by testkit suite. DO NOT EDIT.
// Source: counter.go:32-36 (testkit suite -o crdttest/counter_spec.gen_test.go AdditiveCounter)
//
// Directives:
//   Merge: //testkit:crdt-merge Merge  [suite: AssertCRDTMerge dual-impl convergence subtest]

// Package crdttest_test verifies that any implementation of
// [crdt.AdditiveCounter] honors the contract declared by the
// source interface. Generated by `testkit suite`.
//
// # Usage
//
//	func TestAdditiveCounterContract(t *testing.T) {
//	    AssertAdditiveCounterContract(t, func() crdt.AdditiveCounter {
//	        return newInMemory()
//	    })
//	}
//
// # Multi-impl conformance
//
// Run the same contract once per implementation with
// `t.Run(name, ...)` per impl:
//
//	func TestAdditiveCounterContractAcrossImpls(t *testing.T) {
//	    AssertAdditiveCounterContractAcrossImpls(t, []AdditiveCounterNamedFactory{
//	        {Name: "InMemory", Factory: newInMemory},
//	        {Name: "Postgres", Factory: newPostgres},
//	    })
//	}
//
// New impls drop into the slice — no per-impl test function to
// hand-wire. The driver emits identical per-method, per-shape, and
// per-directive subtests across every factory. Variadic `suite.Option`
// arguments apply to every factory's contract run.
//
// # Contract coverage
//
// Every non-skipped method gets a smoke subtest that constructs the
// impl, invokes the method with safe arguments (zero-values when
// the method's parameters allow, sample-driven when
// `//testkit:sample` is declared), and fails the test loudly on
// panic. Methods marked `//testkit:integration-only` are skipped —
// the consumer's integration test owns those contracts.
//
// Per-shape baseline assertions (Reader, Writer, Stream, …) and
// per-directive subtests (errors, deprecated, retryable, partition,
// order-after, wrapped-via, …) layer on top of smoke; see the
// [AdditiveCounter contract docs](.) for the full per-shape menu.
package crdttest_test

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/generator/testdata/crdt"
	"go.thesmos.sh/testkit/suite"
)

// AdditiveCounterFactory produces an implementation of [crdt.AdditiveCounter] for use
// by the contract driver. Each call must yield a fresh, independent
// instance — the contract subtests reset state between runs by
// asking the factory for a new impl.
type AdditiveCounterFactory func() crdt.AdditiveCounter

// AdditiveCounterNamedFactory pairs a human-readable name with a factory.
// The multi-impl driver runs the contract once per named factory
// with `t.Run(Name, ...)`; the name surfaces in test output.
type AdditiveCounterNamedFactory struct {
	Name    string
	Factory AdditiveCounterFactory
}

// AssertAdditiveCounterContract runs the full AdditiveCounter contract against any
// implementation produced by `factory`. Each subtest constructs a
// fresh impl via the factory so per-test state isolation is the
// caller's responsibility — the factory should return an
// independently-state'd instance every call.
//
// Variadic `opts` carry impl-supplied inputs the contract needs but
// the generator can't synthesize: invalid factories for RejectInvalid
// baselines, prePopulate seeders, paired observers, aggregator
// bounds, stream samples, scope context, lease release, and more.
// See [suite.Option] and the `WithX` constructors for the full set.
func AssertAdditiveCounterContract(t *testing.T, factory AdditiveCounterFactory, opts ...suite.Option) {
	t.Helper()
	resolved := suite.ResolveOptions(opts...)
	_ = resolved
	// When the consumer supplies WithPrePopulate, wrap the factory once
	// so every fresh impl handed to a subtest gets seeded before any
	// contract assertion runs. The wrapper is identity when no
	// PrePopulate option is supplied — production-cost is a single
	// type assertion + nil check at driver entry.
	if seed, ok := resolved.PrePopulate.(func(crdt.AdditiveCounter)); ok {
		base := factory
		factory = func() crdt.AdditiveCounter {
			impl := base()
			seed(impl)
			return impl
		}
	}

	// Merge — Writer-shape method.
	//
	// Shape semantics:
	//   func(ctx, V) error — value writer. Idempotent on repeated identical writes; honors ctx cancellation.
	//
	// Default contracts (always run for Writer):
	//   - smoke
	//       fail-fast bare invocation
	//   - write succeeds
	//       happy-path write against the configured sample
	//   - respects context
	//       ctx.Done() surfaces context.Canceled before mutation
	//   - idempotent
	//       writing the same value twice returns nil twice
	//   - concurrent safe
	//       4 workers × 10 iterations under -race
	//
	// Directive contracts (extra subtests below the baseline):
	//   - crdt merge
	//       //testkit:crdt-merge Other=Merge — paired with Merge, this method's output is invariant under merge order
	t.Run("Merge", func(t *testing.T) {
		t.Parallel()
		sctx := suite.WriterContextFor[crdt.AdditiveCounter, int](t, factory,
			func(ctx context.Context, impl crdt.AdditiveCounter, value int) error {
				return impl.Merge(ctx, value)
			})
		suite.AssertWriterBaseline[crdt.AdditiveCounter, int](
			42,
		)(sctx)
		suite.AssertCRDTMerge[crdt.AdditiveCounter, int](
			42,
			0,
			func(ctx context.Context, impl crdt.AdditiveCounter, v int) error {
				return impl.Merge(ctx, v)
			},
			func() func(a, b crdt.AdditiveCounter) bool {
				if eq, ok := resolved.StateEqual.(func(a, b crdt.AdditiveCounter) bool); ok {
					return eq
				}
				return nil
			}(),
		)(t, factory)
	})

	// Value — Aggregator-shape method.
	//
	// Shape semantics:
	//   func(ctx) (R, error) — scalar aggregator. Reads internal state through a context-aware ctor; returns one value plus an error. Consistent across calls when state hasn't changed.
	//
	// Default contracts (always run for Aggregator):
	//   - smoke
	//       fail-fast bare invocation
	//   - aggregator returns expected
	//       value matches the configured sample with no error
	//   - respects context
	//       ctx.Done() surfaces context.Canceled
	//   - aggregator consistent
	//       three sequential calls yield equal results
	//   - concurrent safe
	//       4 workers × 10 iterations under -race
	//
	// Sample alignment: Aggregator-shape methods have no input parameter, so the contract's expected sample (e.g. 42 for int) cannot be derived from a fresh impl's natural state. Configure your factory so this method returns the sample value — typically via an override field on the in-mem (see allshapestest.SetCountOverride for the pattern) or by pre-populating enough state that the state-derived return matches.
	t.Run("Value", func(t *testing.T) {
		t.Parallel()
		sctx := suite.AggregatorContextFor[crdt.AdditiveCounter, int](t, factory,
			func(ctx context.Context, impl crdt.AdditiveCounter) (int, error) {
				return impl.Value(ctx)
			})
		var extras []suite.AggregatorAssertion[crdt.AdditiveCounter, int]
		if len(resolved.AggregatorBounds) > 0 {
			if lower, lok := resolved.AggregatorBounds[0].Lower.(int); lok {
				if upper, uok := resolved.AggregatorBounds[0].Upper.(int); uok {
					extras = append(extras, suite.AssertAggregatorBounded[crdt.AdditiveCounter, int](lower, upper))
				}
			}
		}
		suite.AssertAggregatorBaseline[crdt.AdditiveCounter, int](42, extras...)(sctx)
	})

}

// AssertAdditiveCounterContractAcrossImpls runs [AssertAdditiveCounterContract] once per named factory under
// `t.Run(Name, ...)`. New impls drop in via slice append. The
// variadic `opts` apply to every factory's contract run.
func AssertAdditiveCounterContractAcrossImpls(t *testing.T, factories []AdditiveCounterNamedFactory, opts ...suite.Option) {
	t.Helper()
	for _, nf := range factories {
		t.Run(nf.Name, func(t *testing.T) {
			t.Parallel()
			AssertAdditiveCounterContract(t, nf.Factory, opts...)
		})
	}
}
