// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/streamreader/iface.go
// Plugins:   golang 1.0.0, model 0.26.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package streamreadertest

import (
	"context"
	"iter"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/streamreader"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
)

// StreamReaderModel runs random sequences of StreamReader's methods against every
// subject and a known-good in-memory reference side by side, comparing after
// every call. Pass it to AssertStreamReaderContract; it reports under
// "model/twin", and StreamReaderWithout("model/twin") declines it.
//
//	Reference: the subject's own factory — no reader/writer pair derives a store,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: List (streamreader)
//	Laws:      AUTO-STREAM-COMPLETION, AUTO-STREAM-REENTRANT
func StreamReaderModel(opts ...StreamReaderModelOption) StreamReaderOption {
	return func(c *streamreaderConfig) {
		c.extensions = append(c.extensions, streamreaderContractExtension{
			name: "model/twin",
			run: func(t *testing.T, _ string, factory func() streamreader.StreamReader, _ *streamreaderConfig) {
				model.Check(t, StreamReaderModelProperty(factory, opts...))
			},
		})
	}
}

// StreamReaderModelProperty builds the property the option runs — exported because a
// bespoke harness composes from here: model.Check for a test, model.MakeFuzz
// for a coverage-guided fuzz target, both over this one derivation.
func StreamReaderModelProperty(factory func() streamreader.StreamReader, opts ...StreamReaderModelOption) func(*model.T) {
	cfg := newStreamReaderModelConfig(opts...)
	reference := cfg.reference
	if reference == nil {
		reference = factory
	}
	// The laws the classifications earned, each reporting under its AUTO-
	// identifier when it fails. Observational: a law never mutates, so running
	// them inside the sequences is safe for every step that follows.
	laws := model.NewRegistry[streamreader.StreamReader]()
	laws.Add(law.StreamCompletion[streamreader.StreamReader, streamreader.Value]{
		Drain: func(rt *model.T, s streamreader.StreamReader) ([]streamreader.Value, error) {
			out := []streamreader.Value{}
			for v, err := range s.List(rt.Context()) {
				if err != nil {
					return out, err
				}
				out = append(out, v)
			}
			return out, nil
		},
	})
	laws.Add(law.StreamReentrancy[streamreader.StreamReader, streamreader.Value]{
		Collect: func(rt *model.T, s streamreader.StreamReader) ([]streamreader.Value, error) {
			out := []streamreader.Value{}
			for v, err := range s.List(rt.Context()) {
				if err != nil {
					return out, err
				}
				out = append(out, v)
			}
			return out, nil
		},
	})
	return model.Property(factory,
		model.WithReference(reference),
		model.WithLaws(laws),
		model.WithActions(
			action.Stream("List",
				func(ctx context.Context, s streamreader.StreamReader) ([]streamreader.Value, error) {
					var out []streamreader.Value
					for v, err := range s.List(ctx) {
						if err != nil {
							return nil, err
						}
						out = append(out, v)
					}
					return out, nil
				}),
		),
	)
}

// StreamReaderModelFuzz hands a subject's sequence space to the
// coverage-guided engine: the fuzzer's bytes replay as rapid's choice
// stream, so mutating them mutates the action ordering and every drawn
// input at once — and the engine's coverage feedback climbs the subject's
// own branches, which is what no fixed seed can do. Wire it from a fuzz
// target beside the subject:
//
//	func FuzzStreamReader(f *testing.F) {
//		StreamReaderModelFuzz(f, func() StreamReader { return NewMine() })
//	}
func StreamReaderModelFuzz(f *testing.F, factory func() streamreader.StreamReader, opts ...StreamReaderModelOption) {
	f.Add([]byte{})
	f.Fuzz(model.MakeFuzz(StreamReaderModelProperty(factory, opts...)))
}

// StreamReaderModelOption configures the model run.
type StreamReaderModelOption func(*streamReaderModelConfig)

// StreamReaderModelReference replaces the derived reference — for an
// interface whose semantics outrun its shape.
func StreamReaderModelReference(factory func() streamreader.StreamReader) StreamReaderModelOption {
	return func(c *streamReaderModelConfig) { c.reference = factory }
}

// StreamReaderSatWear is one wearable defect: a kind, and the wrap that
// dresses a subject in it.
type streamreaderSatWear struct {
	kind string
	wrap func(fx StreamReaderFixture, s streamreader.StreamReader) streamreader.StreamReader
}

//nolint:gochecknoglobals // the prover's wardrobe, read-only after init.
var streamreaderSatWears = map[string][]streamreaderSatWear{}

//nolint:gochecknoinits // the wardrobe fills once, keyed by method.
func init() { //nolint:staticcheck // an empty wardrobe leaves dress unused by design.
	dress := func(method, kind string, wrap func(fx StreamReaderFixture, s streamreader.StreamReader) streamreader.StreamReader) {
		streamreaderSatWears[method] = append(streamreaderSatWears[method],
			streamreaderSatWear{kind: kind, wrap: wrap})
	}
	dress("List", "inert", func(_ StreamReaderFixture, s streamreader.StreamReader) streamreader.StreamReader {
		return streamreaderSatInertList{s}
	})
}

// StreamReaderModelSaturation proves the bound laws can fail: per law, a
// defect is worn on each method the law's closures reach — zeros, the
// fixture pair alternated, a waning count — and at least one worn run must
// fail naming the law's own identifier, with the clean factory standing as
// reference. A law every defect survives is bound but unsaturatable, and
// fails here by name. Pass the same options that arm the tier: a law behind
// an unarmed door or the clocked factory is skipped visibly, never counted.
func StreamReaderModelSaturation(t *testing.T, factory func() streamreader.StreamReader, opts ...StreamReaderModelOption) {
	t.Helper()
	cfg := newStreamReaderModelConfig(opts...)
	_ = cfg
	fx := DefaultStreamReaderFixture()
	_ = fx
	t.Run("AUTO-STREAM-COMPLETION", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"List"} {
				for _, wear := range streamreaderSatWears[method] {
					surrogate := "StreamReaderSat_AUTO-STREAM-COMPLETION_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						StreamReaderModelReference(factory))
					model.Check(f, StreamReaderModelProperty(func() streamreader.StreamReader {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-STREAM-COMPLETION")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-STREAM-COMPLETION survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
	t.Run("AUTO-STREAM-REENTRANT", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"List"} {
				for _, wear := range streamreaderSatWears[method] {
					surrogate := "StreamReaderSat_AUTO-STREAM-REENTRANT_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						StreamReaderModelReference(factory))
					model.Check(f, StreamReaderModelProperty(func() streamreader.StreamReader {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-STREAM-REENTRANT")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-STREAM-REENTRANT survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
}

// streamreaderSatInertList answers zeros where List should act.
type streamreaderSatInertList struct{ streamreader.StreamReader }

func (streamreaderSatInertList) List(_ context.Context) (z0 iter.Seq2[streamreader.Value, error]) {
	return
}

type streamReaderModelConfig struct {
	reference func() streamreader.StreamReader
}

func newStreamReaderModelConfig(opts ...StreamReaderModelOption) *streamReaderModelConfig {
	c := &streamReaderModelConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// testkit: end of generated content.
// testkit:provenance 2a043537a74311d5ff8db3a7549baf07efccab9b50dab2048a865ce6f9a11e88
