// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/monotonic/iface.go
// Plugins:   golang 1.0.0, model 0.26.2, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package monotonictest

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync/atomic"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/monotonic"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
)

// MixedModel runs random sequences of Mixed's methods against every
// subject and a known-good in-memory reference side by side, comparing after
// every call. Pass it to AssertMixedContract; it reports under
// "model/twin", and MixedWithout("model/twin") declines it.
//
//	Reference: the subject's own factory — no reader/writer pair derives a store,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Version (aggregator), Advance (lifecycle)
//	Laws:      AUTO-COUNT-EQUALS-REFERENCE, AUTO-MONOTONIC-NON-DECREASING, AUTO-LIFECYCLE-RESPECTS-CONTEXT
func MixedModel(opts ...MixedModelOption) MixedOption {
	return func(c *mixedConfig) {
		c.extensions = append(c.extensions, mixedContractExtension{
			name: "model/twin",
			run: func(t *testing.T, _ string, factory func() monotonic.Mixed, _ *mixedConfig) {
				model.Check(t, MixedModelProperty(factory, opts...))
			},
		})
	}
}

// MixedModelProperty builds the property the option runs — exported because a
// bespoke harness composes from here: model.Check for a test, model.MakeFuzz
// for a coverage-guided fuzz target, both over this one derivation.
func MixedModelProperty(factory func() monotonic.Mixed, opts ...MixedModelOption) func(*model.T) {
	cfg := newMixedModelConfig(opts...)
	reference := cfg.reference
	if reference == nil {
		reference = factory
	}
	// The laws the classifications earned, each reporting under its AUTO-
	// identifier when it fails. Observational: a law never mutates, so running
	// them inside the sequences is safe for every step that follows.
	laws := model.NewRegistry[monotonic.Mixed]()
	laws.Add(law.CountEqualsReference[monotonic.Mixed, int64]{
		Count: func(rt *model.T, s monotonic.Mixed) (int64, error) {
			return s.Version(rt.Context())
		},
	})
	laws.Add(&law.MonotonicNonDecreasing[monotonic.Mixed, int64]{
		Read: func(rt *model.T, s monotonic.Mixed) (int64, error) {
			return s.Version(rt.Context())
		},
		Less: func(a, b int64) bool { return a < b },
	})
	laws.Add(law.LifecycleRespectsContext[monotonic.Mixed]{
		Op: func(ctx context.Context, s monotonic.Mixed) error {
			return s.Advance(ctx)
		},
	})
	return model.Property(factory,
		model.WithReference(reference),
		model.WithLaws(laws),
		model.WithActions(
			action.Aggregator("Version",
				func(ctx context.Context, s monotonic.Mixed) (int64, error) {
					return s.Version(ctx)
				}),
			action.Lifecycle("Advance",
				func(ctx context.Context, s monotonic.Mixed) error {
					return s.Advance(ctx)
				}),
		),
	)
}

// MixedModelFuzz hands a subject's sequence space to the
// coverage-guided engine: the fuzzer's bytes replay as rapid's choice
// stream, so mutating them mutates the action ordering and every drawn
// input at once — and the engine's coverage feedback climbs the subject's
// own branches, which is what no fixed seed can do. Wire it from a fuzz
// target beside the subject:
//
//	func FuzzMixed(f *testing.F) {
//		MixedModelFuzz(f, func() Mixed { return NewMine() })
//	}
func MixedModelFuzz(f *testing.F, factory func() monotonic.Mixed, opts ...MixedModelOption) {
	f.Add([]byte{})
	f.Fuzz(model.MakeFuzz(MixedModelProperty(factory, opts...)))
}

// MixedModelOption configures the model run.
type MixedModelOption func(*mixedModelConfig)

// MixedModelReference replaces the derived reference — for an
// interface whose semantics outrun its shape.
func MixedModelReference(factory func() monotonic.Mixed) MixedModelOption {
	return func(c *mixedModelConfig) { c.reference = factory }
}

// MixedSatWear is one wearable defect: a kind, and the wrap that
// dresses a subject in it.
type mixedSatWear struct {
	kind string
	wrap func(fx MixedFixture, s monotonic.Mixed) monotonic.Mixed
}

//nolint:gochecknoglobals // the prover's wardrobe, read-only after init.
var mixedSatWears = map[string][]mixedSatWear{}

//nolint:gochecknoinits // the wardrobe fills once, keyed by method.
func init() { //nolint:staticcheck // an empty wardrobe leaves dress unused by design.
	dress := func(method, kind string, wrap func(fx MixedFixture, s monotonic.Mixed) monotonic.Mixed) {
		mixedSatWears[method] = append(mixedSatWears[method],
			mixedSatWear{kind: kind, wrap: wrap})
	}
	dress("Version", "inert", func(_ MixedFixture, s monotonic.Mixed) monotonic.Mixed {
		return mixedSatInertVersion{s}
	})
	dress("Version", "sputter", func(_ MixedFixture, s monotonic.Mixed) monotonic.Mixed {
		return &mixedSatSputterVersion{Mixed: s}
	})
	dress("Version", "wane", func(_ MixedFixture, s monotonic.Mixed) monotonic.Mixed {
		return &mixedSatWaneVersion{Mixed: s}
	})
	dress("Version", "wax", func(_ MixedFixture, s monotonic.Mixed) monotonic.Mixed {
		return &mixedSatWaxVersion{Mixed: s}
	})
	dress("Advance", "inert", func(_ MixedFixture, s monotonic.Mixed) monotonic.Mixed {
		return mixedSatInertAdvance{s}
	})
	dress("Advance", "sputter", func(_ MixedFixture, s monotonic.Mixed) monotonic.Mixed {
		return &mixedSatSputterAdvance{Mixed: s}
	})
}

// MixedModelSaturation proves the bound laws can fail: per law, a
// defect is worn on each method the law's closures reach — zeros, the
// fixture pair alternated, a waning count — and at least one worn run must
// fail naming the law's own identifier, with the clean factory standing as
// reference. A law every defect survives is bound but unsaturatable, and
// fails here by name. Pass the same options that arm the tier: a law behind
// an unarmed door or the clocked factory is skipped visibly, never counted.
func MixedModelSaturation(t *testing.T, factory func() monotonic.Mixed, opts ...MixedModelOption) {
	t.Helper()
	cfg := newMixedModelConfig(opts...)
	_ = cfg
	fx := DefaultMixedFixture()
	_ = fx
	t.Run("AUTO-COUNT-EQUALS-REFERENCE", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"Version"} {
				for _, wear := range mixedSatWears[method] {
					surrogate := "MixedSat_AUTO-COUNT-EQUALS-REFERENCE_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						MixedModelReference(factory))
					model.Check(f, MixedModelProperty(func() monotonic.Mixed {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "[semantic]") || strings.Contains(f.Msg(), "AUTO-COUNT-EQUALS-REFERENCE")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-COUNT-EQUALS-REFERENCE survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
	t.Run("AUTO-MONOTONIC-NON-DECREASING", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"Version"} {
				for _, wear := range mixedSatWears[method] {
					surrogate := "MixedSat_AUTO-MONOTONIC-NON-DECREASING_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						MixedModelReference(factory))
					model.Check(f, MixedModelProperty(func() monotonic.Mixed {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-MONOTONIC-NON-DECREASING")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-MONOTONIC-NON-DECREASING survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
	t.Run("AUTO-LIFECYCLE-RESPECTS-CONTEXT", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"Advance"} {
				for _, wear := range mixedSatWears[method] {
					surrogate := "MixedSat_AUTO-LIFECYCLE-RESPECTS-CONTEXT_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						MixedModelReference(factory))
					model.Check(f, MixedModelProperty(func() monotonic.Mixed {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-LIFECYCLE-RESPECTS-CONTEXT")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-LIFECYCLE-RESPECTS-CONTEXT survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
}

// mixedSatInertVersion answers zeros where Version should act.
type mixedSatInertVersion struct{ monotonic.Mixed }

func (mixedSatInertVersion) Version(_ context.Context) (z0 int64, z1 error) {
	return
}

// mixedSatSputterVersion alternates a minted refusal
// with the real answer where Version should be steady.
type mixedSatSputterVersion struct {
	monotonic.Mixed
	flip atomic.Int64
}

func (m *mixedSatSputterVersion) Version(p0 context.Context) (z0 int64, z1 error) {
	if m.flip.Add(1)%2 == 1 {
		z1 = errors.New("monotonictest: saturation sputtered a refusal")
		return
	}
	return m.Mixed.Version(p0)
}

// mixedSatWaneVersion answers a strictly waning count
// where Version should observe.
type mixedSatWaneVersion struct {
	monotonic.Mixed
	flip atomic.Int64
}

func (m *mixedSatWaneVersion) Version(_ context.Context) (int64, error) {
	return int64(1000 - m.flip.Add(1)), nil
}

// mixedSatWaxVersion answers a count that only grows
// where Version should return to rest.
type mixedSatWaxVersion struct {
	monotonic.Mixed
	flip atomic.Int64
}

func (m *mixedSatWaxVersion) Version(_ context.Context) (int64, error) {
	return int64(m.flip.Add(1)), nil
}

// mixedSatInertAdvance answers zeros where Advance should act.
type mixedSatInertAdvance struct{ monotonic.Mixed }

func (mixedSatInertAdvance) Advance(_ context.Context) (z0 error) {
	return
}

// mixedSatSputterAdvance alternates a minted refusal
// with the real answer where Advance should be steady.
type mixedSatSputterAdvance struct {
	monotonic.Mixed
	flip atomic.Int64
}

func (m *mixedSatSputterAdvance) Advance(p0 context.Context) (z0 error) {
	if m.flip.Add(1)%2 == 1 {
		z0 = errors.New("monotonictest: saturation sputtered a refusal")
		return
	}
	return m.Mixed.Advance(p0)
}

type mixedModelConfig struct {
	reference func() monotonic.Mixed
}

func newMixedModelConfig(opts ...MixedModelOption) *mixedModelConfig {
	c := &mixedModelConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// testkit: end of generated content.
// testkit:provenance ae0e31f8de5b6c6d65e0899b40197537ac36947ce1836912152f6ec2cd469bc6
