// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/codec-lossy/iface.go
// Plugins:   golang 1.0.0, suite 1.15.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package codeclossytest_test

import (
	"context"
	"errors"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/codec-lossy/codeclossytest"
)

// Every generated check for Contract, driven against a stand-in built
// to violate it.
//
//	Proved:   10 checks
//
// Each guard asserts the *reason* the check rejected, not merely that it did. A
// stand-in that failed for some unrelated reason — a nil map, a closed channel
// — would satisfy a guard reading only the fact, which is the vacuity this file
// exists to catch, one level up.

// TestAssertContractEncodeSmokeCanFail holds AssertContractEncodeSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertContractEncodeSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractEncode(func(context.Context, string) (string, error) {
			panic("Contract.Encode: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractEncodeSmoke(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Encode panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertContractEncodeCancelsCanFail holds AssertContractEncodeCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertContractEncodeCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractEncode(func(context.Context, string) (string, error) {
			var r0 string
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractEncodeCancels(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Encode must report a cancelled context as context.Canceled",
		"and rejects it for the reason the check is about")
}

// TestAssertContractEncodeHonoursDeadlineCanFail holds AssertContractEncodeHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertContractEncodeHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractEncode(func(context.Context, string) (string, error) {
			var r0 string
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractEncodeHonoursDeadline(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Encode must report an expired deadline as context.DeadlineExceeded",
		"and rejects it for the reason the check is about")
}

// TestAssertContractEncodeToleratesNilContextCanFail holds AssertContractEncodeToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertContractEncodeToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractEncode(func(context.Context, string) (string, error) {
			panic("Contract.Encode: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractEncodeToleratesNilContext(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Encode panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// TestAssertContractEncodeZeroOnErrorCanFail holds AssertContractEncodeZeroOnError to being able to fail.
//
// The stand-in refuses the call and answers a value that looks like a result
// anyway. A check that let that pass would leave a caller who checks the error
// and a caller who checks the value disagreeing about what happened — the
// claim's own violation, not a stand-in that merely succeeds.
func TestAssertContractEncodeZeroOnErrorCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractEncode(func(context.Context, string) (string, error) {
			return "test-r0", errors.New("violate: refused with a believable value")
		}))

	got := testkit.Rejects(t, "a method answering a believable value beside its error",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractEncodeZeroOnError(tb, subject, fixture.InOther)
		})
	testkit.Assert(t, got).Contains("Encode must return the zero value alongside an error",
		"and rejects it for the reason the check is about")
}

// TestAssertContractDecodeSmokeCanFail holds AssertContractDecodeSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertContractDecodeSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractDecode(func(context.Context, string) (string, error) {
			panic("Contract.Decode: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractDecodeSmoke(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Decode panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertContractDecodeCancelsCanFail holds AssertContractDecodeCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertContractDecodeCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractDecode(func(context.Context, string) (string, error) {
			var r0 string
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractDecodeCancels(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Decode must report a cancelled context as context.Canceled",
		"and rejects it for the reason the check is about")
}

// TestAssertContractDecodeHonoursDeadlineCanFail holds AssertContractDecodeHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertContractDecodeHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractDecode(func(context.Context, string) (string, error) {
			var r0 string
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractDecodeHonoursDeadline(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Decode must report an expired deadline as context.DeadlineExceeded",
		"and rejects it for the reason the check is about")
}

// TestAssertContractDecodeToleratesNilContextCanFail holds AssertContractDecodeToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertContractDecodeToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractDecode(func(context.Context, string) (string, error) {
			panic("Contract.Decode: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractDecodeToleratesNilContext(tb, subject, fixture.In)
		})
	testkit.Assert(t, got).Contains("Decode panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// TestAssertContractDecodeZeroOnErrorCanFail holds AssertContractDecodeZeroOnError to being able to fail.
//
// The stand-in refuses the call and answers a value that looks like a result
// anyway. A check that let that pass would leave a caller who checks the error
// and a caller who checks the value disagreeing about what happened — the
// claim's own violation, not a stand-in that merely succeeds.
func TestAssertContractDecodeZeroOnErrorCanFail(t *testing.T) {
	t.Parallel()

	fixture := codeclossytest.DefaultContractFixture()
	subject := codeclossytest.NewContractStub(t,
		codeclossytest.WithContractDecode(func(context.Context, string) (string, error) {
			return "test-r0", errors.New("violate: refused with a believable value")
		}))

	got := testkit.Rejects(t, "a method answering a believable value beside its error",
		func(tb testing.TB) {
			tb.Helper()
			codeclossytest.AssertContractDecodeZeroOnError(tb, subject, fixture.InOther)
		})
	testkit.Assert(t, got).Contains("Decode must return the zero value alongside an error",
		"and rejects it for the reason the check is about")
}

// testkit: end of generated content.
// testkit:provenance 4771bf9fc3c5215cd9a65dd36903670444eaa6a94e2fb3f7e55634087573f4c4
