// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/concurrentreaders/iface.go
// Plugins:   golang 1.0.0, model 0.8.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package concurrentreaderstest_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/concurrentreaders"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/concurrentreaders/concurrentreaderstest"
	"go.thesmos.sh/testkit/engine/model"
)

// TestMixedModelReference holds the reference to the tier it
// anchors: two independent instances driven through the full property, one as
// subject and one as oracle. A failure here is the derivation's own — before
// any consumer's implementation is in the room.
//
// The supplied-option path rides along, so the option, the config and the
// constructor are all exercised by the file that ships them.
func TestMixedModelReference(t *testing.T) {
	t.Parallel()
	model.Check(t, concurrentreaderstest.MixedModelProperty(
		concurrentreaderstest.NewMixedModelReference,
		concurrentreaderstest.MixedModelReference(concurrentreaderstest.NewMixedModelReference),
	))
}

// FuzzMixedModel holds the fuzz wiring to the derived reference —
// the same one-line composition a consumer writes over their own subject. A
// plain `go test` runs the seed as smoke; `-fuzz=FuzzMixedModel` digs.
func FuzzMixedModel(f *testing.F) {
	concurrentreaderstest.MixedModelFuzz(f, concurrentreaderstest.NewMixedModelReference)
}

// TestMixedModelKillsInertMutants measures the tier's teeth: for
// every driven method, a mutant reference answers zeros there and forwards
// nothing, and the property must fail it. A mutant that survives means that
// method's participation in the run checks nothing — a hole in this
// derivation, not in any consumer's subject. The kill rate this asserts is
// total: 2 of 2.
func TestMixedModelKillsInertMutants(t *testing.T) {
	t.Parallel()

	mutants := []struct {
		method string
		wrap   func(concurrentreaders.Mixed) concurrentreaders.Mixed
	}{
		{"Get", func(s concurrentreaders.Mixed) concurrentreaders.Mixed {
			return mixedModelMutantGet{s}
		}},
		{"Put", func(s concurrentreaders.Mixed) concurrentreaders.Mixed {
			return mixedModelMutantPut{s}
		}},
	}
	for _, m := range mutants {
		t.Run(m.method, func(t *testing.T) {
			t.Parallel()
			// The failure is the expectation, so the artifacts a real failure
			// earns — rapid's failfile, the runner's report — are residue
			// here, not regression seeds; the probe removes what it provoked.
			surrogate := "MixedMutant" + m.method
			t.Cleanup(func() {
				_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
				_ = os.Remove(filepath.Join(
					model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
			})
			f := testkit.NewFailableTB().WithName(surrogate)
			model.Check(f, concurrentreaderstest.MixedModelProperty(func() concurrentreaders.Mixed {
				return m.wrap(concurrentreaderstest.NewMixedModelReference())
			}))
			testkit.True(t, f.Failed(),
				"an inert "+m.method+" must diverge from the clean reference")
		})
	}
}

// mixedModelMutantGet answers zeros where Get should act.
type mixedModelMutantGet struct{ concurrentreaders.Mixed }

func (mixedModelMutantGet) Get(_ context.Context, _ string) (r0 string, r1 error) { return }

// mixedModelMutantPut answers zeros where Put should act.
type mixedModelMutantPut struct{ concurrentreaders.Mixed }

func (mixedModelMutantPut) Put(_ context.Context, _ string, _ string) (r0 error) { return }

// testkit: end of generated content.
// testkit:provenance c69029bb2923179cc73769dcc55b93fb35d77bbf3934a7b65764700ba4859d48
