// Code generated by testkit suite. DO NOT EDIT.
// Source: allshapes.go:39-110 (testkit suite -o allshapestest/allshapes_spec.gen_test.go AllShapes)
//
// Directives:
//   Get:    //testkit:errors ErrNotFound  [stub: Fault<Sentinel>() helper per name]
//   Remove: //testkit:deleter

// Package allshapestest_test verifies that any implementation of
// [interfaces.AllShapes] honors the contract declared by the
// source interface. Generated by `testkit suite`.
//
// # Usage
//
//	func TestStoreContract(t *testing.T) {
//	    AssertAllShapesContract(t, func() interfaces.AllShapes {
//	        return newInMemory()
//	    })
//	}
//
// # Multi-impl conformance
//
// Run the same contract once per implementation with
// `t.Run(name, ...)` per impl:
//
//	func TestStoreContractAcrossImpls(t *testing.T) {
//	    AssertAllShapesContractAcrossImpls(t,
//	        suite.NamedFactory[interfaces.AllShapes]{Name: "InMemory", Factory: newInMemory},
//	        suite.NamedFactory[interfaces.AllShapes]{Name: "Postgres",  Factory: newPostgres},
//	    )
//	}
//
// New impls drop into the slice — no per-impl test function to
// hand-wire. The driver emits identical per-method, per-shape, and
// per-directive subtests across every factory.
//
// # Contract coverage
//
// Every non-skipped method gets a smoke subtest that constructs the
// impl, invokes the method with safe arguments (zero-values when
// the method's parameters allow, sample-driven when
// `//testkit:sample` is declared), and fails the test loudly on
// panic. Methods marked `//testkit:integration-only` are skipped —
// the consumer's integration test owns those contracts.
//
// Per-shape baseline assertions (Reader, Writer, Stream, …) and
// per-directive subtests (errors, deprecated, retryable, partition,
// order-after, wrapped-via, …) layer on top of smoke; see the
// [AllShapes contract docs](.) for the full per-shape menu.
package allshapestest_test

import (
	"context"
	"iter"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/generator/testdata/interfaces"
	"go.thesmos.sh/testkit/suite"
)

// AllShapesFactory produces an implementation of [interfaces.AllShapes] for use
// by the contract driver. Each call must yield a fresh, independent
// instance — the contract subtests reset state between runs by
// asking the factory for a new impl.
type AllShapesFactory func() interfaces.AllShapes

// AllShapesNamedFactory pairs a human-readable name with a factory.
// The multi-impl driver runs the contract once per named factory
// with `t.Run(Name, ...)`; the name surfaces in test output.
type AllShapesNamedFactory struct {
	Name    string
	Factory AllShapesFactory
}

// AssertAllShapesContract runs the full AllShapes contract against any
// implementation produced by `factory`. Each subtest constructs a
// fresh impl via the factory so per-test state isolation is the
// caller's responsibility — the factory should return an
// independently-state'd instance every call.
func AssertAllShapesContract(t *testing.T, factory AllShapesFactory) {
	t.Helper()
	errTest := testkit.TestError("AllShapes-contract")
	_ = errTest

	t.Run("All", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.All(t.Context())
		})
		sctx := suite.StreamContextFor[interfaces.AllShapes, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes) iter.Seq2[interfaces.Record, error] {
				seq := impl.All(ctx)
				return func(yield func(interfaces.Record, error) bool) {
					for v := range seq {
						if !yield(v, nil) {
							return
						}
					}
				}
			})
		suite.AssertStreamCompletes[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamRespectsContext[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamReentrant[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamRespectsBreak[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamConcurrentSafe[interfaces.AllShapes, interfaces.Record](4)(sctx)
	})

	t.Run("Count", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _ = impl.Count(t.Context())
		})
		sctx := suite.AggregatorContextFor[interfaces.AllShapes, int](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes) (int, error) {
				return impl.Count(ctx)
			})
		suite.AssertAggregatorReturns[interfaces.AllShapes, int](42)(sctx)
		suite.AssertAggregatorRespectsContext[interfaces.AllShapes, int]()(sctx)
		suite.AssertAggregatorConsistent[interfaces.AllShapes, int](3)(sctx)
		t.Run("rejects invalid", func(t *testing.T) {
			t.Skipf("Count: RejectInvalid baseline reserved for consumer-supplied bounds via AssertAggregatorBounded")
		})
		suite.AssertAggregatorConcurrentSafe[interfaces.AllShapes, int](4, 10)(sctx)
	})

	t.Run("Description", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Description()
		})
		sctx := suite.PureContextFor[interfaces.AllShapes, string](t, factory,
			func(impl interfaces.AllShapes) string {
				return impl.Description()
			})
		suite.AssertPureReturns[interfaces.AllShapes, string]("test-result")(sctx)
		suite.AssertPureRespectsContext[interfaces.AllShapes, string]()(sctx)
		suite.AssertDeterministic[interfaces.AllShapes, string](3)(sctx)
		suite.AssertPureRejectInvalid[interfaces.AllShapes, string]()(sctx)
		suite.AssertPureConcurrentSafe[interfaces.AllShapes, string](4, 10)(sctx)
	})

	t.Run("Err", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Err()
		})
		sctx := suite.PoisonAccessorContextFor[interfaces.AllShapes](t, factory,
			func(impl interfaces.AllShapes) error {
				return impl.Err()
			})
		suite.AssertPoisonAccessorNilOnFresh[interfaces.AllShapes]()(sctx)
		suite.AssertPoisonAccessorRespectsContext[interfaces.AllShapes]()(sctx)
		suite.AssertPoisonAccessorConsistent[interfaces.AllShapes]()(sctx)
		t.Run("rejects invalid (poisoned)", func(t *testing.T) {
			t.Skipf("Err: AssertPoisonAccessorRejectInvalid requires consumer-supplied poisonedFactory + sentinel")
		})
		suite.AssertPoisonAccessorConcurrentSafe[interfaces.AllShapes](4, 10)(sctx)
	})

	t.Run("Fetch", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _, _ = impl.Fetch(t.Context(), "test-key")
		})
		sctx := suite.MultiReaderContextFor[interfaces.AllShapes, string, interfaces.Record, string](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, key string) (interfaces.Record, string, error) {
				return impl.Fetch(ctx, key)
			})
		suite.AssertMultiReaderReturnsForKey[interfaces.AllShapes, string, interfaces.Record, string]("test-key", interfaces.Record{ID: "test-id"}, "test-result")(sctx)
		suite.AssertMultiReaderRespectsContext[interfaces.AllShapes, string, interfaces.Record, string]("test-key")(sctx)
		suite.AssertMultiReaderConsistent[interfaces.AllShapes, string, interfaces.Record, string]("test-key", 3)(sctx)
		t.Run("rejects invalid (no sentinel)", func(t *testing.T) {
			t.Skipf("Fetch: RejectInvalid baseline requires //testkit:errors <Sentinel>")
		})
		suite.AssertMultiReaderConcurrentSafe[interfaces.AllShapes, string, interfaces.Record, string]("test-key", 4, 10)(sctx)
	})

	t.Run("Find", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Find(t.Context(), "test-key")
		})
		sctx := suite.PointerReaderContextFor[interfaces.AllShapes, string, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, key string) *interfaces.Record {
				return impl.Find(ctx, key)
			})
		suite.AssertPointerReaderReturnsForKey[interfaces.AllShapes, string, interfaces.Record]("test-key", &interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertPointerReaderRespectsContext[interfaces.AllShapes, string, interfaces.Record]("test-key")(sctx)
		suite.AssertPointerReaderConsistent[interfaces.AllShapes, string, interfaces.Record]("test-key", 3)(sctx)
		suite.AssertPointerReaderNilOnUnknown[interfaces.AllShapes, string, interfaces.Record]("")(sctx)
		suite.AssertPointerReaderConcurrentSafe[interfaces.AllShapes, string, interfaces.Record]("test-key", 4, 10)(sctx)
	})

	t.Run("Get", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _ = impl.Get(t.Context(), "test-key")
		})
		sctx := suite.ReaderContextFor[interfaces.AllShapes, string, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, key string) (interfaces.Record, error) {
				return impl.Get(ctx, key)
			})
		suite.AssertReturnsForKey[interfaces.AllShapes, string, interfaces.Record]("test-key", interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertReaderRespectsContext[interfaces.AllShapes, string, interfaces.Record]("test-key")(sctx)
		suite.AssertConsistentReads[interfaces.AllShapes, string, interfaces.Record]("test-key", 3)(sctx)
		suite.AssertReturnsSentinel[interfaces.AllShapes, string, interfaces.Record]("", interfaces.ErrNotFound)(sctx)
		suite.AssertReaderConcurrentSafe[interfaces.AllShapes, string, interfaces.Record]("test-key", 4, 10)(sctx)
	})

	t.Run("Init", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Init(t.Context())
		})
		sctx := suite.LifecycleContextFor[interfaces.AllShapes](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes) error {
				return impl.Init(ctx)
			})
		suite.AssertLifecycleSucceeds[interfaces.AllShapes]()(sctx)
		suite.AssertLifecycleRespectsContext[interfaces.AllShapes]()(sctx)
		suite.AssertLifecycleIdempotent[interfaces.AllShapes]()(sctx)
		t.Run("rejects invalid", func(t *testing.T) {
			t.Skipf("Init: AssertLifecycleRejectInvalid requires consumer-supplied invalidFactory + sentinel")
		})
		suite.AssertLifecycleConcurrentSafe[interfaces.AllShapes](4, 10)(sctx)
	})

	t.Run("Inspect", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _, _ = impl.Inspect(t.Context(), "test-key")
		})
		sctx := suite.LookupContextFor[interfaces.AllShapes, string, interfaces.Record, string](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, key string) (interfaces.Record, string, bool) {
				return impl.Inspect(ctx, key)
			})
		suite.AssertLookupReturns[interfaces.AllShapes, string, interfaces.Record, string]("test-key", interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertLookupRespectsContext[interfaces.AllShapes, string, interfaces.Record, string]("test-key")(sctx)
		suite.AssertLookupConsistent[interfaces.AllShapes, string, interfaces.Record, string]("test-key", 3)(sctx)
		suite.AssertLookupMissing[interfaces.AllShapes, string, interfaces.Record, string]("")(sctx)
		suite.AssertLookupConcurrentSafe[interfaces.AllShapes, string, interfaces.Record, string]("test-key", 4, 10)(sctx)
	})

	t.Run("IsHealthy", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.IsHealthy()
		})
		sctx := suite.PredicateContextFor[interfaces.AllShapes](t, factory,
			func(impl interfaces.AllShapes) bool {
				return impl.IsHealthy()
			})
		suite.AssertPredicateReturns[interfaces.AllShapes](true)(sctx)
		suite.AssertPredicateRespectsContext[interfaces.AllShapes]()(sctx)
		suite.AssertPredicateConsistent[interfaces.AllShapes](3)(sctx)
		suite.AssertPredicateRejectInvalid[interfaces.AllShapes]()(sctx)
		suite.AssertPredicateConcurrentSafe[interfaces.AllShapes](4, 10)(sctx)
	})

	t.Run("Load", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _ = impl.Load(t.Context(), "test-key")
		})
		sctx := suite.ReaderWithBoolContextFor[interfaces.AllShapes, string, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, key string) (interfaces.Record, bool) {
				return impl.Load(ctx, key)
			})
		suite.AssertReaderWithBoolReturns[interfaces.AllShapes, string, interfaces.Record]("test-key", interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertReaderWithBoolRespectsContext[interfaces.AllShapes, string, interfaces.Record]("test-key")(sctx)
		suite.AssertReaderWithBoolConsistent[interfaces.AllShapes, string, interfaces.Record]("test-key", 3)(sctx)
		suite.AssertReaderWithBoolMissing[interfaces.AllShapes, string, interfaces.Record]("")(sctx)
		suite.AssertReaderWithBoolConcurrentSafe[interfaces.AllShapes, string, interfaces.Record]("test-key", 4, 10)(sctx)
	})

	t.Run("Lookup", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Lookup(t.Context(), "test-key")
		})
		sctx := suite.ReaderNoErrorContextFor[interfaces.AllShapes, string, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, key string) interfaces.Record {
				return impl.Lookup(ctx, key)
			})
		suite.AssertReaderNoErrorReturnsForKey[interfaces.AllShapes, string, interfaces.Record]("test-key", interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertReaderNoErrorRespectsContext[interfaces.AllShapes, string, interfaces.Record]("test-key")(sctx)
		suite.AssertReaderNoErrorConsistent[interfaces.AllShapes, string, interfaces.Record]("test-key", 3)(sctx)
		suite.AssertReaderNoErrorZeroOnUnknown[interfaces.AllShapes, string, interfaces.Record]("", interfaces.Record{})(sctx)
		suite.AssertReaderNoErrorConcurrentSafe[interfaces.AllShapes, string, interfaces.Record]("test-key", 4, 10)(sctx)
	})

	t.Run("Many", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _ = impl.Many(t.Context())
		})
		sctx := suite.BatchReaderContextFor[interfaces.AllShapes, string, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, keys []string) ([]interfaces.Record, error) {
				return impl.Many(ctx, keys...)
			})
		sampleKeys := []string{"test-keys"}
		sampleVals := []interfaces.Record{interfaces.Record{ID: "test-id"}}
		suite.AssertBatchReaderReturnsAll[interfaces.AllShapes, string, interfaces.Record](sampleKeys, sampleVals)(sctx)
		suite.AssertBatchReaderRespectsContext[interfaces.AllShapes, string, interfaces.Record](sampleKeys)(sctx)
		suite.AssertBatchReaderConsistent[interfaces.AllShapes, string, interfaces.Record](sampleKeys, 3)(sctx)
		t.Run("rejects invalid (no sentinel)", func(t *testing.T) {
			t.Skipf("Many: RejectInvalid baseline requires //testkit:errors <Sentinel>")
		})
		suite.AssertBatchReaderConcurrentSafe[interfaces.AllShapes, string, interfaces.Record](sampleKeys, 4, 10)(sctx)
	})

	t.Run("Put", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Put(t.Context(), interfaces.Record{ID: "test-id"})
		})
		sctx := suite.WriterContextFor[interfaces.AllShapes, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, value interfaces.Record) error {
				return impl.Put(ctx, value)
			})
		suite.AssertWriteSucceeds[interfaces.AllShapes, interfaces.Record](interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertWriterRespectsContext[interfaces.AllShapes, interfaces.Record](interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertWriterIdempotent[interfaces.AllShapes, interfaces.Record](interfaces.Record{ID: "test-id"})(sctx)
		t.Run("rejects invalid (no sentinel)", func(t *testing.T) {
			t.Skipf("Put: RejectInvalid baseline requires //testkit:errors <Sentinel>; subtest omitted to avoid a meaningless assertion")
		})
		suite.AssertWriterConcurrentSafe[interfaces.AllShapes, interfaces.Record](interfaces.Record{ID: "test-id"}, 4, 10)(sctx)
	})

	t.Run("ReadFrom", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _ = impl.ReadFrom(t.Context(), nil)
		})
		t.Run("succeeds", func(t *testing.T) {
			t.Skipf("ReadFrom: AssertStreamConsumerSucceeds requires a consumer-supplied stream + want value")
		})
		t.Run("respects context", func(t *testing.T) {
			t.Skipf("ReadFrom: AssertStreamConsumerRespectsContext requires a consumer-supplied stream value")
		})
		t.Run("consistent", func(t *testing.T) {
			t.Skipf("ReadFrom: AssertStreamConsumerConsistent requires a consumer-supplied stream factory")
		})
		t.Run("rejects invalid", func(t *testing.T) {
			t.Skipf("ReadFrom: AssertStreamConsumerRejectInvalid requires a consumer-supplied invalid stream + sentinel")
		})
		t.Run("concurrent safe", func(t *testing.T) {
			t.Skipf("ReadFrom: AssertStreamConsumerConcurrentSafe requires a consumer-supplied stream factory")
		})
	})

	t.Run("Remove", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Remove(t.Context(), "test-key")
		})
		sctx := suite.DeleterContextFor[interfaces.AllShapes, string](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, key string) error {
				return impl.Remove(ctx, key)
			})
		suite.AssertDeleteSucceeds[interfaces.AllShapes, string]("test-key")(sctx)
		suite.AssertDeleterRespectsContext[interfaces.AllShapes, string]("test-key")(sctx)
		suite.AssertDeleteIdempotent[interfaces.AllShapes, string]("test-key")(sctx)
		t.Run("rejects invalid (no sentinel)", func(t *testing.T) {
			t.Skipf("Remove: RejectInvalid baseline requires //testkit:errors <NotFound> sentinel; subtest omitted")
		})
		suite.AssertDeleterConcurrentSafe[interfaces.AllShapes, string]("test-key", 4, 10)(sctx)
	})

	t.Run("Reset", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			impl.Reset()
		})
		sctx := suite.VoidLifecycleContextFor[interfaces.AllShapes](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes) {
				impl.Reset()
			})
		suite.AssertVoidLifecycleSucceeds[interfaces.AllShapes]()(sctx)
		suite.AssertVoidLifecycleRespectsContext[interfaces.AllShapes]()(sctx)
		suite.AssertVoidLifecycleIdempotent[interfaces.AllShapes]()(sctx)
		t.Run("rejects invalid", func(t *testing.T) {
			t.Skipf("Reset: AssertVoidLifecycleRejectInvalid requires consumer-supplied invalidFactory + check")
		})
		suite.AssertVoidLifecycleConcurrentSafe[interfaces.AllShapes](4, 10)(sctx)
	})

	t.Run("Scan", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Scan(t.Context())
		})
		sctx := suite.StreamContextFor[interfaces.AllShapes, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes) iter.Seq2[interfaces.Record, error] {
				return impl.Scan(ctx)
			})
		suite.AssertStreamCompletes[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamRespectsContext[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamReentrant[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamRespectsBreak[interfaces.AllShapes, interfaces.Record]()(sctx)
		suite.AssertStreamConcurrentSafe[interfaces.AllShapes, interfaces.Record](4)(sctx)
	})

	t.Run("Schedule", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Schedule(t.Context(), "test-key", interfaces.Record{ID: "test-id"}, 42)
		})
		sctx := suite.MultiArgWriterContextFor[interfaces.AllShapes, string, interfaces.Record, int](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, p1 string, p2 interfaces.Record, p3 int) error {
				return impl.Schedule(ctx, p1, p2, p3)
			})
		suite.AssertMultiArgWriteSucceeds[interfaces.AllShapes, string, interfaces.Record, int]("test-key", interfaces.Record{ID: "test-id"}, 42)(sctx)
		suite.AssertMultiArgWriterRespectsContext[interfaces.AllShapes, string, interfaces.Record, int]("test-key", interfaces.Record{ID: "test-id"}, 42)(sctx)
		suite.AssertMultiArgWriterIdempotent[interfaces.AllShapes, string, interfaces.Record, int]("test-key", interfaces.Record{ID: "test-id"}, 42)(sctx)
		t.Run("rejects invalid (no sentinel)", func(t *testing.T) {
			t.Skipf("Schedule: RejectInvalid baseline requires //testkit:errors <Sentinel>")
		})
		suite.AssertMultiArgWriterConcurrentSafe[interfaces.AllShapes, string, interfaces.Record, int]("test-key", interfaces.Record{ID: "test-id"}, 42, 4, 10)(sctx)
	})

	t.Run("Set", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_ = impl.Set(t.Context(), "test-key", interfaces.Record{ID: "test-id"})
		})
		sctx := suite.CompositeWriterContextFor[interfaces.AllShapes, string, interfaces.Record](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, k1 string, value interfaces.Record) error {
				return impl.Set(ctx, k1, value)
			})
		suite.AssertCompositeWriteSucceeds[interfaces.AllShapes, string, interfaces.Record]("test-key", interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertCompositeWriterRespectsContext[interfaces.AllShapes, string, interfaces.Record]("test-key", interfaces.Record{ID: "test-id"})(sctx)
		suite.AssertCompositeWriterIdempotent[interfaces.AllShapes, string, interfaces.Record]("test-key", interfaces.Record{ID: "test-id"})(sctx)
		t.Run("rejects invalid (no sentinel)", func(t *testing.T) {
			t.Skipf("Set: RejectInvalid baseline requires //testkit:errors <Sentinel>")
		})
		suite.AssertCompositeWriterConcurrentSafe[interfaces.AllShapes, string, interfaces.Record]("test-key", interfaces.Record{ID: "test-id"}, 4, 10)(sctx)
	})

	t.Run("Statistics", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _, _, _ = impl.Statistics(t.Context())
		})
	})

	t.Run("Stats", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			_, _, _ = impl.Stats(t.Context())
		})
		sctx := suite.MultiAggregatorContextFor[interfaces.AllShapes, int, int](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes) (int, int, error) {
				return impl.Stats(ctx)
			})
		suite.AssertMultiAggregatorReturns[interfaces.AllShapes, int, int](42, 42)(sctx)
		suite.AssertMultiAggregatorRespectsContext[interfaces.AllShapes, int, int]()(sctx)
		suite.AssertMultiAggregatorConsistent[interfaces.AllShapes, int, int](3)(sctx)
		t.Run("rejects invalid", func(t *testing.T) {
			t.Skipf("Stats: AssertMultiAggregatorReturnsSentinel requires consumer-supplied invalidFactory + sentinel")
		})
		suite.AssertMultiAggregatorConcurrentSafe[interfaces.AllShapes, int, int](4, 10)(sctx)
	})

	t.Run("Touch", func(t *testing.T) {
		t.Run("smoke", func(t *testing.T) {
			t.Parallel()
			impl := factory()
			impl.Touch(t.Context(), "test-key")
		})
		sctx := suite.MutatorContextFor[interfaces.AllShapes, string](t, factory,
			func(ctx context.Context, impl interfaces.AllShapes, value string) {
				impl.Touch(ctx, value)
			})
		suite.AssertMutatorSucceeds[interfaces.AllShapes, string]("test-key")(sctx)
		suite.AssertMutatorRespectsContext[interfaces.AllShapes, string]("test-key")(sctx)
		suite.AssertMutatorIdempotent[interfaces.AllShapes, string]("test-key")(sctx)
		t.Run("rejects invalid", func(t *testing.T) {
			t.Skipf("Touch: AssertMutatorRejectInvalid requires consumer-supplied check observing rejection via paired reader/aggregator")
		})
		suite.AssertMutatorConcurrentSafe[interfaces.AllShapes, string]("test-key", 4, 10)(sctx)
	})

}

// AssertAllShapesContractAcrossImpls runs [AssertAllShapesContract] once per named factory under
// `t.Run(Name, ...)`. New impls drop in via slice append.
func AssertAllShapesContractAcrossImpls(t *testing.T, factories ...AllShapesNamedFactory) {
	t.Helper()
	for _, nf := range factories {
		t.Run(nf.Name, func(t *testing.T) {
			t.Parallel()
			AssertAllShapesContract(t, nf.Factory)
		})
	}
}
