// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/causal/iface.go
// Plugins:   golang 1.0.0, model 0.63.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package causaltest

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"sync/atomic"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/causal"
	"go.thesmos.sh/testkit/core/trace"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
	"go.thesmos.sh/testkit/engine/model/linearize"
)

// MixedModel runs random sequences of Mixed's methods against every
// subject and a known-good in-memory reference side by side, comparing after
// every call. Pass it to AssertMixedContract; it reports under
// "model/twin", and MixedWithout("model/twin") declines it.
//
//	Reference: the subject's own factory — the subject assigns the version member on write, which no value-storing oracle stamps,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Store (answeringwriter), Get (reader)
//	Sessions:  per-client laws read Rev off Get's value; the
//	           concurrent leg interleaves real clients over a stepless model —
//	           a store-assigned stamp defeats value equality, so the laws carry it
//	Values:    the fixture pair blended with arbitrary draws, each keyed
//	           from the pool; MixedModelValues replaces the pool
//	Concurrent: Store and Get interleave across four workers;
//	           the per-client laws read the multi-client trace — stepless,
//	           because a store-assigned Rev defeats value equality
//	Laws:      AUTO-CAUSAL-ORDERING (supplied: happensBefore)
func MixedModel(opts ...MixedModelOption) MixedOption {
	return func(c *mixedConfig) {
		c.extensions = append(c.extensions, mixedContractExtension{
			name: "model/twin",
			run: func(t *testing.T, _ string, factory func() causal.Mixed, _ *mixedConfig) {
				model.Check(t, MixedModelProperty(factory, opts...))
			},
		})
		c.extensions = append(c.extensions, mixedContractExtension{
			name: "model/concurrent",
			run: func(t *testing.T, _ string, factory func() causal.Mixed, _ *mixedConfig) {
				MixedModelConcurrent(t, factory, opts...)
			},
		})
	}
}

// MixedModelProperty builds the property the option runs — exported because a
// bespoke harness composes from here: model.Check for a test, model.MakeFuzz
// for a coverage-guided fuzz target, both over this one derivation.
func MixedModelProperty(factory func() causal.Mixed, opts ...MixedModelOption) func(*model.T) {
	cfg := newMixedModelConfig(opts...)
	fx := DefaultMixedFixture()
	// Two keys, drawn for every key slot: collision density is what makes a
	// read revisit a write and an overwrite land on held state. A wide key
	// pool would pass every comparison over a history that never collides.
	keys := model.SampledFrom([]string{fx.Key, fx.KeyOther})
	// Bodies blend the fixture pair with arbitrary draws: the pair keeps
	// identical rewrites frequent, the wide arm reaches values no fixture
	// spells — and nothing in the claims licenses refusing either.
	bodies := model.OneOf(
		model.SampledFrom([]causal.Value{fx.V, fx.VOther}),
		model.Make[causal.Value](),
	)
	// Every drawn value lands on a pooled key: a key rewritten under another
	// body is the history latest-write-wins is about, and a fresh-keyed value
	// would never collide with one already held.
	values := model.Custom(func(t *model.T) causal.Value {
		v := bodies.Draw(t, "value_body")
		v.Key = keys.Draw(t, "value_key")
		return v
	})
	if cfg.values != nil {
		values = cfg.values
	}
	reference := cfg.reference
	if reference == nil {
		reference = factory
	}
	// The laws the classifications earned, each reporting under its AUTO-
	// identifier when it fails. Observational: a law never mutates, so running
	// them inside the sequences is safe for every step that follows.
	laws := model.NewRegistry[causal.Mixed]()
	if cfg.happensBefore != nil {
		laws.Add(&law.CausalOrdering[causal.Mixed, string]{
			Classify:      mixedSessionClassify,
			HappensBefore: cfg.happensBefore,
		})
	} else {
		laws.Declined("AUTO-CAUSAL-ORDERING",
			"MixedModelHappens Before")
	}
	// The saturation prover's isolation: with siblings registered, the first
	// law to catch a defect ends the iteration and every other law bound on
	// the same methods reads as unsaturatable.
	if cfg.onlyLaw != "" {
		for _, l := range laws.Laws() {
			if l.ID() != cfg.onlyLaw {
				laws.SkipByID(l.ID())
			}
		}
	}
	return model.Property(factory,
		model.WithReference(reference),
		model.WithLaws(laws),
		// Isolating one law is the prover asking whether that law can fail,
		// and the differential answers first for almost any defect — the
		// worn subject disagrees with the clean reference at step 0 and the
		// iteration ends before a law is consulted. Silencing it is what
		// leaves the law as the only witness. A conformance run isolates
		// nothing, so this is false there and the differential stays armed.
		model.WithLawsOnly[causal.Mixed](cfg.onlyLaw != ""),
		model.WithActions(
			action.AnsweringWriter("Store", values,
				func(ctx context.Context, s causal.Mixed, v causal.Value) (causal.Value, error) {
					return s.Store(ctx, v)
				}),
			action.Reader("Get", keys,
				func(ctx context.Context, s causal.Mixed, k string) (causal.Value, error) {
					return s.Get(ctx, k)
				}),
		),
	)
}

// MixedModelFuzz hands a subject's sequence space to the
// coverage-guided engine: the fuzzer's bytes replay as rapid's choice
// stream, so mutating them mutates the action ordering and every drawn
// input at once — and the engine's coverage feedback climbs the subject's
// own branches, which is what no fixed seed can do. Wire it from a fuzz
// target beside the subject:
//
//	func FuzzMixed(f *testing.F) {
//		MixedModelFuzz(f, func() Mixed { return NewMine() })
//	}
func MixedModelFuzz(f *testing.F, factory func() causal.Mixed, opts ...MixedModelOption) {
	f.Add([]byte{})
	f.Fuzz(model.MakeFuzz(MixedModelProperty(factory, opts...)))
}

// MixedModelConcurrent runs the linearizability leg: four workers
// interleave Store and Get over the shared pools, and hold
// the recorded interleaving to the per-client session laws. No Porcupine
// model runs here — the subject assigns Rev on write, which no
// value-equality model predicts — so the trace-scanning laws are the check.
// and the laws stay with the sequential leg, whose step boundary they need.
// Exported for the same bespoke harnesses the property serves.
func MixedModelConcurrent(t *testing.T, factory func() causal.Mixed, opts ...MixedModelOption) {
	cfg := newMixedModelConfig(opts...)
	fx := DefaultMixedFixture()
	// Two keys, drawn for every key slot: collision density is what makes a
	// read revisit a write and an overwrite land on held state. A wide key
	// pool would pass every comparison over a history that never collides.
	keys := model.SampledFrom([]string{fx.Key, fx.KeyOther})
	// Bodies blend the fixture pair with arbitrary draws: the pair keeps
	// identical rewrites frequent, the wide arm reaches values no fixture
	// spells — and nothing in the claims licenses refusing either.
	bodies := model.OneOf(
		model.SampledFrom([]causal.Value{fx.V, fx.VOther}),
		model.Make[causal.Value](),
	)
	// Every drawn value lands on a pooled key: a key rewritten under another
	// body is the history latest-write-wins is about, and a fresh-keyed value
	// would never collide with one already held.
	values := model.Custom(func(t *model.T) causal.Value {
		v := bodies.Draw(t, "value_body")
		v.Key = keys.Draw(t, "value_key")
		return v
	})
	if cfg.values != nil {
		values = cfg.values
	}
	model.Assert(t, factory,
		model.WithConcurrent(model.ConcurrentConfig[causal.Mixed]{
			// Stepless on purpose: the subject assigns Rev on write, and
			// no value-equality model survives a stamp it cannot predict. The
			// per-client laws over the recorded interleaving are the check.
			Actions: []model.ConcurrentAction[causal.Mixed]{
				linearize.ConcurrentAnsweringWriter("Store", values,
					func(ctx context.Context, s causal.Mixed, v causal.Value) (causal.Value, error) {
						return s.Store(ctx, v)
					}, func(v causal.Value) string { return v.Key }),
				linearize.ConcurrentReader("Get", keys,
					func(ctx context.Context, s causal.Mixed, k string) (causal.Value, error) {
						return s.Get(ctx, k)
					}),
			},
		}),
		model.WithLaw(&law.CausalOrdering[causal.Mixed, string]{
			Classify:      mixedSessionClassify,
			HappensBefore: cfg.happensBefore,
		}),
	)
}

// mixedSessionClassify interprets one trace event as a per-client
// operation: the ordering stamp rides the value's Rev member, and an
// errored call classifies nothing — a miss's zero value is not a version.
func mixedSessionClassify(ev trace.Event) (law.ClientOp[string], bool) {
	if ev.Err != nil {
		return law.ClientOp[string]{}, false
	}
	switch ev.Method {
	case "Get":
		v, ok := ev.Output.(causal.Value)
		if !ok {
			return law.ClientOp[string]{}, false
		}
		return law.ClientOp[string]{Key: v.Key, Version: int64(v.Rev)}, true
	case "Store":
		v, ok := ev.Output.(causal.Value)
		if !ok {
			return law.ClientOp[string]{}, false
		}
		return law.ClientOp[string]{Write: true, Key: v.Key, Version: int64(v.Rev)}, true
	}
	return law.ClientOp[string]{}, false
}

// MixedModelOption configures the model run.
type MixedModelOption func(*mixedModelConfig)

// MixedModelReference replaces the derived reference — for an
// interface whose semantics outrun its shape.
func MixedModelReference(factory func() causal.Mixed) MixedModelOption {
	return func(c *mixedModelConfig) { c.reference = factory }
}

// MixedModelHappensBefore supplies the happensBefore closure — a domain fact
// no derivation can invent. Every law reading it arms only under this
// option; unarmed, the header still names the door.
func MixedModelHappensBefore(fn func(a, b law.ClientOp[string]) bool) MixedModelOption {
	return func(c *mixedModelConfig) { c.happensBefore = fn }
}

// MixedSatWear is one wearable defect: a kind, and the wrap that
// dresses a subject in it.
type mixedSatWear struct {
	kind string
	wrap func(fx MixedFixture, s causal.Mixed) causal.Mixed
}

//nolint:gochecknoglobals // the prover's wardrobe, read-only after init.
var mixedSatWears = map[string][]mixedSatWear{}

//nolint:gochecknoinits // the wardrobe fills once, keyed by method.
func init() { //nolint:staticcheck // an empty wardrobe leaves dress unused by design.
	dress := func(method, kind string, wrap func(fx MixedFixture, s causal.Mixed) causal.Mixed) {
		mixedSatWears[method] = append(mixedSatWears[method],
			mixedSatWear{kind: kind, wrap: wrap})
	}
	dress("Get", "inert", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return mixedSatInertGet{s}
	})
	dress("Get", "flicker", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return &mixedSatFlickerGet{Mixed: s}
	})
	dress("Get", "sputter", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return &mixedSatSputterGet{Mixed: s}
	})
	dress("Get", "regress", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return &mixedSatRegressGet{Mixed: s}
	})
	dress("Get", "spill", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return mixedSatSpillGet{s}
	})
	dress("Get", "flap", func(fx MixedFixture, s causal.Mixed) causal.Mixed {
		return &mixedSatFlapGet{Mixed: s, a: fx.V, b: fx.VOther}
	})
	dress("Store", "inert", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return mixedSatInertStore{s}
	})
	dress("Store", "flicker", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return &mixedSatFlickerStore{Mixed: s}
	})
	dress("Store", "sputter", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return &mixedSatSputterStore{Mixed: s}
	})
	dress("Store", "spill", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return mixedSatSpillStore{s}
	})
	dress("Store", "passthrough", func(_ MixedFixture, s causal.Mixed) causal.Mixed {
		return mixedSatPassthroughStore{s}
	})
	dress("Store", "flap", func(fx MixedFixture, s causal.Mixed) causal.Mixed {
		return &mixedSatFlapStore{Mixed: s, a: fx.V, b: fx.VOther}
	})
}

// MixedModelSaturation proves the bound laws can fail: per law, a
// defect is worn on each method the law's closures reach — zeros, the
// fixture pair alternated, a waning count — and at least one worn run must
// fail naming the law's own identifier, with the clean factory standing as
// reference. A law every defect survives is bound but unsaturatable, and
// fails here by name. Pass the same options that arm the tier: a law behind
// an unarmed door or the clocked factory is skipped visibly, never counted.
func MixedModelSaturation(t *testing.T, factory func() causal.Mixed, opts ...MixedModelOption) {
	t.Helper()
	cfg := newMixedModelConfig(opts...)
	_ = cfg
	fx := DefaultMixedFixture()
	_ = fx
	t.Run("AUTO-CAUSAL-ORDERING", func(t *testing.T) {
		if cfg.happensBefore == nil {
			t.Skip("the happensBefore door is not armed here, and the law registers only armed")
		}
		killed := func() bool {
			for _, method := range []string{"Get", "Store"} {
				for _, wear := range mixedSatWears[method] {
					// Two references per defect. Silencing the differential leaves
					// the law as the only witness, but not every action reports
					// through it: a shape whose action fails structurally still
					// ends the iteration, and a reference wearing the same defect
					// behaves the same way the subject does, so nothing diverges
					// and the law is reached. A law that *is* the comparison needs
					// the opposite — with both sides worn it has nothing to
					// disagree with — so the clean reference runs too and either
					// kill counts. The corpus measured both: dropping either one
					// loses laws that only the other can saturate.
					for _, blind := range []bool{true, false} {
						surrogate := "MixedSat_AUTO-CAUSAL-ORDERING_" + method + "_" + wear.kind
						if blind {
							surrogate += "_blind"
						}
						t.Cleanup(func() {
							_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
							_ = os.Remove(filepath.Join(
								model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
						})
						reference := factory
						if blind {
							reference = func() causal.Mixed { return wear.wrap(fx, factory()) }
						}
						f := testkit.NewFailableTB().WithName(surrogate)
						worn := append(slices.Clone(opts),
							MixedModelReference(reference),
							mixedModelOnlyLaw("AUTO-CAUSAL-ORDERING"))
						model.Check(f, MixedModelProperty(func() causal.Mixed {
							return wear.wrap(fx, factory())
						}, worn...))
						// The reporter's own rendering, not the bare identifier.
						// rapid echoes the TB's name into its final message and the
						// surrogate above is named for this law, so matching the
						// identifier alone matched the name — the criterion reduced
						// to f.Failed() and every defect "killed" every law. The
						// verdict's format carries the identifier where no name can:
						// after the kind, which is the one place only the reporter
						// writes. The suffix rather than the whole prefix because a
						// REQ-tagged law renders "[REQ-1 invariant]".
						if f.Failed() && (strings.Contains(f.Msg(), "invariant] AUTO-CAUSAL-ORDERING")) {
							return true
						}
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-CAUSAL-ORDERING survived every defect worn on its own methods — bound but unsaturatable")
		}
		// Not yet narrowed to this law's own defect class. The wears whose
		// class its name claims are
		// jumble, latch — requiring the kill to come from one
		// of those reddens 23 laws across the corpus, and the measurement says
		// roughly a third are weak laws and the rest are wrong classes. That
		// triage is 1.10b. What ships here is the skip above, which is the
		// half the measurement settled.
	})
}

// mixedSatInertGet answers zeros where Get should act.
type mixedSatInertGet struct{ causal.Mixed }

func (mixedSatInertGet) Get(_ context.Context, _ string) (z0 causal.Value, z1 error) {
	return
}

// mixedSatFlickerGet answers zeros every second
// call, where Get should answer the same thing twice.
//
// The defect every stability claim names: cacheable, deterministic,
// consistent, non-decreasing are all about two calls agreeing, and a subject
// that answers zeros *forever* agrees with itself perfectly. Only an answer
// that changes breaks them, and alternating with the zero is the smallest
// change available at any return type.
type mixedSatFlickerGet struct {
	causal.Mixed
	flip atomic.Int64
}

func (m *mixedSatFlickerGet) Get(p0 context.Context, p1 string) (z0 causal.Value, z1 error) {
	if m.flip.Add(1)%2 == 0 {
		return
	}
	return m.Mixed.Get(p0, p1)
}

// mixedSatSputterGet alternates a minted refusal
// with the real answer where Get should be steady.
type mixedSatSputterGet struct {
	causal.Mixed
	flip atomic.Int64
}

func (m *mixedSatSputterGet) Get(p0 context.Context, p1 string) (z0 causal.Value, z1 error) {
	if m.flip.Add(1)%2 == 1 {
		z1 = errors.New("causaltest: saturation sputtered a refusal")
		return
	}
	return m.Mixed.Get(p0, p1)
}

// mixedSatRegressGet answers Get's own
// value with Rev walked backwards, and every other member left as
// the subject set it.
//
// One member rather than the whole value, because the session laws read the
// key off the same answer they order. A wear replacing the value files each
// read under a different key, and a law that never compares two reads of one
// key cannot fail — which is what every zero-answering defect did here.
//
// The stamp descends from whatever the subject last returned, so the second
// read of a key is strictly older than the first however the subject numbers
// its versions.
type mixedSatRegressGet struct {
	causal.Mixed
	mu   sync.Mutex
	held bool
	prev causal.Value
}

func (m *mixedSatRegressGet) Get(p0 context.Context, p1 string) (causal.Value, error) {
	out, err := m.Mixed.Get(p0, p1)
	if err != nil {
		return out, err
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.held {
		out.Rev = m.prev.Rev - 1
	}
	m.held, m.prev = true, out
	return out, nil
}

// mixedSatSpillGet refuses while answering what
// Get actually found — whatever the failed lookup left behind.
//
// Every refusal the wardrobe mints elsewhere arrives with the zero value
// beside it, and the value a failed read is supposed to answer is usually the
// zero. So the defect and the claim agree, and a law about what an error must
// coincide with has nothing that can disagree with it.
type mixedSatSpillGet struct{ causal.Mixed }

func (m mixedSatSpillGet) Get(p0 context.Context, p1 string) (causal.Value, error) {
	out, err := m.Mixed.Get(p0, p1)
	if err != nil {
		return out, err
	}
	return out, errors.New("causaltest: saturation spilled a found value into a refusal")
}

// mixedSatFlapGet alternates the fixture pair where
// Get should answer the store.
type mixedSatFlapGet struct {
	causal.Mixed
	flip atomic.Int64
	a, b causal.Value
}

func (m *mixedSatFlapGet) Get(_ context.Context, _ string) (causal.Value, error) {
	if m.flip.Add(1)%2 == 0 {
		return m.a, nil
	}
	return m.b, nil
}

// mixedSatInertStore answers zeros where Store should act.
type mixedSatInertStore struct{ causal.Mixed }

func (mixedSatInertStore) Store(_ context.Context, _ causal.Value) (z0 causal.Value, z1 error) {
	return
}

// mixedSatFlickerStore answers zeros every second
// call, where Store should answer the same thing twice.
//
// The defect every stability claim names: cacheable, deterministic,
// consistent, non-decreasing are all about two calls agreeing, and a subject
// that answers zeros *forever* agrees with itself perfectly. Only an answer
// that changes breaks them, and alternating with the zero is the smallest
// change available at any return type.
type mixedSatFlickerStore struct {
	causal.Mixed
	flip atomic.Int64
}

func (m *mixedSatFlickerStore) Store(p0 context.Context, p1 causal.Value) (z0 causal.Value, z1 error) {
	if m.flip.Add(1)%2 == 0 {
		return
	}
	return m.Mixed.Store(p0, p1)
}

// mixedSatSputterStore alternates a minted refusal
// with the real answer where Store should be steady.
type mixedSatSputterStore struct {
	causal.Mixed
	flip atomic.Int64
}

func (m *mixedSatSputterStore) Store(p0 context.Context, p1 causal.Value) (z0 causal.Value, z1 error) {
	if m.flip.Add(1)%2 == 1 {
		z1 = errors.New("causaltest: saturation sputtered a refusal")
		return
	}
	return m.Mixed.Store(p0, p1)
}

// mixedSatSpillStore refuses while answering what
// Store actually found — whatever the failed lookup left behind.
//
// Every refusal the wardrobe mints elsewhere arrives with the zero value
// beside it, and the value a failed read is supposed to answer is usually the
// zero. So the defect and the claim agree, and a law about what an error must
// coincide with has nothing that can disagree with it.
type mixedSatSpillStore struct{ causal.Mixed }

func (m mixedSatSpillStore) Store(p0 context.Context, p1 causal.Value) (causal.Value, error) {
	out, err := m.Mixed.Store(p0, p1)
	if err != nil {
		return out, err
	}
	return out, errors.New("causaltest: saturation spilled a found value into a refusal")
}

// mixedSatPassthroughStore answers Store's
// argument verbatim, where the method's whole job was to change it.
//
// Every other wear answers something the subject did not — a zero, a stale
// repeat, a wrong count. A claim about what a transformation *removes*
// survives all of them, because a zero has had everything removed and passes
// trivially. The escaper that escapes nothing is spelled only by answering
// the input.
type mixedSatPassthroughStore struct{ causal.Mixed }

func (m mixedSatPassthroughStore) Store(p0 context.Context, p1 causal.Value) (causal.Value, error) {
	if _, err := m.Mixed.Store(p0, p1); err != nil {
		var zero causal.Value
		return zero, err
	}
	return p1, nil
}

// mixedSatFlapStore alternates the fixture pair where
// Store should answer the store.
type mixedSatFlapStore struct {
	causal.Mixed
	flip atomic.Int64
	a, b causal.Value
}

func (m *mixedSatFlapStore) Store(_ context.Context, _ causal.Value) (causal.Value, error) {
	if m.flip.Add(1)%2 == 0 {
		return m.a, nil
	}
	return m.b, nil
}

// MixedModelValues replaces the values pool — for a subject whose
// accepted values a raw draw cannot spell. The pool feeds every value slot,
// the sequences and the laws alike; keep its draws colliding, because values
// that never revisit a key pass every comparison over a history that holds
// nothing twice.
func MixedModelValues(values *model.Generator[causal.Value]) MixedModelOption {
	return func(c *mixedModelConfig) { c.values = values }
}

// mixedModelOnlyLaw narrows the run to one law.
//
// Unexported: this is the saturation prover's instrument, not a knob. A
// conformance run asserts every law the classifications earned, and dropping
// all but one is only ever right when the question is "can this law fail",
// which is the one question the prover asks.
//
// Without it the prover cannot answer that question at all. The runner stops
// the iteration at the first law that fails, so a defect worn for law A is
// reported under whichever law happens to catch it first — the corpus showed
// 114 such runs, each one a law that looked unsaturatable because a sibling
// spoke over it.
func mixedModelOnlyLaw(id string) MixedModelOption {
	return func(c *mixedModelConfig) { c.onlyLaw = id }
}

type mixedModelConfig struct {
	reference     func() causal.Mixed
	onlyLaw       string
	happensBefore func(a, b law.ClientOp[string]) bool
	values        *model.Generator[causal.Value]
}

func newMixedModelConfig(opts ...MixedModelOption) *mixedModelConfig {
	c := &mixedModelConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// testkit: end of generated content.
// testkit:provenance ca8f25a537bd2c2c1f07f8899aa8c7bb700fa5e6316978757bc66d308e87d09b
