// Code generated by testkit suite. DO NOT EDIT.
// Source: cache.go:17 (testkit suite -o nestedmaptest/cache_spec.gen_test.go MapCache)

// Package nestedmaptest_test verifies that any implementation of
// [nestedmap.MapCache] honors the contract declared by the
// source interface. Generated by `testkit suite`.
//
// # Usage
//
//	func TestMapCacheContract(t *testing.T) {
//	    AssertMapCacheContract(t, func() nestedmap.MapCache {
//	        return newInMemory()
//	    })
//	}
//
// # Multi-impl conformance
//
// Run the same contract once per implementation with
// `t.Run(name, ...)` per impl:
//
//	func TestMapCacheContractAcrossImpls(t *testing.T) {
//	    AssertMapCacheContractAcrossImpls(t, []MapCacheNamedFactory{
//	        {Name: "InMemory", Factory: newInMemory},
//	        {Name: "Postgres", Factory: newPostgres},
//	    })
//	}
//
// New impls drop into the slice — no per-impl test function to
// hand-wire. The driver emits identical per-method, per-shape, and
// per-directive subtests across every factory. Variadic `suite.Option`
// arguments apply to every factory's contract run.
//
// # Contract coverage
//
// Every non-skipped method gets a smoke subtest that constructs the
// impl, invokes the method with safe arguments (zero-values when
// the method's parameters allow, sample-driven when
// `//testkit:sample` is declared), and fails the test loudly on
// panic. Methods marked `//testkit:integration-only` are skipped —
// the consumer's integration test owns those contracts.
//
// Per-shape baseline assertions (Reader, Writer, Stream, …) and
// per-directive subtests (errors, deprecated, retryable, partition,
// order-after, wrapped-via, …) layer on top of smoke; see the
// [MapCache contract docs](.) for the full per-shape menu.
package nestedmaptest_test

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/generator/testdata/generics-nested/nestedmap"
	"go.thesmos.sh/testkit/suite"
)

// MapCacheFactory produces an implementation of [nestedmap.MapCache] for use
// by the contract driver. Each call must yield a fresh, independent
// instance — the contract subtests reset state between runs by
// asking the factory for a new impl.
type MapCacheFactory func() nestedmap.MapCache

// MapCacheNamedFactory pairs a human-readable name with a factory.
// The multi-impl driver runs the contract once per named factory
// with `t.Run(Name, ...)`; the name surfaces in test output.
type MapCacheNamedFactory struct {
	Name    string
	Factory MapCacheFactory
}

// AssertMapCacheContract runs the full MapCache contract against any
// implementation produced by `factory`. Each subtest constructs a
// fresh impl via the factory so per-test state isolation is the
// caller's responsibility — the factory should return an
// independently-state'd instance every call.
//
// Variadic `opts` carry impl-supplied inputs the contract needs but
// the generator can't synthesize: invalid factories for RejectInvalid
// baselines, prePopulate seeders, paired observers, aggregator
// bounds, stream samples, scope context, lease release, and more.
// See [suite.Option] and the `WithX` constructors for the full set.
func AssertMapCacheContract(t *testing.T, factory MapCacheFactory, opts ...suite.Option) {
	t.Helper()
	resolved := suite.ResolveOptions(opts...)
	_ = resolved
	// When the consumer supplies WithPrePopulate, wrap the factory once
	// so every fresh impl handed to a subtest gets seeded before any
	// contract assertion runs. The wrapper is identity when no
	// PrePopulate option is supplied — production-cost is a single
	// type assertion + nil check at driver entry.
	if seed, ok := resolved.PrePopulate.(func(nestedmap.MapCache)); ok {
		base := factory
		factory = func() nestedmap.MapCache {
			impl := base()
			seed(impl)
			return impl
		}
	}

	// Get — Reader-shape method.
	//
	// Shape semantics:
	//   func(ctx, K) (V, error) — keyed reader. Maps a key to a value or surfaces a sentinel error for unknown keys. Reads must be consistent (same input → same output) and free of observable side effects.
	//
	// Default contracts (always run for Reader):
	//   - smoke
	//       fail-fast bare invocation with the sample key
	//   - returns for key <sample>
	//       happy-path read against the configured sample
	//   - respects context
	//       ctx.Done() surfaces context.Canceled
	//   - consistent reads
	//       three sequential reads of the same key yield equal results
	//   - concurrent safe
	//       4 workers × 10 iterations under -race
	t.Run("Get", func(t *testing.T) {
		t.Parallel()
		sctx := suite.ReaderContextFor[nestedmap.MapCache, string, map[string]int](t, factory,
			func(ctx context.Context, impl nestedmap.MapCache, key string) (map[string]int, error) {
				return impl.Get(ctx, key)
			})
		suite.AssertReaderBaseline[nestedmap.MapCache, string, map[string]int](
			"test-key",
			map[string]int{"test-result0": 42},
		)(sctx)
	})

}

// AssertMapCacheContractAcrossImpls runs [AssertMapCacheContract] once per named factory under
// `t.Run(Name, ...)`. New impls drop in via slice append. The
// variadic `opts` apply to every factory's contract run.
func AssertMapCacheContractAcrossImpls(t *testing.T, factories []MapCacheNamedFactory, opts ...suite.Option) {
	t.Helper()
	for _, nf := range factories {
		t.Run(nf.Name, func(t *testing.T) {
			t.Parallel()
			AssertMapCacheContract(t, nf.Factory, opts...)
		})
	}
}
