// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/windowed/iface.go
// Plugins:   golang 1.0.0, suite 1.15.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package windowedtest_test

import (
	"context"
	"errors"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/windowed/windowedtest"
)

// Every generated check for Mixed, driven against a stand-in built
// to violate it.
//
//	Proved:   9 checks
//
// Each guard asserts the *reason* the check rejected, not merely that it did. A
// stand-in that failed for some unrelated reason — a nil map, a closed channel
// — would satisfy a guard reading only the fact, which is the vacuity this file
// exists to catch, one level up.

// TestAssertMixedRecordSmokeCanFail holds AssertMixedRecordSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertMixedRecordSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedRecord(func(context.Context, string) error {
			panic("Mixed.Record: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedRecordSmoke(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("Record panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedRecordCancelsCanFail holds AssertMixedRecordCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertMixedRecordCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedRecord(func(context.Context, string) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedRecordCancels(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("Record must report a cancelled context as context.Canceled",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedRecordHonoursDeadlineCanFail holds AssertMixedRecordHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertMixedRecordHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedRecord(func(context.Context, string) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedRecordHonoursDeadline(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("Record must report an expired deadline as context.DeadlineExceeded",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedRecordToleratesNilContextCanFail holds AssertMixedRecordToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertMixedRecordToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedRecord(func(context.Context, string) error {
			panic("Mixed.Record: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedRecordToleratesNilContext(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("Record panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedCountInSmokeCanFail holds AssertMixedCountInSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertMixedCountInSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedCountIn(func(context.Context, string) (int, error) {
			panic("Mixed.CountIn: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedCountInSmoke(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("CountIn panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedCountInCancelsCanFail holds AssertMixedCountInCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertMixedCountInCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedCountIn(func(context.Context, string) (int, error) {
			var r0 int
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedCountInCancels(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("CountIn must report a cancelled context as context.Canceled",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedCountInHonoursDeadlineCanFail holds AssertMixedCountInHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertMixedCountInHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedCountIn(func(context.Context, string) (int, error) {
			var r0 int
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedCountInHonoursDeadline(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("CountIn must report an expired deadline as context.DeadlineExceeded",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedCountInToleratesNilContextCanFail holds AssertMixedCountInToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertMixedCountInToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedCountIn(func(context.Context, string) (int, error) {
			panic("Mixed.CountIn: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedCountInToleratesNilContext(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("CountIn panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedCountInZeroOnErrorCanFail holds AssertMixedCountInZeroOnError to being able to fail.
//
// The stand-in refuses the call and answers a value that looks like a result
// anyway. A check that let that pass would leave a caller who checks the error
// and a caller who checks the value disagreeing about what happened — the
// claim's own violation, not a stand-in that merely succeeds.
func TestAssertMixedCountInZeroOnErrorCanFail(t *testing.T) {
	t.Parallel()

	fixture := windowedtest.DefaultMixedFixture()
	subject := windowedtest.NewMixedStub(t,
		windowedtest.WithMixedCountIn(func(context.Context, string) (int, error) {
			return 42, errors.New("violate: refused with a believable value")
		}))

	got := testkit.Rejects(t, "a method answering a believable value beside its error",
		func(tb testing.TB) {
			tb.Helper()
			windowedtest.AssertMixedCountInZeroOnError(tb, subject, fixture.KeyOther)
		})
	testkit.Assert(t, got).Contains("CountIn must return the zero value alongside an error",
		"and rejects it for the reason the check is about")
}

// testkit: end of generated content.
// testkit:provenance 2d5a61c0f08884e72c6b9778f460266216f5930df6a2fd2df6beb19ff178808a
