// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/lease/iface.go
// Plugins:   golang 1.0.0, suite 1.9.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package leasetest

import (
	"context"
	"slices"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/lease"
)

// ContractAcquireCheck is one assertion about Acquire.
//
// Every generated check for Acquire is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type ContractAcquireCheck func(tb testing.TB, subject lease.Contract, key string)

// ContractReleaseCheck is one assertion about Release.
//
// Every generated check for Release is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type ContractReleaseCheck func(tb testing.TB, subject lease.Contract, key string)

// ContractFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through ContractWithFixture
// and the check a consumer writes has something to use.
type ContractFixture struct {
	Key      string
	KeyOther string
}

// DefaultContractFixture is what this run derived. Replace any field through
// ContractWithFixture; the rest keep these values.
func DefaultContractFixture() ContractFixture {
	return ContractFixture{
		Key:      "test-key",
		KeyOther: "other-key",
	}
}

// AssertContractContract runs every generated check against every declared subject.
//
//	Checks:   8 across 2 methods, per subject
//	Subjects: declare each with ContractSubject
//	Double:   every subject runs a second time wrapped in ContractStub, so
//	          anything the wrapper fails that the subject passes is the double
//	          lying. ContractWithoutDouble declines it.
//	Extend:   ContractOnAcquire, ContractOnRelease
//	Drop:     ContractWithout, by the path each check reports under
//
// # What is checked somewhere else
//
// These need a reference implementation to compare against, which a suite run
// has no way to build. Nothing here asserts them and nothing here should:
//
//   - writer, on Acquire, Release
//   - lease, on Acquire, Release
//
// //testkit:model on the interface derives that reference, and the
// ContractModel option it generates runs them here. Its own file
// names the path it reports under and the ContractWithout call that
// declines it — this header said "model" for every fixture, and a twinned
// reference registers under "model/twin", so it was wrong wherever the
// oracle could not be derived.
func AssertContractContract(t *testing.T, opts ...ContractOption) {
	t.Helper()
	cfg := newContractConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertContractContract was given no subject; declare one with " +
			"ContractSubject(name, factory)")
	}
	for _, p := range cfg.phantoms() {
		t.Errorf("ContractWithout(%q) declines nothing: no check here reports "+
			"under that path, so this suite asserts one thing more than its "+
			"author believes", p)
	}
	for _, s := range cfg.subjects {
		runContractChecks(t, cfg, s.name, s.factory, nil)
		if !cfg.withoutDouble {
			runContractChecks(t, cfg, s.name+" through the double", s.factory,
				func(tb testing.TB, subject lease.Contract) lease.Contract {
					return NewContractStub(tb, ContractStubDelegateTo(subject))
				})
		}
	}
}

// runContractChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runContractChecks(
	t *testing.T,
	cfg *contractConfig,
	label string,
	factory func() lease.Contract,
	wrap func(tb testing.TB, subject lease.Contract) lease.Contract,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run("Acquire", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Acquire/smoke", "smoke", func(tb testing.TB) {
				AssertContractAcquireSmoke(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Acquire/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertContractAcquireCancels(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Acquire/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertContractAcquireHonoursDeadline(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Acquire/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertContractAcquireToleratesNilContext(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			for _, c := range cfg.onAcquire {
				cfg.run(t, "Acquire"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
				})
			}
		})

		t.Run("Release", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Release/smoke", "smoke", func(tb testing.TB) {
				AssertContractReleaseSmoke(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Release/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertContractReleaseCancels(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Release/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertContractReleaseHonoursDeadline(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Release/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertContractReleaseToleratesNilContext(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			for _, c := range cfg.onRelease {
				cfg.run(t, "Release"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
				})
			}
		})

		// The extra bodies of checks this run was given, each reporting under its
		// own name and dropped by it.
		//
		// The plain subject only. The wrapped pass exists to prove the double
		// faithful and the per-method checks above already do that, so running one
		// through the wrapper prices the wrapper and says nothing new about the
		// subject.
		if wrap == nil {
			for _, e := range cfg.extensions {
				if cfg.declined(e.name) {
					t.Run(e.name, func(t *testing.T) {
						t.Skipf("dropped through ContractWithout(%q)", e.name)
					})
					continue
				}
				t.Run(e.name, func(t *testing.T) {
					t.Parallel()
					e.run(t, label, factory, cfg)
				})
			}
		}
	})
}

// AssertContractAcquireSmoke asserts Acquire survives a call with derived inputs.
//
// Fails when: Acquire panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertContractAcquireSmoke(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Acquire panicked on a derived value (%v); supply one it "+
				"accepts through ContractWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_ = subject.Acquire(ctx, key)
}

// AssertContractAcquireCancels asserts Acquire reports a cancelled context as cancelled.
//
// Fails when: Acquire returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertContractAcquireCancels(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	err := subject.Acquire(ctx, key)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Acquire must report a cancelled context as context.Canceled")
}

// AssertContractAcquireHonoursDeadline asserts Acquire reports an expired deadline as exceeded.
//
// Fails when: Acquire returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertContractAcquireHonoursDeadline(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	err := subject.Acquire(ctx, key)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Acquire must report an expired deadline as context.DeadlineExceeded")
}

// AssertContractAcquireToleratesNilContext asserts Acquire does not panic on a nil context.
//
// Fails when: Acquire panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertContractAcquireToleratesNilContext(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Acquire panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_ = subject.Acquire(ctx, key)
}

// AssertContractReleaseSmoke asserts Release survives a call with derived inputs.
//
// Fails when: Release panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertContractReleaseSmoke(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Release panicked on a derived value (%v); supply one it "+
				"accepts through ContractWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_ = subject.Release(ctx, key)
}

// AssertContractReleaseCancels asserts Release reports a cancelled context as cancelled.
//
// Fails when: Release returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertContractReleaseCancels(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	err := subject.Release(ctx, key)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Release must report a cancelled context as context.Canceled")
}

// AssertContractReleaseHonoursDeadline asserts Release reports an expired deadline as exceeded.
//
// Fails when: Release returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertContractReleaseHonoursDeadline(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	err := subject.Release(ctx, key)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Release must report an expired deadline as context.DeadlineExceeded")
}

// AssertContractReleaseToleratesNilContext asserts Release does not panic on a nil context.
//
// Fails when: Release panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertContractReleaseToleratesNilContext(tb testing.TB, subject lease.Contract, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Release panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_ = subject.Release(ctx, key)
}

// ContractOption configures a contract run.
type ContractOption func(*contractConfig)

// ContractSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func ContractSubject(name string, factory func() lease.Contract) ContractOption {
	return func(c *contractConfig) {
		c.subjects = append(c.subjects, namedContractSubject{name, factory})
	}
}

// ContractWithoutDouble declines the second run through ContractStub.
//
// The double run proves the stand-in is faithful, and costs a second pass over
// every check. Decline it where the double is not used.
func ContractWithoutDouble() ContractOption {
	return func(c *contractConfig) { c.withoutDouble = true }
}

// ContractWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func ContractWithClock(c clock.Clock) ContractOption {
	return func(cfg *contractConfig) { cfg.clock = c }
}

// ContractWithFixture replaces the derived inputs.
func ContractWithFixture(f ContractFixture) ContractOption {
	return func(c *contractConfig) { c.Fixture = f }
}

// ContractSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func ContractSeed(fn func(ctx context.Context, subject lease.Contract) error) ContractOption {
	return func(c *contractConfig) {
		c.seed = fn
		c.seedIsDerived = false
	}
}

// ContractOnAcquire adds a named check to Acquire.
func ContractOnAcquire(name string, fn ContractAcquireCheck) ContractOption {
	return func(c *contractConfig) {
		c.onAcquire = append(c.onAcquire, namedContractAcquireCheck{name, fn})
	}
}

// ContractOnRelease adds a named check to Release.
func ContractOnRelease(name string, fn ContractReleaseCheck) ContractOption {
	return func(c *contractConfig) {
		c.onRelease = append(c.onRelease, namedContractReleaseCheck{name, fn})
	}
}

// ContractWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func ContractWithout(paths ...string) ContractOption {
	return func(c *contractConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedContractAcquireCheck struct {
	name string
	fn   ContractAcquireCheck
}

type namedContractReleaseCheck struct {
	name string
	fn   ContractReleaseCheck
}

type namedContractSubject struct {
	name    string
	factory func() lease.Contract
}

// contractContractExtension is a body of checks a generated sibling adds through an option.
//
// A sibling declares the option and closes over whatever configures it, so
// everything that varies per run is typed and private to the file that owns it
// — this file understands only the name and the call. Nothing arrives except
// through an option, which is what keeps the set fixed before the first subtest
// starts.
type contractContractExtension struct {
	// name is the path this reports under, and the one ContractWithout drops
	// it by. Anything nested beneath it is the extension's own to name.
	name string

	// run takes the factory rather than a subject. One that drives sequences
	// builds a subject per iteration, and one that compares against a reference
	// needs the unseeded subject a factory returns — which
	// contractConfig.subject is not.
	//
	// Called once per subject, in parallel, sharing the config. Anything it
	// mutates has to be built inside the call: state captured when the option
	// was declared is state two subjects write at once.
	run func(
		t *testing.T,
		subject string,
		factory func() lease.Contract,
		cfg *contractConfig,
	)
}

type contractConfig struct {
	Fixture       ContractFixture
	subjects      []namedContractSubject
	withoutDouble bool
	clock         clock.Clock
	seed          func(ctx context.Context, subject lease.Contract) error
	// seedIsDerived is what lets a failed seed name the right culprit. The
	// derived seed and a consumer's are the same field, and the advice for one
	// is useless for the other.
	seedIsDerived bool
	without       map[string]struct{}
	extensions    []contractContractExtension
	onAcquire     []namedContractAcquireCheck
	onRelease     []namedContractReleaseCheck
}

func newContractConfig(opts ...ContractOption) *contractConfig {
	c := &contractConfig{
		Fixture: DefaultContractFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	// Derived: Acquire is classified writer, so the interface
	// populates itself and a reader has something to read.
	c.seed = func(ctx context.Context, subject lease.Contract) error {
		return subject.Acquire(ctx, c.Fixture.Key)
	}
	c.seedIsDerived = true
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *contractConfig) subject(
	tb testing.TB,
	factory func() lease.Contract,
	wrap func(tb testing.TB, subject lease.Contract) lease.Contract,
) lease.Contract {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			if c.seedIsDerived {
				tb.Fatalf("seeding through Acquire failed: %v; "+
					"supply a value it accepts through ContractWithFixture, or a "+
					"whole seed through ContractSeed", err)
			} else {
				tb.Fatalf("the seed supplied through ContractSeed failed: %v", err)
			}
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// dropped reports whether a path was declined through ContractWithout.
//
// Named rather than inlined because the drop set is read from two places: here,
// and by whatever registered through the seam — which reports under paths this
// file has never heard of and must answer the same question about them.
func (c *contractConfig) declined(path string) bool {
	_, ok := c.without[path]
	return ok
}

// contractPaths is every path this file reports a check under.
//
// The set a ContractWithout argument has to be a member of. Declared
// rather than observed: a check that did not run is not a check that does not
// exist — an integration-only method skips without ever consulting the drop
// set, and reading that as a phantom would fail a correct suite on a machine
// with the environment unset.
//
//nolint:gochecknoglobals // the emitted check paths, read-only after init.
var contractPaths = map[string]struct{}{
	"Acquire/smoke":                       {},
	"Acquire/reports a cancelled context": {},
	"Acquire/reports an expired deadline": {},
	"Acquire/tolerates a nil context":     {},
	"Release/smoke":                       {},
	"Release/reports a cancelled context": {},
	"Release/reports an expired deadline": {},
	"Release/tolerates a nil context":     {},
}

// phantoms names every ContractWithout path that declines nothing.
//
// A drop that drops nothing is this option's silent half: the consumer wrote
// it against a check since renamed, or never emitted for that method at all,
// and every run after reads green while asserting one thing more than its
// author believes. Extensions carry their own names — the seam reports under
// paths this file has never heard of — so they count as known too.
func (c *contractConfig) phantoms() []string {
	known := func(p string) bool {
		if _, ok := contractPaths[p]; ok {
			return true
		}
		for _, e := range c.extensions {
			if e.name == p {
				return true
			}
		}
		for _, on := range c.onAcquire {
			if "Acquire"+"/"+on.name == p {
				return true
			}
		}
		for _, on := range c.onRelease {
			if "Release"+"/"+on.name == p {
				return true
			}
		}
		return false
	}
	var out []string
	for p := range c.without {
		if !known(p) {
			out = append(out, p)
		}
	}
	slices.Sort(out)
	return out
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *contractConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if c.declined(path) {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through ContractWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance 5c6f6f03609bfd910007d9cf0a7ea0e5aef4eb92ff21b1c0dabc3bd57fe743b8
