// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/lease/iface.go
// Plugins:   golang 1.0.0, model 0.38.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package leasetest

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync/atomic"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/lease"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
	"go.thesmos.sh/testkit/engine/model/linearize"
	"go.thesmos.sh/testkit/engine/model/ref"
)

// ContractModel runs random sequences of Contract's methods against every
// subject and a known-good in-memory reference side by side, comparing after
// every call. Pass it to AssertContractContract; it reports under
// "model", and ContractWithout("model") declines it.
//
//	Reference: derived — the LeaseTracker oracle, which is the
//	           lease contract's own semantics; ContractModelReference replaces it
//	Sequences: Acquire (writer), Release (writer)
//	Concurrent: Acquire and Release interleave across four workers,
//	           Porcupine-checked against the lease-table model per key
//	Laws:      AUTO-LEASE-DOUBLE-ACQUIRE-BLOCKS, AUTO-LEASE-RELEASED-ON-CANCEL (supplied: free)
//	Not bound:
//	           AUTO-WRITE-OBSERVABLE — Read names the reader family, and the interface has no keyed reader
func ContractModel(opts ...ContractModelOption) ContractOption {
	return func(c *contractConfig) {
		c.extensions = append(c.extensions, contractContractExtension{
			name: "model",
			run: func(t *testing.T, _ string, factory func() lease.Contract, _ *contractConfig) {
				model.Check(t, ContractModelProperty(factory, opts...))
			},
		})
		c.extensions = append(c.extensions, contractContractExtension{
			name: "model/concurrent",
			run: func(t *testing.T, _ string, factory func() lease.Contract, _ *contractConfig) {
				ContractModelConcurrent(t, factory, opts...)
			},
		})
	}
}

// ContractModelProperty builds the property the option runs — exported because a
// bespoke harness composes from here: model.Check for a test, model.MakeFuzz
// for a coverage-guided fuzz target, both over this one derivation.
func ContractModelProperty(factory func() lease.Contract, opts ...ContractModelOption) func(*model.T) {
	cfg := newContractModelConfig(opts...)
	fx := DefaultContractFixture()
	// Two keys, drawn for every key slot: collision density is what makes a
	// read revisit a write and an overwrite land on held state. A wide key
	// pool would pass every comparison over a history that never collides.
	keys := model.SampledFrom([]string{fx.Key, fx.KeyOther})
	reference := cfg.reference
	if reference == nil {
		reference = NewContractModelReference
	}
	// The laws the classifications earned, each reporting under its AUTO-
	// identifier when it fails. Observational: a law never mutates, so running
	// them inside the sequences is safe for every step that follows.
	laws := model.NewRegistry[lease.Contract]()
	laws.Add(law.LeaseDoubleAcquireBlocks[lease.Contract, string]{
		Acquire: func(rt *model.T, s lease.Contract, k string) error {
			return s.Acquire(rt.Context(), k)
		},
		Release: func(rt *model.T, s lease.Contract, k string) error {
			return s.Release(rt.Context(), k)
		},
		Keys: keys,
		Held: lease.ErrHeld,
	})
	if cfg.free != nil {
		laws.Add(law.LeaseReleasedOnCancel[lease.Contract, string]{
			Acquire: func(ctx context.Context, s lease.Contract, k string) error {
				return s.Acquire(ctx, k)
			},
			Free:    cfg.free,
			Keys:    keys,
			Timeout: 100000000,
		})
	}
	// The saturation prover's isolation: with siblings registered, the first
	// law to catch a defect ends the iteration and every other law bound on
	// the same methods reads as unsaturatable.
	if cfg.onlyLaw != "" {
		for _, l := range laws.Laws() {
			if l.ID() != cfg.onlyLaw {
				laws.SkipByID(l.ID())
			}
		}
	}
	return model.Property(factory,
		model.WithReference(reference),
		model.WithLaws(laws),
		// Isolating one law is the prover asking whether that law can fail,
		// and the differential answers first for almost any defect — the
		// worn subject disagrees with the clean reference at step 0 and the
		// iteration ends before a law is consulted. Silencing it is what
		// leaves the law as the only witness. A conformance run isolates
		// nothing, so this is false there and the differential stays armed.
		model.WithLawsOnly[lease.Contract](cfg.onlyLaw != ""),
		model.WithActions(
			action.Writer("Acquire", keys,
				func(ctx context.Context, s lease.Contract, v string) error {
					return s.Acquire(ctx, v)
				}),
			action.Writer("Release", keys,
				func(ctx context.Context, s lease.Contract, v string) error {
					return s.Release(ctx, v)
				}),
		),
	)
}

// ContractModelFuzz hands a subject's sequence space to the
// coverage-guided engine: the fuzzer's bytes replay as rapid's choice
// stream, so mutating them mutates the action ordering and every drawn
// input at once — and the engine's coverage feedback climbs the subject's
// own branches, which is what no fixed seed can do. Wire it from a fuzz
// target beside the subject:
//
//	func FuzzContract(f *testing.F) {
//		ContractModelFuzz(f, func() Contract { return NewMine() })
//	}
func ContractModelFuzz(f *testing.F, factory func() lease.Contract, opts ...ContractModelOption) {
	f.Add([]byte{})
	f.Fuzz(model.MakeFuzz(ContractModelProperty(factory, opts...)))
}

// ContractModelConcurrent runs the linearizability leg: four workers
// interleave Acquire and Release over the shared keys, and
// Porcupine checks the recorded history against the lease-table model, one
// key at a time. No reference runs here — linearizability is the oracle —
// and the laws stay with the sequential leg, whose step boundary they need.
// Exported for the same bespoke harnesses the property serves.
func ContractModelConcurrent(t *testing.T, factory func() lease.Contract, opts ...ContractModelOption) {
	fx := DefaultContractFixture()
	// Two keys, drawn for every key slot: collision density is what makes a
	// read revisit a write and an overwrite land on held state. A wide key
	// pool would pass every comparison over a history that never collides.
	keys := model.SampledFrom([]string{fx.Key, fx.KeyOther})
	model.Assert(t, factory,
		model.WithConcurrent(model.ConcurrentConfig[lease.Contract]{
			// The lease-table model speaks the acquire/release vocabulary at
			// the oracle's own held identity; the nil free arm is the lenient
			// release both the oracle and the corpus subject speak. The op
			// spellings are the model's canonical vocabulary — it switches on
			// them, and an alias checks nothing.
			Model: linearize.LeaseTable(lease.ErrHeld, nil),
			Actions: []model.ConcurrentAction[lease.Contract]{
				linearize.ConcurrentWriter(linearize.OpAcquire, keys,
					func(ctx context.Context, s lease.Contract, k string) error {
						return s.Acquire(ctx, k)
					}, func(k string) string { return k }),
				linearize.ConcurrentWriter(linearize.OpRelease, keys,
					func(ctx context.Context, s lease.Contract, k string) error {
						return s.Release(ctx, k)
					}, func(k string) string { return k }),
			},
		}),
	)
}

// contractModelReference adapts the shipped LeaseTracker oracle — the
// lease contract's own semantics — to Contract.
// Deliberately simple: its correctness is read, not tested.
type contractModelReference struct {
	store *ref.LeaseTracker[string]
}

func NewContractModelReference() lease.Contract {
	return &contractModelReference{store: ref.NewLeaseTracker[string](
		lease.ErrHeld,
		nil,
	)}
}

func (r *contractModelReference) Acquire(ctx context.Context, key string) error {
	return r.store.Acquire(ctx, key)
}

func (r *contractModelReference) Release(ctx context.Context, key string) error {
	return r.store.Release(ctx, key)
}

// ContractModelOption configures the model run.
type ContractModelOption func(*contractModelConfig)

// ContractModelReference replaces the derived reference — for an
// interface whose semantics outrun its shape.
func ContractModelReference(factory func() lease.Contract) ContractModelOption {
	return func(c *contractModelConfig) { c.reference = factory }
}

// ContractModelFree supplies the free closure — a domain fact
// no derivation can invent. Every law reading it arms only under this
// option; unarmed, the header still names the door.
func ContractModelFree(fn func(*model.T, lease.Contract, string) bool) ContractModelOption {
	return func(c *contractModelConfig) { c.free = fn }
}

// ContractSatWear is one wearable defect: a kind, and the wrap that
// dresses a subject in it.
type contractSatWear struct {
	kind string
	wrap func(fx ContractFixture, s lease.Contract) lease.Contract
}

//nolint:gochecknoglobals // the prover's wardrobe, read-only after init.
var contractSatWears = map[string][]contractSatWear{}

//nolint:gochecknoinits // the wardrobe fills once, keyed by method.
func init() { //nolint:staticcheck // an empty wardrobe leaves dress unused by design.
	dress := func(method, kind string, wrap func(fx ContractFixture, s lease.Contract) lease.Contract) {
		contractSatWears[method] = append(contractSatWears[method],
			contractSatWear{kind: kind, wrap: wrap})
	}
	dress("Acquire", "inert", func(_ ContractFixture, s lease.Contract) lease.Contract {
		return contractSatInertAcquire{s}
	})
	dress("Acquire", "flicker", func(_ ContractFixture, s lease.Contract) lease.Contract {
		return &contractSatFlickerAcquire{Contract: s}
	})
	dress("Acquire", "sputter", func(_ ContractFixture, s lease.Contract) lease.Contract {
		return &contractSatSputterAcquire{Contract: s}
	})
	dress("Release", "inert", func(_ ContractFixture, s lease.Contract) lease.Contract {
		return contractSatInertRelease{s}
	})
	dress("Release", "flicker", func(_ ContractFixture, s lease.Contract) lease.Contract {
		return &contractSatFlickerRelease{Contract: s}
	})
	dress("Release", "sputter", func(_ ContractFixture, s lease.Contract) lease.Contract {
		return &contractSatSputterRelease{Contract: s}
	})
}

// ContractModelSaturation proves the bound laws can fail: per law, a
// defect is worn on each method the law's closures reach — zeros, the
// fixture pair alternated, a waning count — and at least one worn run must
// fail naming the law's own identifier, with the clean factory standing as
// reference. A law every defect survives is bound but unsaturatable, and
// fails here by name. Pass the same options that arm the tier: a law behind
// an unarmed door or the clocked factory is skipped visibly, never counted.
func ContractModelSaturation(t *testing.T, factory func() lease.Contract, opts ...ContractModelOption) {
	t.Helper()
	cfg := newContractModelConfig(opts...)
	_ = cfg
	fx := DefaultContractFixture()
	_ = fx
	t.Run("AUTO-LEASE-DOUBLE-ACQUIRE-BLOCKS", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"Acquire", "Release"} {
				for _, wear := range contractSatWears[method] {
					// Two references per defect. Silencing the differential leaves
					// the law as the only witness, but not every action reports
					// through it: a shape whose action fails structurally still
					// ends the iteration, and a reference wearing the same defect
					// behaves the same way the subject does, so nothing diverges
					// and the law is reached. A law that *is* the comparison needs
					// the opposite — with both sides worn it has nothing to
					// disagree with — so the clean reference runs too and either
					// kill counts. The corpus measured both: dropping either one
					// loses laws that only the other can saturate.
					for _, blind := range []bool{true, false} {
						surrogate := "ContractSat_AUTO-LEASE-DOUBLE-ACQUIRE-BLOCKS_" + method + "_" + wear.kind
						if blind {
							surrogate += "_blind"
						}
						t.Cleanup(func() {
							_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
							_ = os.Remove(filepath.Join(
								model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
						})
						reference := factory
						if blind {
							reference = func() lease.Contract { return wear.wrap(fx, factory()) }
						}
						f := testkit.NewFailableTB().WithName(surrogate)
						worn := append(slices.Clone(opts),
							ContractModelReference(reference),
							contractModelOnlyLaw("AUTO-LEASE-DOUBLE-ACQUIRE-BLOCKS"))
						model.Check(f, ContractModelProperty(func() lease.Contract {
							return wear.wrap(fx, factory())
						}, worn...))
						// The reporter's own rendering, not the bare identifier.
						// rapid echoes the TB's name into its final message and the
						// surrogate above is named for this law, so matching the
						// identifier alone matched the name — the criterion reduced
						// to f.Failed() and every defect "killed" every law. The
						// verdict's format carries the identifier where no name can:
						// after the kind, which is the one place only the reporter
						// writes. The suffix rather than the whole prefix because a
						// REQ-tagged law renders "[REQ-1 invariant]".
						if f.Failed() && (strings.Contains(f.Msg(), "invariant] AUTO-LEASE-DOUBLE-ACQUIRE-BLOCKS")) {
							return true
						}
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-LEASE-DOUBLE-ACQUIRE-BLOCKS survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
	t.Run("AUTO-LEASE-RELEASED-ON-CANCEL", func(t *testing.T) {
		if cfg.free == nil {
			t.Skip("the free door is not armed here, and the law registers only armed")
		}
		killed := func() bool {
			for _, method := range []string{"Acquire"} {
				for _, wear := range contractSatWears[method] {
					// Two references per defect. Silencing the differential leaves
					// the law as the only witness, but not every action reports
					// through it: a shape whose action fails structurally still
					// ends the iteration, and a reference wearing the same defect
					// behaves the same way the subject does, so nothing diverges
					// and the law is reached. A law that *is* the comparison needs
					// the opposite — with both sides worn it has nothing to
					// disagree with — so the clean reference runs too and either
					// kill counts. The corpus measured both: dropping either one
					// loses laws that only the other can saturate.
					for _, blind := range []bool{true, false} {
						surrogate := "ContractSat_AUTO-LEASE-RELEASED-ON-CANCEL_" + method + "_" + wear.kind
						if blind {
							surrogate += "_blind"
						}
						t.Cleanup(func() {
							_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
							_ = os.Remove(filepath.Join(
								model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
						})
						reference := factory
						if blind {
							reference = func() lease.Contract { return wear.wrap(fx, factory()) }
						}
						f := testkit.NewFailableTB().WithName(surrogate)
						worn := append(slices.Clone(opts),
							ContractModelReference(reference),
							contractModelOnlyLaw("AUTO-LEASE-RELEASED-ON-CANCEL"))
						model.Check(f, ContractModelProperty(func() lease.Contract {
							return wear.wrap(fx, factory())
						}, worn...))
						// The reporter's own rendering, not the bare identifier.
						// rapid echoes the TB's name into its final message and the
						// surrogate above is named for this law, so matching the
						// identifier alone matched the name — the criterion reduced
						// to f.Failed() and every defect "killed" every law. The
						// verdict's format carries the identifier where no name can:
						// after the kind, which is the one place only the reporter
						// writes. The suffix rather than the whole prefix because a
						// REQ-tagged law renders "[REQ-1 invariant]".
						if f.Failed() && (strings.Contains(f.Msg(), "invariant] AUTO-LEASE-RELEASED-ON-CANCEL")) {
							return true
						}
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-LEASE-RELEASED-ON-CANCEL survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
}

// contractSatInertAcquire answers zeros where Acquire should act.
type contractSatInertAcquire struct{ lease.Contract }

func (contractSatInertAcquire) Acquire(_ context.Context, _ string) (z0 error) {
	return
}

// contractSatFlickerAcquire answers zeros every second
// call, where Acquire should answer the same thing twice.
//
// The defect every stability claim names: cacheable, deterministic,
// consistent, non-decreasing are all about two calls agreeing, and a subject
// that answers zeros *forever* agrees with itself perfectly. Only an answer
// that changes breaks them, and alternating with the zero is the smallest
// change available at any return type.
type contractSatFlickerAcquire struct {
	lease.Contract
	flip atomic.Int64
}

func (m *contractSatFlickerAcquire) Acquire(p0 context.Context, p1 string) (z0 error) {
	if m.flip.Add(1)%2 == 0 {
		return
	}
	return m.Contract.Acquire(p0, p1)
}

// contractSatSputterAcquire alternates a minted refusal
// with the real answer where Acquire should be steady.
type contractSatSputterAcquire struct {
	lease.Contract
	flip atomic.Int64
}

func (m *contractSatSputterAcquire) Acquire(p0 context.Context, p1 string) (z0 error) {
	if m.flip.Add(1)%2 == 1 {
		z0 = errors.New("leasetest: saturation sputtered a refusal")
		return
	}
	return m.Contract.Acquire(p0, p1)
}

// contractSatInertRelease answers zeros where Release should act.
type contractSatInertRelease struct{ lease.Contract }

func (contractSatInertRelease) Release(_ context.Context, _ string) (z0 error) {
	return
}

// contractSatFlickerRelease answers zeros every second
// call, where Release should answer the same thing twice.
//
// The defect every stability claim names: cacheable, deterministic,
// consistent, non-decreasing are all about two calls agreeing, and a subject
// that answers zeros *forever* agrees with itself perfectly. Only an answer
// that changes breaks them, and alternating with the zero is the smallest
// change available at any return type.
type contractSatFlickerRelease struct {
	lease.Contract
	flip atomic.Int64
}

func (m *contractSatFlickerRelease) Release(p0 context.Context, p1 string) (z0 error) {
	if m.flip.Add(1)%2 == 0 {
		return
	}
	return m.Contract.Release(p0, p1)
}

// contractSatSputterRelease alternates a minted refusal
// with the real answer where Release should be steady.
type contractSatSputterRelease struct {
	lease.Contract
	flip atomic.Int64
}

func (m *contractSatSputterRelease) Release(p0 context.Context, p1 string) (z0 error) {
	if m.flip.Add(1)%2 == 1 {
		z0 = errors.New("leasetest: saturation sputtered a refusal")
		return
	}
	return m.Contract.Release(p0, p1)
}

// contractModelOnlyLaw narrows the run to one law.
//
// Unexported: this is the saturation prover's instrument, not a knob. A
// conformance run asserts every law the classifications earned, and dropping
// all but one is only ever right when the question is "can this law fail",
// which is the one question the prover asks.
//
// Without it the prover cannot answer that question at all. The runner stops
// the iteration at the first law that fails, so a defect worn for law A is
// reported under whichever law happens to catch it first — the corpus showed
// 114 such runs, each one a law that looked unsaturatable because a sibling
// spoke over it.
func contractModelOnlyLaw(id string) ContractModelOption {
	return func(c *contractModelConfig) { c.onlyLaw = id }
}

type contractModelConfig struct {
	reference func() lease.Contract
	onlyLaw   string
	free      func(*model.T, lease.Contract, string) bool
}

func newContractModelConfig(opts ...ContractModelOption) *contractModelConfig {
	c := &contractModelConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// testkit: end of generated content.
// testkit:provenance 1da9c57805aaf53df53638f431a1e5fb2843d3ca687bfff64c11553c9b8957a5
