// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/lang/embeddedforeign/iface.go
// Plugins:   golang 1.0.0, suite 1.2.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package embeddedforeigntest

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/lang/embeddedforeign"
)

// StreamReadCheck is one assertion about Read.
//
// Every generated check for Read is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type StreamReadCheck func(tb testing.TB, subject embeddedforeign.Stream, key string)

// StreamCloseCheck is one assertion about Close.
//
// Every generated check for Close is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type StreamCloseCheck func(tb testing.TB, subject embeddedforeign.Stream)

// StreamFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through StreamWithFixture
// and the check a consumer writes has something to use.
type StreamFixture struct {
	Key      string
	KeyOther string
}

// DefaultStreamFixture is what this run derived. Replace any field through
// StreamWithFixture; the rest keep these values.
func DefaultStreamFixture() StreamFixture {
	return StreamFixture{
		Key:      "test-key",
		KeyOther: "other-key",
	}
}

// AssertStreamContract runs every generated check against every declared subject.
//
//	Checks:   6 across 2 methods, per subject
//	Subjects: declare each with StreamSubject
//	Double:   every subject runs a second time wrapped in StreamStub, so
//	          anything the wrapper fails that the subject passes is the double
//	          lying. StreamWithoutDouble declines it.
//	Extend:   StreamOnRead, StreamOnClose
//	Drop:     StreamWithout, by the path each check reports under
func AssertStreamContract(t *testing.T, opts ...StreamOption) {
	t.Helper()
	cfg := newStreamConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertStreamContract was given no subject; declare one with " +
			"StreamSubject(name, factory)")
	}
	for _, s := range cfg.subjects {
		runStreamChecks(t, cfg, s.name, s.factory, nil)
		if !cfg.withoutDouble {
			runStreamChecks(t, cfg, s.name+" through the double", s.factory,
				func(tb testing.TB, subject embeddedforeign.Stream) embeddedforeign.Stream {
					return NewStreamStub(tb, StreamStubDelegateTo(subject))
				})
		}
	}
}

// runStreamChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runStreamChecks(
	t *testing.T,
	cfg *streamConfig,
	label string,
	factory func() embeddedforeign.Stream,
	wrap func(tb testing.TB, subject embeddedforeign.Stream) embeddedforeign.Stream,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run("Read", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Read/smoke", "smoke", func(tb testing.TB) {
				AssertStreamReadSmoke(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Read/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertStreamReadCancels(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Read/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertStreamReadHonoursDeadline(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Read/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertStreamReadToleratesNilContext(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Read/an error carries the zero value", "an error carries the zero value", func(tb testing.TB) {
				AssertStreamReadZeroOnError(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.KeyOther)
			})
			for _, c := range cfg.onRead {
				cfg.run(t, "Read"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
				})
			}
		})

		t.Run("Close", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Close/smoke", "smoke", func(tb testing.TB) {
				AssertStreamCloseSmoke(tb, cfg.subject(tb, factory, wrap))
			})
			for _, c := range cfg.onClose {
				cfg.run(t, "Close"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap))
				})
			}
		})

		// The extra bodies of checks this run was given, each reporting under its
		// own name and dropped by it.
		//
		// The plain subject only. The wrapped pass exists to prove the double
		// faithful and the per-method checks above already do that, so running one
		// through the wrapper prices the wrapper and says nothing new about the
		// subject.
		if wrap == nil {
			for _, e := range cfg.extensions {
				if cfg.dropped(e.name) {
					t.Run(e.name, func(t *testing.T) {
						t.Skipf("dropped through StreamWithout(%q)", e.name)
					})
					continue
				}
				t.Run(e.name, func(t *testing.T) {
					t.Parallel()
					e.run(t, label, factory, cfg)
				})
			}
		}
	})
}

// AssertStreamReadSmoke asserts Read survives a call with derived inputs.
//
// Fails when: Read panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertStreamReadSmoke(tb testing.TB, subject embeddedforeign.Stream, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Read panicked on a derived value (%v); supply one it "+
				"accepts through StreamWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_, _ = subject.Read(ctx, key)
}

// AssertStreamReadCancels asserts Read reports a cancelled context as cancelled.
//
// Fails when: Read returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertStreamReadCancels(tb testing.TB, subject embeddedforeign.Stream, key string) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	_, err := subject.Read(ctx, key)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Read must report a cancelled context as context.Canceled")
}

// AssertStreamReadHonoursDeadline asserts Read reports an expired deadline as exceeded.
//
// Fails when: Read returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertStreamReadHonoursDeadline(tb testing.TB, subject embeddedforeign.Stream, key string) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	_, err := subject.Read(ctx, key)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Read must report an expired deadline as context.DeadlineExceeded")
}

// AssertStreamReadToleratesNilContext asserts Read does not panic on a nil context.
//
// Fails when: Read panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertStreamReadToleratesNilContext(tb testing.TB, subject embeddedforeign.Stream, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Read panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_, _ = subject.Read(ctx, key)
}

// AssertStreamReadZeroOnError asserts an error is accompanied by the zero value.
//
// Fails when: Read returns a non-zero result alongside a non-nil
// error. A caller who checks the error and a caller who checks the value must
// not disagree about whether the call succeeded.
//
// Skips when the alternate input succeeds: a total method has no failure this
// run can reach, and a skip says so where a green line would claim a
// comparison that never happened.
func AssertStreamReadZeroOnError(tb testing.TB, subject embeddedforeign.Stream, key string) {
	tb.Helper()
	ctx := tb.Context()
	r0, r1 := subject.Read(ctx, key)
	if r1 == nil {
		tb.Skipf("Read accepted the alternate input; nothing this run " +
			"supplies makes it fail, so the zero-on-error claim goes unexercised")
		return
	}
	{
		var zero string
		testkit.Equal(tb, r0, zero,
			"Read must return the zero value alongside an error")
	}
}

// AssertStreamCloseSmoke asserts Close survives a call with derived inputs.
//
// Fails when: Close panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertStreamCloseSmoke(tb testing.TB, subject embeddedforeign.Stream) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Close panicked on a derived value (%v); supply one it "+
				"accepts through StreamWithFixture", r)
		}
	}()
	_ = subject.Close()
}

// StreamOption configures a contract run.
type StreamOption func(*streamConfig)

// StreamSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func StreamSubject(name string, factory func() embeddedforeign.Stream) StreamOption {
	return func(c *streamConfig) {
		c.subjects = append(c.subjects, namedStreamSubject{name, factory})
	}
}

// StreamWithoutDouble declines the second run through StreamStub.
//
// The double run proves the stand-in is faithful, and costs a second pass over
// every check. Decline it where the double is not used.
func StreamWithoutDouble() StreamOption {
	return func(c *streamConfig) { c.withoutDouble = true }
}

// StreamWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func StreamWithClock(c clock.Clock) StreamOption {
	return func(cfg *streamConfig) { cfg.clock = c }
}

// StreamWithFixture replaces the derived inputs.
func StreamWithFixture(f StreamFixture) StreamOption {
	return func(c *streamConfig) { c.Fixture = f }
}

// StreamSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func StreamSeed(fn func(ctx context.Context, subject embeddedforeign.Stream) error) StreamOption {
	return func(c *streamConfig) {
		c.seed = fn
	}
}

// StreamOnRead adds a named check to Read.
func StreamOnRead(name string, fn StreamReadCheck) StreamOption {
	return func(c *streamConfig) {
		c.onRead = append(c.onRead, namedStreamReadCheck{name, fn})
	}
}

// StreamOnClose adds a named check to Close.
func StreamOnClose(name string, fn StreamCloseCheck) StreamOption {
	return func(c *streamConfig) {
		c.onClose = append(c.onClose, namedStreamCloseCheck{name, fn})
	}
}

// StreamWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func StreamWithout(paths ...string) StreamOption {
	return func(c *streamConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedStreamReadCheck struct {
	name string
	fn   StreamReadCheck
}

type namedStreamCloseCheck struct {
	name string
	fn   StreamCloseCheck
}

type namedStreamSubject struct {
	name    string
	factory func() embeddedforeign.Stream
}

// streamContractExtension is a body of checks a generated sibling adds through an option.
//
// A sibling declares the option and closes over whatever configures it, so
// everything that varies per run is typed and private to the file that owns it
// — this file understands only the name and the call. Nothing arrives except
// through an option, which is what keeps the set fixed before the first subtest
// starts.
type streamContractExtension struct {
	// name is the path this reports under, and the one StreamWithout drops
	// it by. Anything nested beneath it is the extension's own to name.
	name string

	// run takes the factory rather than a subject. One that drives sequences
	// builds a subject per iteration, and one that compares against a reference
	// needs the unseeded subject a factory returns — which
	// streamConfig.subject is not.
	//
	// Called once per subject, in parallel, sharing the config. Anything it
	// mutates has to be built inside the call: state captured when the option
	// was declared is state two subjects write at once.
	run func(
		t *testing.T,
		subject string,
		factory func() embeddedforeign.Stream,
		cfg *streamConfig,
	)
}

type streamConfig struct {
	Fixture       StreamFixture
	subjects      []namedStreamSubject
	withoutDouble bool
	clock         clock.Clock
	seed          func(ctx context.Context, subject embeddedforeign.Stream) error
	without       map[string]struct{}
	extensions    []streamContractExtension
	onRead        []namedStreamReadCheck
	onClose       []namedStreamCloseCheck
}

func newStreamConfig(opts ...StreamOption) *streamConfig {
	c := &streamConfig{
		Fixture: DefaultStreamFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *streamConfig) subject(
	tb testing.TB,
	factory func() embeddedforeign.Stream,
	wrap func(tb testing.TB, subject embeddedforeign.Stream) embeddedforeign.Stream,
) embeddedforeign.Stream {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			tb.Fatalf("the seed supplied through StreamSeed failed: %v", err)
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// dropped reports whether a path was declined through StreamWithout.
//
// Named rather than inlined because the drop set is read from two places: here,
// and by whatever registered through the seam — which reports under paths this
// file has never heard of and must answer the same question about them.
func (c *streamConfig) dropped(path string) bool {
	_, ok := c.without[path]
	return ok
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *streamConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if c.dropped(path) {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through StreamWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance 4f82fa0f6a9cbd9c8a1cff93adf27be72595b098e71d4b288364ce9fd7dd62ea
