// Code generated by testkit enum. DO NOT EDIT.
// Source: testkit enum -o multifile.gen_test.go Region

// This file verifies the package's enum-style integer types satisfy a
// battery of contracts:
//
//   - exhaustive:     every declared constant of the type is in the test set
//   - distinct:       no two constants share an integer value
//   - zero value:     the type's zero value matches the iota[0] declaration
//   - wire compat:    constant→int mapping matches a committed JSON golden
//     (regenerate explicitly with `go test -update` after
//     a deliberate reorder)
package enums_test

import (
	"encoding/json"
	"testing"

	"go.thesmos.sh/testkit/generator/testdata/enums"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/golden"
)

// TestRegionEnum verifies the *enums.Region
// enum's invariants — exhaustiveness, distinctness, zero-value
// alignment, wire compatibility against the committed golden, and
// (when the type implements them) stringer / parse / marshal
// round-trips.
func TestRegionEnum(t *testing.T) {
	t.Parallel()

	type enumEntry struct {
		value enums.Region
		name  string
	}

	all := []enumEntry{
		{
			value: enums.RegionUS,
			name:  "RegionUS",
		},
		{
			value: enums.RegionEU,
			name:  "RegionEU",
		},
		{
			value: enums.RegionAP,
			name:  "RegionAP",
		},
		{
			value: enums.RegionLA,
			name:  "RegionLA",
		},
	}

	// "exhaustive": the test set must include every declared
	// constant. Catches accidental drops during refactors.
	t.Run("exhaustive", func(t *testing.T) {
		t.Parallel()
		testkit.Len(t, all, 4,
			"must have exactly 4 values")
	})

	// "zero value is RegionUS": the type's zero value
	// (var x Region) must match iota[0]. Catches reorderings
	// that silently change which value uninitialized variables take.
	t.Run("zero value is RegionUS", func(t *testing.T) {
		t.Parallel()
		var zero enums.Region
		testkit.Equal(t, zero, enums.RegionUS,
			"zero value must equal first iota declaration")
	})

	// "all values are distinct": no two constants share an integer
	// value. Distinctness is required for errors.Is-style switches
	// and for wire compatibility.
	t.Run("all values are distinct", func(t *testing.T) {
		t.Parallel()
		seen := make(map[enums.Region]string)
		for _, tt := range all {
			prev, dup := seen[tt.value]
			testkit.False(t, dup,
				tt.name+" and "+prev+" have identical value")
			seen[tt.value] = tt.name
		}
	})

	// "wire compatibility": this type's slice of the consolidated
	// golden file at multifile.gen_wire.json must match the live
	// constant→int mapping. Reordering or renumbering any constant
	// fails this subtest until the golden is regenerated with
	// `go test -update`.
	//
	// Why this matters: enum integer values frequently end up
	// persisted to durable storage (databases, message queues, audit
	// logs). A silent reorder corrupts every existing record. CI runs
	// without `-update`, so accidental drift fails the build; a
	// deliberate change shows up in code review as a diff to the JSON
	// golden alongside the source change. The diff is scoped to this
	// type's slice — sibling types' values stay out of the way.
	t.Run("wire compatibility", func(t *testing.T) {
		t.Parallel()
		live, err := json.Marshal(map[string]int{
			"RegionUS": int(enums.RegionUS),
			"RegionEU": int(enums.RegionEU),
			"RegionAP": int(enums.RegionAP),
			"RegionLA": int(enums.RegionLA),
		})
		testkit.NoError(t, err, "marshal live mapping")
		golden.AssertGoldenJSONField(t,
			"multifile.gen_wire.json", "Region",
			live, golden.ShouldUpdate())
	})
}
