// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/composite/batched-mixins/iface.go
// Plugins:   golang 1.0.0, model 0.7.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package batchedmixinstest_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"go.thesmos.sh/testkit"
	batchedmixins "go.thesmos.sh/testkit/conformance/corpus/iface/composite/batched-mixins"
	"go.thesmos.sh/testkit/conformance/corpus/iface/composite/batched-mixins/batchedmixinstest"
	"go.thesmos.sh/testkit/engine/model"
)

// TestBatchedModelReference holds the reference to the tier it
// anchors: two independent instances driven through the full property, one as
// subject and one as oracle. A failure here is the derivation's own — before
// any consumer's implementation is in the room.
//
// The supplied-option path rides along, so the option, the config and the
// constructor are all exercised by the file that ships them.
func TestBatchedModelReference(t *testing.T) {
	t.Parallel()
	model.Check(t, batchedmixinstest.BatchedModelProperty(
		batchedmixinstest.NewBatchedModelReference,
		batchedmixinstest.BatchedModelReference(batchedmixinstest.NewBatchedModelReference),
	))
}

// FuzzBatchedModel hands the derivation's sequence space to the
// coverage-guided engine: the fuzzer's bytes replay as rapid's choice
// stream, hunting the action ordering that breaks a law. A plain `go test`
// runs the seed as smoke; `go test -fuzz=FuzzBatchedModel` digs.
// A consumer fuzzes their own subject the same way, through
// BatchedModelProperty and [model.MakeFuzz].
func FuzzBatchedModel(f *testing.F) {
	f.Add([]byte{})
	f.Fuzz(model.MakeFuzz(
		batchedmixinstest.BatchedModelProperty(batchedmixinstest.NewBatchedModelReference)))
}

// TestBatchedModelKillsInertMutants measures the tier's teeth: for
// every driven method, a mutant reference answers zeros there and forwards
// nothing, and the property must fail it. A mutant that survives means that
// method's participation in the run checks nothing — a hole in this
// derivation, not in any consumer's subject. The kill rate this asserts is
// total: 2 of 2.
func TestBatchedModelKillsInertMutants(t *testing.T) {
	t.Parallel()

	mutants := []struct {
		method string
		wrap   func(batchedmixins.Batched) batchedmixins.Batched
	}{
		{"Put", func(s batchedmixins.Batched) batchedmixins.Batched {
			return batchedModelMutantPut{s}
		}},
		{"Read", func(s batchedmixins.Batched) batchedmixins.Batched {
			return batchedModelMutantRead{s}
		}},
	}
	for _, m := range mutants {
		t.Run(m.method, func(t *testing.T) {
			t.Parallel()
			// The failure is the expectation, so the artifacts a real failure
			// earns — rapid's failfile, the runner's report — are residue
			// here, not regression seeds; the probe removes what it provoked.
			surrogate := "BatchedMutant" + m.method
			t.Cleanup(func() {
				_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
				_ = os.Remove(filepath.Join(
					model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
			})
			f := testkit.NewFailableTB().WithName(surrogate)
			model.Check(f, batchedmixinstest.BatchedModelProperty(func() batchedmixins.Batched {
				return m.wrap(batchedmixinstest.NewBatchedModelReference())
			}))
			testkit.True(t, f.Failed(),
				"an inert "+m.method+" must diverge from the clean reference")
		})
	}
}

// batchedModelMutantPut answers zeros where Put should act.
type batchedModelMutantPut struct{ batchedmixins.Batched }

func (batchedModelMutantPut) Put(_ context.Context, _ string, _ string) (r0 error) { return }

// batchedModelMutantRead answers zeros where Read should act.
type batchedModelMutantRead struct{ batchedmixins.Batched }

func (batchedModelMutantRead) Read(_ context.Context, _ string) (r0 string, r1 error) { return }

// TestBatchedModelReferenceInertBodies calls what the sequences
// never do. An inert body's whole contract is answering zero values whatever
// it is handed; a panic here would ambush the first consumer who reaches the
// reference through the interface.
func TestBatchedModelReferenceInertBodies(t *testing.T) {
	t.Parallel()
	r := batchedmixinstest.NewBatchedModelReference()
	_, _ = r.List(t.Context())
}

// testkit: end of generated content.
// testkit:provenance 1385c69df73a1677ef2569b613d1507ba09f2799c2cd29f736f9f59a15e07069
