// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/composite/batched-mixins/iface.go
// Plugins:   golang 1.0.0, model 0.26.2, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package batchedmixinstest

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync/atomic"
	"testing"

	"go.thesmos.sh/testkit"
	batchedmixins "go.thesmos.sh/testkit/conformance/corpus/iface/composite/batched-mixins"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
)

// BatchedModel runs random sequences of Batched's methods against every
// subject and a known-good in-memory reference side by side, comparing after
// every call. Pass it to AssertBatchedContract; it reports under
// "model/twin", and BatchedWithout("model/twin") declines it.
//
//	Reference: the subject's own factory — the bounded claim clamps what the reader answers, and a derived collection clamps nothing,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Put (compositewriter), Read (reader), List (collector)
//	Values:    the fixture pair blended with arbitrary draws; BatchedModelValues replaces the pool
//	Laws:      AUTO-IDEMPOTENT-WRITE, AUTO-READ-AFTER-WRITE, AUTO-COUNT-EQUALS-REFERENCE, AUTO-AGGREGATOR-BOUNDED
//	Not bound:
//	           AUTO-WRITE-OBSERVABLE — KeyOf needs the key projection, which was not derivable here
//	           AUTO-PURE-DETERMINISTIC — Call closes over List, which is not a bare pure call
//	           AUTO-CACHEABLE — Read closes over List, whose shape is collector rather than a keyed reader
func BatchedModel(opts ...BatchedModelOption) BatchedOption {
	return func(c *batchedConfig) {
		c.extensions = append(c.extensions, batchedContractExtension{
			name: "model/twin",
			run: func(t *testing.T, _ string, factory func() batchedmixins.Batched, _ *batchedConfig) {
				model.Check(t, BatchedModelProperty(factory, opts...))
			},
		})
	}
}

// BatchedModelProperty builds the property the option runs — exported because a
// bespoke harness composes from here: model.Check for a test, model.MakeFuzz
// for a coverage-guided fuzz target, both over this one derivation.
func BatchedModelProperty(factory func() batchedmixins.Batched, opts ...BatchedModelOption) func(*model.T) {
	cfg := newBatchedModelConfig(opts...)
	fx := DefaultBatchedFixture()
	// Two keys, drawn for every key slot: collision density is what makes a
	// read revisit a write and an overwrite land on held state. A wide key
	// pool would pass every comparison over a history that never collides.
	keys := model.SampledFrom([]string{fx.Key, fx.KeyOther})
	// Bodies blend the fixture pair with arbitrary draws: the pair keeps
	// identical rewrites frequent, the wide arm reaches values no fixture
	// spells — and nothing in the claims licenses refusing either.
	bodies := model.OneOf(
		model.SampledFrom([]string{fx.Value, fx.ValueOther}),
		model.Make[string](),
	)
	values := bodies
	if cfg.values != nil {
		values = cfg.values
	}
	reference := cfg.reference
	if reference == nil {
		reference = factory
	}
	// The laws the classifications earned, each reporting under its AUTO-
	// identifier when it fails. Observational: a law never mutates, so running
	// them inside the sequences is safe for every step that follows.
	laws := model.NewRegistry[batchedmixins.Batched]()
	laws.Add(law.IdempotentWrite[batchedmixins.Batched, string, []string]{
		Write: func(rt *model.T, s batchedmixins.Batched, v string) error {
			return s.Put(rt.Context(), fx.Key, v)
		},
		Values: values,
		Observe: func(rt *model.T, s batchedmixins.Batched) []string {
			v, err := s.List(rt.Context())
			if err != nil {
				rt.Fatalf("Observe observation failed: %v", err)
			}
			return v
		},
	})
	laws.Add(law.ReadAfterWrite[batchedmixins.Batched, string, string]{
		Read: func(rt *model.T, s batchedmixins.Batched, k string) (string, error) {
			return s.Read(rt.Context(), k)
		},
		Keys: keys,
	})
	laws.Add(law.CountEqualsReference[batchedmixins.Batched, int]{
		Count: func(rt *model.T, s batchedmixins.Batched) (int, error) {
			items, err := s.List(rt.Context())
			return len(items), err
		},
	})
	laws.Add(law.AggregatorBounded[batchedmixins.Batched, int]{
		Read: func(rt *model.T, s batchedmixins.Batched) (int, error) {
			items, err := s.List(rt.Context())
			return len(items), err
		},
		Max: 50,
	})
	return model.Property(factory,
		model.WithReference(reference),
		model.WithLaws(laws),
		model.WithActions(
			action.CompositeWriter("Put", keys, values,
				func(ctx context.Context, s batchedmixins.Batched, k string, v string) error {
					return s.Put(ctx, k, v)
				}),
			action.Reader("Read", keys,
				func(ctx context.Context, s batchedmixins.Batched, k string) (string, error) {
					return s.Read(ctx, k)
				}),
			action.Stream("List",
				func(ctx context.Context, s batchedmixins.Batched) ([]string, error) {
					return s.List(ctx)
				}),
		),
	)
}

// BatchedModelFuzz hands a subject's sequence space to the
// coverage-guided engine: the fuzzer's bytes replay as rapid's choice
// stream, so mutating them mutates the action ordering and every drawn
// input at once — and the engine's coverage feedback climbs the subject's
// own branches, which is what no fixed seed can do. Wire it from a fuzz
// target beside the subject:
//
//	func FuzzBatched(f *testing.F) {
//		BatchedModelFuzz(f, func() Batched { return NewMine() })
//	}
func BatchedModelFuzz(f *testing.F, factory func() batchedmixins.Batched, opts ...BatchedModelOption) {
	f.Add([]byte{})
	f.Fuzz(model.MakeFuzz(BatchedModelProperty(factory, opts...)))
}

// BatchedModelOption configures the model run.
type BatchedModelOption func(*batchedModelConfig)

// BatchedModelReference replaces the derived reference — for an
// interface whose semantics outrun its shape.
func BatchedModelReference(factory func() batchedmixins.Batched) BatchedModelOption {
	return func(c *batchedModelConfig) { c.reference = factory }
}

// BatchedSatWear is one wearable defect: a kind, and the wrap that
// dresses a subject in it.
type batchedSatWear struct {
	kind string
	wrap func(fx BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched
}

//nolint:gochecknoglobals // the prover's wardrobe, read-only after init.
var batchedSatWears = map[string][]batchedSatWear{}

//nolint:gochecknoinits // the wardrobe fills once, keyed by method.
func init() { //nolint:staticcheck // an empty wardrobe leaves dress unused by design.
	dress := func(method, kind string, wrap func(fx BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched) {
		batchedSatWears[method] = append(batchedSatWears[method],
			batchedSatWear{kind: kind, wrap: wrap})
	}
	dress("List", "inert", func(_ BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return batchedSatInertList{s}
	})
	dress("List", "sputter", func(_ BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return &batchedSatSputterList{Batched: s}
	})
	dress("List", "fade", func(_ BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return &batchedSatFadeList{Batched: s}
	})
	dress("Put", "inert", func(_ BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return batchedSatInertPut{s}
	})
	dress("Put", "sputter", func(_ BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return &batchedSatSputterPut{Batched: s}
	})
	dress("Read", "inert", func(_ BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return batchedSatInertRead{s}
	})
	dress("Read", "sputter", func(_ BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return &batchedSatSputterRead{Batched: s}
	})
	dress("Read", "flap", func(fx BatchedFixture, s batchedmixins.Batched) batchedmixins.Batched {
		return &batchedSatFlapRead{Batched: s, a: fx.Value, b: fx.ValueOther}
	})
}

// BatchedModelSaturation proves the bound laws can fail: per law, a
// defect is worn on each method the law's closures reach — zeros, the
// fixture pair alternated, a waning count — and at least one worn run must
// fail naming the law's own identifier, with the clean factory standing as
// reference. A law every defect survives is bound but unsaturatable, and
// fails here by name. Pass the same options that arm the tier: a law behind
// an unarmed door or the clocked factory is skipped visibly, never counted.
func BatchedModelSaturation(t *testing.T, factory func() batchedmixins.Batched, opts ...BatchedModelOption) {
	t.Helper()
	cfg := newBatchedModelConfig(opts...)
	_ = cfg
	fx := DefaultBatchedFixture()
	_ = fx
	t.Run("AUTO-IDEMPOTENT-WRITE", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"List", "Put"} {
				for _, wear := range batchedSatWears[method] {
					surrogate := "BatchedSat_AUTO-IDEMPOTENT-WRITE_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						BatchedModelReference(factory))
					model.Check(f, BatchedModelProperty(func() batchedmixins.Batched {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-IDEMPOTENT-WRITE")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-IDEMPOTENT-WRITE survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
	t.Run("AUTO-READ-AFTER-WRITE", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"Read"} {
				for _, wear := range batchedSatWears[method] {
					surrogate := "BatchedSat_AUTO-READ-AFTER-WRITE_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						BatchedModelReference(factory))
					model.Check(f, BatchedModelProperty(func() batchedmixins.Batched {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-READ-AFTER-WRITE")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-READ-AFTER-WRITE survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
	t.Run("AUTO-COUNT-EQUALS-REFERENCE", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"List"} {
				for _, wear := range batchedSatWears[method] {
					surrogate := "BatchedSat_AUTO-COUNT-EQUALS-REFERENCE_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						BatchedModelReference(factory))
					model.Check(f, BatchedModelProperty(func() batchedmixins.Batched {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "[semantic]") || strings.Contains(f.Msg(), "AUTO-COUNT-EQUALS-REFERENCE")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-COUNT-EQUALS-REFERENCE survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
	t.Run("AUTO-AGGREGATOR-BOUNDED", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"List"} {
				for _, wear := range batchedSatWears[method] {
					surrogate := "BatchedSat_AUTO-AGGREGATOR-BOUNDED_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						BatchedModelReference(factory))
					model.Check(f, BatchedModelProperty(func() batchedmixins.Batched {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-AGGREGATOR-BOUNDED")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-AGGREGATOR-BOUNDED survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
}

// batchedSatInertList answers zeros where List should act.
type batchedSatInertList struct{ batchedmixins.Batched }

func (batchedSatInertList) List(_ context.Context) (z0 []string, z1 error) {
	return
}

// batchedSatSputterList alternates a minted refusal
// with the real answer where List should be steady.
type batchedSatSputterList struct {
	batchedmixins.Batched
	flip atomic.Int64
}

func (m *batchedSatSputterList) List(p0 context.Context) (z0 []string, z1 error) {
	if m.flip.Add(1)%2 == 1 {
		z1 = errors.New("batchedmixinstest: saturation sputtered a refusal")
		return
	}
	return m.Batched.List(p0)
}

// batchedSatFadeList answers every second replay
// reversed and short one — the log lying about what it already showed.
type batchedSatFadeList struct {
	batchedmixins.Batched
	flip atomic.Int64
}

func (m *batchedSatFadeList) List(p0 context.Context) ([]string, error) {
	out, err := m.Batched.List(p0)
	if err != nil || m.flip.Add(1)%2 == 1 || len(out) == 0 {
		return out, err
	}
	faded := slices.Clone(out)
	slices.Reverse(faded)
	return faded[:len(faded)-1], nil
}

// batchedSatInertPut answers zeros where Put should act.
type batchedSatInertPut struct{ batchedmixins.Batched }

func (batchedSatInertPut) Put(_ context.Context, _ string, _ string) (z0 error) {
	return
}

// batchedSatSputterPut alternates a minted refusal
// with the real answer where Put should be steady.
type batchedSatSputterPut struct {
	batchedmixins.Batched
	flip atomic.Int64
}

func (m *batchedSatSputterPut) Put(p0 context.Context, p1 string, p2 string) (z0 error) {
	if m.flip.Add(1)%2 == 1 {
		z0 = errors.New("batchedmixinstest: saturation sputtered a refusal")
		return
	}
	return m.Batched.Put(p0, p1, p2)
}

// batchedSatInertRead answers zeros where Read should act.
type batchedSatInertRead struct{ batchedmixins.Batched }

func (batchedSatInertRead) Read(_ context.Context, _ string) (z0 string, z1 error) {
	return
}

// batchedSatSputterRead alternates a minted refusal
// with the real answer where Read should be steady.
type batchedSatSputterRead struct {
	batchedmixins.Batched
	flip atomic.Int64
}

func (m *batchedSatSputterRead) Read(p0 context.Context, p1 string) (z0 string, z1 error) {
	if m.flip.Add(1)%2 == 1 {
		z1 = errors.New("batchedmixinstest: saturation sputtered a refusal")
		return
	}
	return m.Batched.Read(p0, p1)
}

// batchedSatFlapRead alternates the fixture pair where
// Read should answer the store.
type batchedSatFlapRead struct {
	batchedmixins.Batched
	flip atomic.Int64
	a, b string
}

func (m *batchedSatFlapRead) Read(_ context.Context, _ string) (string, error) {
	if m.flip.Add(1)%2 == 0 {
		return m.a, nil
	}
	return m.b, nil
}

// BatchedModelValues replaces the values pool — for a subject whose
// accepted values a raw draw cannot spell. The pool feeds every value slot,
// the sequences and the laws alike; keep its draws colliding, because values
// that never revisit a key pass every comparison over a history that holds
// nothing twice.
func BatchedModelValues(values *model.Generator[string]) BatchedModelOption {
	return func(c *batchedModelConfig) { c.values = values }
}

type batchedModelConfig struct {
	reference func() batchedmixins.Batched
	values    *model.Generator[string]
}

func newBatchedModelConfig(opts ...BatchedModelOption) *batchedModelConfig {
	c := &batchedModelConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// testkit: end of generated content.
// testkit:provenance 20c92106e54783ff0cd0824b129f37c5123da56c5cc0b635e80c54306be3f75a
