// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/tx/iface.go
// Plugins:   golang 1.0.0, suite 1.0.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package txtest

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/tx"
)

// ContractBeginCheck is one assertion about Begin.
//
// Every generated check for Begin is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type ContractBeginCheck func(tb testing.TB, subject tx.Contract)

// ContractCommitCheck is one assertion about Commit.
//
// Every generated check for Commit is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type ContractCommitCheck func(tb testing.TB, subject tx.Contract)

// ContractRollbackCheck is one assertion about Rollback.
//
// Every generated check for Rollback is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type ContractRollbackCheck func(tb testing.TB, subject tx.Contract)

// ContractFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through ContractWithFixture
// and the check a consumer writes has something to use.
type ContractFixture struct {
}

// DefaultContractFixture is what this run derived. Replace any field through
// ContractWithFixture; the rest keep these values.
func DefaultContractFixture() ContractFixture {
	return ContractFixture{}
}

// AssertContractContract runs every generated check against every declared subject.
//
//	Checks:   12 across 3 methods, per subject
//	Subjects: declare each with ContractSubject
//	Double:   every subject runs a second time wrapped in ContractStub, so
//	          anything the wrapper fails that the subject passes is the double
//	          lying. ContractWithoutDouble declines it.
//	Extend:   ContractOnBegin, ContractOnCommit, ContractOnRollback
//	Drop:     ContractWithout, by the path each check reports under
//
// # What this file does not check
//
// The interface declares these and nothing here asserts them. Each is statable
// against a subject you can build, so the check is yours to write:
//
//   - tx, on Begin, Commit, Rollback — write it with ContractOnBegin
//
// # What is checked somewhere else
//
// These need a reference implementation to compare against, which a suite run
// has no way to build. Nothing here asserts them and nothing here should:
//
//   - lifecycle, on Begin, Commit, Rollback
func AssertContractContract(t *testing.T, opts ...ContractOption) {
	t.Helper()
	cfg := newContractConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertContractContract was given no subject; declare one with " +
			"ContractSubject(name, factory)")
	}
	for _, s := range cfg.subjects {
		runContractChecks(t, cfg, s.name, s.factory, nil)
		if !cfg.withoutDouble {
			runContractChecks(t, cfg, s.name+" through the double", s.factory,
				func(tb testing.TB, subject tx.Contract) tx.Contract {
					return NewContractStub(tb, ContractStubDelegateTo(subject))
				})
		}
	}
}

// runContractChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runContractChecks(
	t *testing.T,
	cfg *contractConfig,
	label string,
	factory func() tx.Contract,
	wrap func(tb testing.TB, subject tx.Contract) tx.Contract,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run("Begin", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Begin/smoke", "smoke", func(tb testing.TB) {
				AssertContractBeginSmoke(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Begin/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertContractBeginCancels(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Begin/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertContractBeginHonoursDeadline(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Begin/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertContractBeginToleratesNilContext(tb, cfg.subject(tb, factory, wrap))
			})
			for _, c := range cfg.onBegin {
				cfg.run(t, "Begin"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap))
				})
			}
		})

		t.Run("Commit", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Commit/smoke", "smoke", func(tb testing.TB) {
				AssertContractCommitSmoke(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Commit/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertContractCommitCancels(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Commit/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertContractCommitHonoursDeadline(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Commit/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertContractCommitToleratesNilContext(tb, cfg.subject(tb, factory, wrap))
			})
			for _, c := range cfg.onCommit {
				cfg.run(t, "Commit"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap))
				})
			}
		})

		t.Run("Rollback", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Rollback/smoke", "smoke", func(tb testing.TB) {
				AssertContractRollbackSmoke(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Rollback/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertContractRollbackCancels(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Rollback/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertContractRollbackHonoursDeadline(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Rollback/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertContractRollbackToleratesNilContext(tb, cfg.subject(tb, factory, wrap))
			})
			for _, c := range cfg.onRollback {
				cfg.run(t, "Rollback"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap))
				})
			}
		})
	})
}

// AssertContractBeginSmoke asserts Begin survives a call with derived inputs.
//
// Fails when: Begin panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertContractBeginSmoke(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Begin panicked on a derived value (%v); supply one it "+
				"accepts through ContractWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_ = subject.Begin(ctx)
}

// AssertContractBeginCancels asserts Begin reports a cancelled context as cancelled.
//
// Fails when: Begin returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertContractBeginCancels(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	err := subject.Begin(ctx)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Begin must report a cancelled context as context.Canceled")
}

// AssertContractBeginHonoursDeadline asserts Begin reports an expired deadline as exceeded.
//
// Fails when: Begin returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertContractBeginHonoursDeadline(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	err := subject.Begin(ctx)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Begin must report an expired deadline as context.DeadlineExceeded")
}

// AssertContractBeginToleratesNilContext asserts Begin does not panic on a nil context.
//
// Fails when: Begin panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertContractBeginToleratesNilContext(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Begin panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_ = subject.Begin(ctx)
}

// AssertContractCommitSmoke asserts Commit survives a call with derived inputs.
//
// Fails when: Commit panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertContractCommitSmoke(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Commit panicked on a derived value (%v); supply one it "+
				"accepts through ContractWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_ = subject.Commit(ctx)
}

// AssertContractCommitCancels asserts Commit reports a cancelled context as cancelled.
//
// Fails when: Commit returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertContractCommitCancels(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	err := subject.Commit(ctx)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Commit must report a cancelled context as context.Canceled")
}

// AssertContractCommitHonoursDeadline asserts Commit reports an expired deadline as exceeded.
//
// Fails when: Commit returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertContractCommitHonoursDeadline(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	err := subject.Commit(ctx)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Commit must report an expired deadline as context.DeadlineExceeded")
}

// AssertContractCommitToleratesNilContext asserts Commit does not panic on a nil context.
//
// Fails when: Commit panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertContractCommitToleratesNilContext(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Commit panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_ = subject.Commit(ctx)
}

// AssertContractRollbackSmoke asserts Rollback survives a call with derived inputs.
//
// Fails when: Rollback panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertContractRollbackSmoke(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Rollback panicked on a derived value (%v); supply one it "+
				"accepts through ContractWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_ = subject.Rollback(ctx)
}

// AssertContractRollbackCancels asserts Rollback reports a cancelled context as cancelled.
//
// Fails when: Rollback returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertContractRollbackCancels(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	err := subject.Rollback(ctx)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Rollback must report a cancelled context as context.Canceled")
}

// AssertContractRollbackHonoursDeadline asserts Rollback reports an expired deadline as exceeded.
//
// Fails when: Rollback returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertContractRollbackHonoursDeadline(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	err := subject.Rollback(ctx)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Rollback must report an expired deadline as context.DeadlineExceeded")
}

// AssertContractRollbackToleratesNilContext asserts Rollback does not panic on a nil context.
//
// Fails when: Rollback panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertContractRollbackToleratesNilContext(tb testing.TB, subject tx.Contract) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Rollback panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_ = subject.Rollback(ctx)
}

// ContractOption configures a contract run.
type ContractOption func(*contractConfig)

// ContractSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func ContractSubject(name string, factory func() tx.Contract) ContractOption {
	return func(c *contractConfig) {
		c.subjects = append(c.subjects, namedContractSubject{name, factory})
	}
}

// ContractWithoutDouble declines the second run through ContractStub.
//
// The double run proves the stand-in is faithful, and costs a second pass over
// every check. Decline it where the double is not used.
func ContractWithoutDouble() ContractOption {
	return func(c *contractConfig) { c.withoutDouble = true }
}

// ContractWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func ContractWithClock(c clock.Clock) ContractOption {
	return func(cfg *contractConfig) { cfg.clock = c }
}

// ContractWithFixture replaces the derived inputs.
func ContractWithFixture(f ContractFixture) ContractOption {
	return func(c *contractConfig) { c.Fixture = f }
}

// ContractSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func ContractSeed(fn func(ctx context.Context, subject tx.Contract) error) ContractOption {
	return func(c *contractConfig) {
		c.seed = fn
	}
}

// ContractOnBegin adds a named check to Begin.
func ContractOnBegin(name string, fn ContractBeginCheck) ContractOption {
	return func(c *contractConfig) {
		c.onBegin = append(c.onBegin, namedContractBeginCheck{name, fn})
	}
}

// ContractOnCommit adds a named check to Commit.
func ContractOnCommit(name string, fn ContractCommitCheck) ContractOption {
	return func(c *contractConfig) {
		c.onCommit = append(c.onCommit, namedContractCommitCheck{name, fn})
	}
}

// ContractOnRollback adds a named check to Rollback.
func ContractOnRollback(name string, fn ContractRollbackCheck) ContractOption {
	return func(c *contractConfig) {
		c.onRollback = append(c.onRollback, namedContractRollbackCheck{name, fn})
	}
}

// ContractWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func ContractWithout(paths ...string) ContractOption {
	return func(c *contractConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedContractBeginCheck struct {
	name string
	fn   ContractBeginCheck
}

type namedContractCommitCheck struct {
	name string
	fn   ContractCommitCheck
}

type namedContractRollbackCheck struct {
	name string
	fn   ContractRollbackCheck
}

type namedContractSubject struct {
	name    string
	factory func() tx.Contract
}

type contractConfig struct {
	Fixture       ContractFixture
	subjects      []namedContractSubject
	withoutDouble bool
	clock         clock.Clock
	seed          func(ctx context.Context, subject tx.Contract) error
	without       map[string]struct{}
	onBegin       []namedContractBeginCheck
	onCommit      []namedContractCommitCheck
	onRollback    []namedContractRollbackCheck
}

func newContractConfig(opts ...ContractOption) *contractConfig {
	c := &contractConfig{
		Fixture: DefaultContractFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *contractConfig) subject(
	tb testing.TB,
	factory func() tx.Contract,
	wrap func(tb testing.TB, subject tx.Contract) tx.Contract,
) tx.Contract {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			tb.Fatalf("the seed supplied through ContractSeed failed: %v", err)
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *contractConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if _, dropped := c.without[path]; dropped {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through ContractWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance fa91a04a4eab1f1fc2f75d249137110a514c59f73fe01478dff374fb43ffa5e8
