// Code generated by testkit builder. DO NOT EDIT.
// Source: testkit builder -o genericstest/nested.gen.go Cache

// This file holds fluent builders for test fixtures. Each builder
// follows the same contract:
//
//   - New<Type>()       creates a builder seeded with defaults (when
//     a <Type>Defaults factory or //testkit:default
//     directives are present) or zero values.
//   - New<Type>From(v)  creates a builder seeded with v.
//   - With<Field>(v)    sets a field; chains.
//   - Append<Field>(v)  appends to a slice field (slice fields only).
//   - With<Field>Entry(k, v) adds a map entry (map fields only).
//   - Mutate(fn)        applies fn to the value under construction.
//   - Clone()           returns a deep copy (slice/map/bytes deep-copied).
//   - Build()           returns the constructed value.
package genericstest_test

import (
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/generator/testdata/generics"
	"go.thesmos.sh/testkit/generator/testdata/generics/genericstest"
)

// TestCacheBuilder verifies the CacheBuilder contract
// against the generated builder: constructor seeding and every
// per-field setter, plus Mutate / Clone independence
// asserted via Default.
func TestCacheBuilder(t *testing.T) {
	t.Parallel()

	// Generic builder runs against a concrete instantiation chosen
	// by the generator (TestTypeArgs); zero-value round-trip is
	// skipped because cmp.Diff against a fresh struct literal
	// isn't meaningful for the generic test view.
	t.Run("Build does not panic", func(t *testing.T) {
		t.Parallel()
		_ = genericstest.NewCache[string, int]().Build()
	})

	t.Run("NewCacheFrom round-trips", func(t *testing.T) {
		t.Parallel()
		v := generics.Cache[string, int]{}
		got := genericstest.NewCacheFrom(v).Build()
		testkit.Equal(t, got, v, "must round-trip zero value")
	})

	t.Run("WithDefault sets field", func(t *testing.T) {
		t.Parallel()
		got := genericstest.NewCache[string, int]().
			WithDefault(42).Build()
		testkit.Equal(t, got.Default, 42, "must set Default")
	})

	t.Run("WithEntries replaces map", func(t *testing.T) {
		t.Parallel()
		sample := map[string]int{}
		got := genericstest.NewCache[string, int]().
			WithEntries(sample).Build()
		testkit.Equal(t, got.Entries, sample, "must set Entries")
	})

	t.Run("WithEntriesEntry lazy-inits and adds", func(t *testing.T) {
		t.Parallel()
		got := genericstest.NewCache[string, int]().
			WithEntriesEntry("test-key", 42).
			Build()
		testkit.Len(t, got.Entries, 1, "lazy-init map must have 1 entry")
		testkit.Equal(t, got.Entries["test-key"], 42,
			"entry must be added")
	})

	t.Run("Clone deep-copies Entries map", func(t *testing.T) {
		t.Parallel()
		base := genericstest.NewCache[string, int]().
			WithEntriesEntry("test-key", 42)
		clone := base.Clone()
		clone.Mutate(func(v *generics.Cache[string, int]) {
			delete(v.Entries, "test-key")
		})
		original := base.Build()
		modified := clone.Build()
		testkit.Len(t, original.Entries, 1,
			"original map must be unchanged after clone deletes")
		testkit.Len(t, modified.Entries, 0,
			"clone map must reflect the delete")
	})

	t.Run("WithRecent replaces existing slice", func(t *testing.T) {
		t.Parallel()
		sample := []int{42}
		got := genericstest.NewCache[string, int]().
			WithRecent(sample...).
			WithRecent(sample...).
			Build()
		testkit.Len(t, got.Recent, len(sample),
			"With must replace, not append — second call overwrites first")
	})

	t.Run("AppendRecent preserves existing", func(t *testing.T) {
		t.Parallel()
		sample := []int{42}
		got := genericstest.NewCache[string, int]().
			WithRecent(sample...).
			AppendRecent(sample...).
			Build()
		testkit.Len(t, got.Recent, len(sample)*2,
			"Append must preserve existing + add new")
	})

	t.Run("Clone deep-copies Recent slice", func(t *testing.T) {
		t.Parallel()
		sample := []int{42}
		base := genericstest.NewCache[string, int]().WithRecent(sample...)
		clone := base.Clone()
		clone.AppendRecent(sample...)
		original := base.Build()
		modified := clone.Build()
		testkit.Len(t, original.Recent, len(sample),
			"original slice must be unchanged after clone mutation")
		testkit.Len(t, modified.Recent, len(sample)*2,
			"clone must have appended")
	})

	t.Run("Clone forks independent copy", func(t *testing.T) {
		t.Parallel()
		base := genericstest.NewCache[string, int]()
		clone := base.Clone().WithDefault(42)
		original := base.Build()
		modified := clone.Build()
		testkit.NotEqual(t, original.Default, modified.Default,
			"Clone must produce independent copy")
	})

	t.Run("Mutate modifies value", func(t *testing.T) {
		t.Parallel()
		got := genericstest.NewCache[string, int]().
			Mutate(func(v *generics.Cache[string, int]) {
				v.Default = 42
			}).Build()
		testkit.Equal(t, got.Default, 42, "Mutate must modify")
	})
}
