// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/writer/iface.go
// Plugins:   golang 1.0.0, suite 1.0.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package writertest_test

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/writer"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/writer/writertest"
)

// Every generated check for Writer, driven against a stand-in built
// to violate it.
//
//	Proved:   4 checks
//
// Each guard asserts the *reason* the check rejected, not merely that it did. A
// stand-in that failed for some unrelated reason — a nil map, a closed channel
// — would satisfy a guard reading only the fact, which is the vacuity this file
// exists to catch, one level up.

// TestAssertWriterPutSmokeCanFail holds AssertWriterPutSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertWriterPutSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := writertest.DefaultWriterFixture()
	subject := writertest.NewWriterStub(t,
		writertest.WithWriterPut(func(context.Context, writer.Value) error {
			panic("Writer.Put: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			writertest.AssertWriterPutSmoke(tb, subject, fixture.V)
		})
	testkit.Assert(t, got).Contains("panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertWriterPutCancelsCanFail holds AssertWriterPutCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertWriterPutCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := writertest.DefaultWriterFixture()
	subject := writertest.NewWriterStub(t,
		writertest.WithWriterPut(func(context.Context, writer.Value) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			writertest.AssertWriterPutCancels(tb, subject, fixture.V)
		})
	testkit.Assert(t, got).Contains("must report a cancelled context",
		"and rejects it for the reason the check is about")
}

// TestAssertWriterPutHonoursDeadlineCanFail holds AssertWriterPutHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertWriterPutHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := writertest.DefaultWriterFixture()
	subject := writertest.NewWriterStub(t,
		writertest.WithWriterPut(func(context.Context, writer.Value) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			writertest.AssertWriterPutHonoursDeadline(tb, subject, fixture.V)
		})
	testkit.Assert(t, got).Contains("must report an expired deadline",
		"and rejects it for the reason the check is about")
}

// TestAssertWriterPutToleratesNilContextCanFail holds AssertWriterPutToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertWriterPutToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := writertest.DefaultWriterFixture()
	subject := writertest.NewWriterStub(t,
		writertest.WithWriterPut(func(context.Context, writer.Value) error {
			panic("Writer.Put: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			writertest.AssertWriterPutToleratesNilContext(tb, subject, fixture.V)
		})
	testkit.Assert(t, got).Contains("panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// testkit: end of generated content.
// testkit:provenance 80cd525d28a8d238e16d92cee3263adfb2c548dcc8c2500be2a63cb599dee5e2
