// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/poisonable/iface.go
// Plugins:   golang 1.0.0, model 0.3.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package poisonabletest

import (
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/poisonable"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
)

// MixedModel runs random sequences of Mixed's methods against every
// subject and a known-good in-memory reference side by side, comparing after
// every call. Pass it to AssertMixedContract; it reports under
// "model", and MixedWithout("model") declines it.
//
//	Reference: the subject's own factory — no reader/writer pair derives a store,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Probe (poisonaccessor)
//	Not driven:
//	           Fail — the poisonable.induce partner — the poison inducer, which would kill one side of the pair
//	Not bound:
//	           AUTO-POISON-NIL-ON-FRESH — the catalogue carries no instantiation spec for it
//	           AUTO-POISON-IDEMPOTENT-READ — the catalogue carries no instantiation spec for it
//	           AUTO-POISON-CONSISTENT — the catalogue carries no instantiation spec for it
func MixedModel(opts ...MixedModelOption) MixedOption {
	return func(c *mixedConfig) {
		c.extensions = append(c.extensions, mixedContractExtension{
			name: "model",
			run: func(t *testing.T, _ string, factory func() poisonable.Mixed, _ *mixedConfig) {
				model.Check(t, MixedModelProperty(factory, opts...))
			},
		})
	}
}

// MixedModelProperty builds the property the option runs — exported because a
// bespoke harness composes from here: model.Check for a test, model.MakeFuzz
// for a coverage-guided fuzz target, both over this one derivation.
func MixedModelProperty(factory func() poisonable.Mixed, opts ...MixedModelOption) func(*model.T) {
	cfg := newMixedModelConfig(opts...)
	reference := cfg.reference
	if reference == nil {
		reference = factory
	}
	return model.Property(factory,
		model.WithReference(reference),
		model.WithActions(
			action.PoisonCheck("Probe",
				func(s poisonable.Mixed) error {
					return s.Probe()
				}),
		),
	)
}

// MixedModelOption configures the model run.
type MixedModelOption func(*mixedModelConfig)

// MixedModelReference replaces the derived reference — for an
// interface whose semantics outrun its shape.
func MixedModelReference(factory func() poisonable.Mixed) MixedModelOption {
	return func(c *mixedModelConfig) { c.reference = factory }
}

type mixedModelConfig struct {
	reference func() poisonable.Mixed
}

func newMixedModelConfig(opts ...MixedModelOption) *mixedModelConfig {
	c := &mixedModelConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// testkit: end of generated content.
// testkit:provenance 2f3566e6baa9b5db19ee7199693ad4533d4959f2da0e4ea8ed12ac92f5aa0713
