// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/sideeffect/iface.go
// Plugins:   golang 1.0.0, stub 1.0.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package sideeffecttest

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/sideeffect"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// MixedTouchCall records one invocation of Mixed.Touch.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type MixedTouchCall struct {
	Ctx context.Context
	Key string
	Err error
}

// MixedObservedCall records one invocation of Mixed.Observed.
//
// Fields take their names from the source signature — parameters and named
// returns alike — so a failure message names what the author named. A slot
// the source left unnamed or blank falls back to a positional name.
type MixedObservedCall struct {
	Ctx    context.Context
	Key    string
	Result int
	Err    error
}

// --- Per-method configuration ---

// MixedTouchStub controls how the double answers Touch and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type MixedTouchStub struct {
	*stub.MethodStub[MixedTouchCall]

	fn       func(context.Context, string) error
	fallback *MixedTouchReturn
}

// MixedTouchReturn holds the fixed answer configured through Returns.
type MixedTouchReturn struct {
	Err error
}

// Returns pins a fixed result for every call to Touch. A Func
// override and an injected fault both take precedence over it.
func (s *MixedTouchStub) Returns(err error) *MixedTouchStub {
	s.fallback = &MixedTouchReturn{Err: err}
	return s
}

// Func supplies a body for Touch, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *MixedTouchStub) Func(fn func(context.Context, string) error) *MixedTouchStub {
	s.fn = fn
	return s
}

// MixedObservedStub controls how the double answers Observed and records
// what it was asked.
//
// The embedded MethodStub supplies the machinery every method shares: call
// recording, fault injection, latency against a virtual clock, gates,
// call-count expectations, and strict mode.
type MixedObservedStub struct {
	*stub.MethodStub[MixedObservedCall]

	fn       func(context.Context, string) (int, error)
	fallback *MixedObservedReturn
}

// MixedObservedReturn holds the fixed answer configured through Returns.
type MixedObservedReturn struct {
	Result int
	Err    error
}

// Returns pins a fixed result for every call to Observed. A Func
// override and an injected fault both take precedence over it.
func (s *MixedObservedStub) Returns(result int, err error) *MixedObservedStub {
	s.fallback = &MixedObservedReturn{Result: result, Err: err}
	return s
}

// Func supplies a body for Observed, for when the answer depends on the
// arguments. An injected fault still takes precedence.
func (s *MixedObservedStub) Func(fn func(context.Context, string) (int, error)) *MixedObservedStub {
	s.fn = fn
	return s
}

// --- MixedStub ---

// MixedStubOption configures a [MixedStub] at construction time.
type MixedStubOption func(*MixedStub)

// MixedStubStrict makes an unconfigured method fail the test rather than
// return its zero value, which turns a call nobody planned for into a failure
// at the call site instead of a puzzling zero further downstream.
func MixedStubStrict() MixedStubOption {
	return func(s *MixedStub) { s.strict = true }
}

// MixedStubDelegateTo wraps a real implementation: every method forwards to
// impl and is recorded on the double on the way through.
//
// This is what lets one generated suite run against both the double and the
// production type, which is the point of conformance testing.
func MixedStubDelegateTo(impl sideeffect.Mixed) MixedStubOption {
	return func(s *MixedStub) {
		s.OnTouch.Func(impl.Touch)
		s.OnObserved.Func(impl.Observed)
	}
}

// MixedStubWithClock drives latency and time-windowed faults from clk
// rather than from wall time, so a test asserting on a five-second timeout
// does not take five seconds.
func MixedStubWithClock(clk clock.Clock) MixedStubOption {
	return func(s *MixedStub) {
		for _, m := range s.all {
			m.SetClock(clk)
		}
	}
}

// MixedStubWithRandSource makes probabilistic fault injection reproducible.
// A failure nobody can replay is not a finding.
func MixedStubWithRandSource(src rand.Source) MixedStubOption {
	return func(s *MixedStub) {
		for _, m := range s.all {
			m.SetRandSource(src)
		}
	}
}

// MixedStubBenchMode disables call recording. Dispatch still works; only
// the accumulating call log is dropped, because its allocations are what a
// benchmark would otherwise be measuring.
func MixedStubBenchMode() MixedStubOption {
	return func(s *MixedStub) {
		for _, m := range s.all {
			m.BenchMode()
		}
	}
}

// WithMixedTouch sets Touch's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithMixedTouch(fn func(context.Context, string) error) MixedStubOption {
	return func(s *MixedStub) { s.OnTouch.Func(fn) }
}

// WithMixedObserved sets Observed's body at construction
// time, for the common case of configuring one method and taking the
// defaults for the rest.
func WithMixedObserved(fn func(context.Context, string) (int, error)) MixedStubOption {
	return func(s *MixedStub) { s.OnObserved.Func(fn) }
}

// MixedStub is a recording test double for Mixed.
//
// Each On<Method> field is that method's configuration point. Left alone, a
// method returns its zero value and records the call.
type MixedStub struct {
	OnTouch    *MixedTouchStub
	OnObserved *MixedObservedStub

	// all is every method stub above, viewed through the surface that does
	// not depend on a signature. It is what lets a setting apply to the whole
	// double in a loop rather than in one line per method.
	all    []stub.Configurable
	strict bool
}

// Compile-time proof that MixedStub satisfies Mixed.
//
// It lives here rather than in the companion so a drifted signature fails
// `go build` rather than waiting for a test run — the double is unusable the
// moment it stops satisfying the interface, and that is worth learning at the
// earliest point it can be known.
var _ sideeffect.Mixed = (*MixedStub)(nil)

// NewMixedStub returns a double bound to tb.
//
// Passing tb registers a cleanup that verifies every method's call-count
// expectations when the test ends, so an unmet Times is reported without the
// caller remembering to check. A nil tb skips that, which is what benchmarks
// and non-test callers want.
func NewMixedStub(tb testing.TB, opts ...MixedStubOption) *MixedStub {
	s := &MixedStub{
		OnTouch:    &MixedTouchStub{MethodStub: stub.NewMethodStub[MixedTouchCall](tb, "Mixed.Touch")},
		OnObserved: &MixedObservedStub{MethodStub: stub.NewMethodStub[MixedObservedCall](tb, "Mixed.Observed")},
	}
	s.all = []stub.Configurable{
		s.OnTouch.MethodStub,
		s.OnObserved.MethodStub,
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		for _, m := range s.all {
			m.Strict()
		}
	}
	if tb != nil {
		// A fuzz target reruns its body many times over and registers a
		// cleanup per run, so verifying there would report against the wrong
		// iteration.
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				for _, m := range s.all {
					m.Verify()
				}
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count
// expectations. Func and Returns configuration is deliberately preserved, so
// a test can reuse one double across phases without rebuilding it.
func (s *MixedStub) ResetCalls() {
	for _, m := range s.all {
		m.Reset()
	}
}

// --- Interface methods ---

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *MixedTouchStub) invoke(ctx context.Context, key string) func() MixedTouchReturn {
	if s.fn == nil {
		return nil
	}
	return func() MixedTouchReturn {
		r0 := s.fn(ctx, key)
		return MixedTouchReturn{Err: r0}
	}
}

// Touch records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *MixedStub) Touch(ctx context.Context, key string) error {
	call := MixedTouchCall{Ctx: ctx, Key: key}
	r := stub.Answer(s.OnTouch.MethodStub, &call, stub.Arms[MixedTouchCall, MixedTouchReturn]{
		Invoke:   s.OnTouch.invoke(ctx, key),
		Fallback: s.OnTouch.fallback,
		Fault:    func(err error) MixedTouchReturn { return MixedTouchReturn{Err: err} },
		Stamp: func(c *MixedTouchCall, r MixedTouchReturn) {
			c.Err = r.Err
		},
	})
	return r.Err
}

// invoke adapts the Func override to the shape [stub.Answer] consumes, or
// returns nil when no override is set — which is how Answer tells "no
// override" from "an override that returns zero".
func (s *MixedObservedStub) invoke(ctx context.Context, key string) func() MixedObservedReturn {
	if s.fn == nil {
		return nil
	}
	return func() MixedObservedReturn {
		r0, r1 := s.fn(ctx, key)
		return MixedObservedReturn{Result: r0, Err: r1}
	}
}

// Observed records the call and answers it.
//
// Which arm answers — injected fault, Func override, Returns fallback, or the
// zero value — is [stub.Answer]'s to decide, so every generated double
// resolves a call the same way and the ordering is tested once rather than
// restated per method.
func (s *MixedStub) Observed(ctx context.Context, key string) (int, error) {
	call := MixedObservedCall{Ctx: ctx, Key: key}
	r := stub.Answer(s.OnObserved.MethodStub, &call, stub.Arms[MixedObservedCall, MixedObservedReturn]{
		Invoke:   s.OnObserved.invoke(ctx, key),
		Fallback: s.OnObserved.fallback,
		Fault:    func(err error) MixedObservedReturn { return MixedObservedReturn{Err: err} },
		Stamp: func(c *MixedObservedCall, r MixedObservedReturn) {
			c.Result = r.Result
			c.Err = r.Err
		},
	})
	return r.Result, r.Err
}

// testkit: end of generated content.
// testkit:provenance fdf4244b51df8c4df02cdc39c2b966a23c62d0ad4052d779a5dd1f48851fbef7
