// Code generated by testkit. DO NOT EDIT.
//
// Source:    conformance/corpus/iface/lang/variadic/iface.go
// Plugins:   golang 1.0.0, suite 1.17.0, backend.golang 1.0.0
// Command:   testkit run ./conformance/corpus/...

package variadictest

import (
	"context"
	"fmt"
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/lang/variadic"
	"go.thesmos.sh/testkit/engine/suite"
	"go.thesmos.sh/testkit/engine/suite/prove"
)

// The generated conformance surface for Finder.
//
// A file-level comment rather than a package doc: three generators write
// into this package and a package doc has one owner, so the listing
// lives with the witness it describes.
//
// Entry points:
//
//	RunFinder(t, opts...)      ProveFinder(t, checks)
//
// A harness is a config literal (FinderHarness); your own checks are a
// table (FinderChecks); drops are written against the typed index:
//
//	FinderSuite.Checks.<Method>.<Check>()
//
// Every ID this package emits:
//
//	Find/cancel
//	Find/deadline
//	Find/nilcontext
//	Find/smoke
//	Find/zero-on-error
//	FindWithLimit/cancel
//	FindWithLimit/deadline
//	FindWithLimit/nilcontext
//	FindWithLimit/smoke
//	FindWithLimit/zero-on-error
//
// Reached by a rule and not derivable here. Each is a claim this file
// does NOT make, so a reader counting coverage from the list above
// knows what is missing and what would bring it back:
//
//	Find's miss check — nothing on this interface writes and no corpus seeds it, so no input is one nothing supplied. To close it: declare what a miss reports with //testkit:mixin notfound sentinel=Err…, or write the claim as a row.
//
// The compatibility handshake. A breaking change to the check surface
// renames the witness, and every file generated against this one stops
// compiling with the skew named rather than dispatching wrong.
var _ = suite.CompatV2

// FinderFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Those drops are listed above with what closes
// each; a row you write is handed this fixture either way.
type FinderFixture struct {
	keys       string
	keysOther  string
	limit      int
	limitOther int
}

// DefaultFinderFixture is what a run with no config draws.
func DefaultFinderFixture() FinderFixture {
	return finderNewFixture()
}

// finderNewFixture is what a run draws from, given its config.
//
// Read through the accessors below rather than as fields: a roled value
// comes from the config's pool and an unroled one from its derived
// literal, and no check that draws should be able to tell which.
func finderNewFixture() FinderFixture {
	return FinderFixture{
		keys:       "test-keys",
		keysOther:  "other-keys",
		limit:      1,
		limitOther: 2,
	}
}

// Keys is the canonical keys every check draws.
//
// One element of a variadic parameter, not the list. Every generated
// check passes it alone; what a method does with several is a claim only
// a check written by hand can make.
func (f FinderFixture) Keys() string { return f.keys }

// KeysOther is a second keys, different from the first — which is
// what lets a miss check miss and a comparison mean something.
func (f FinderFixture) KeysOther() string { return f.keysOther }

// Limit is the canonical limit every check draws.
func (f FinderFixture) Limit() int { return f.limit }

// LimitOther is a second limit, different from the first — which is
// what lets a miss check miss and a comparison mean something.
func (f FinderFixture) LimitOther() int { return f.limitOther }

// Finder is the witnessed instantiation.
//
// A generic interface aliases with its own parameters, which Go admits
// since 1.24 — so every declaration below names Finder and
// the arguments follow, exactly as they do for a concrete one.
type Finder = variadic.Finder

// FinderSubject is the runtime subject a RunWith body receives.
//
// Aliased rather than named through the engine, so a consumer writing a
// row against the subject stays inside this package's vocabulary.
type FinderSubject = suite.Subject[Finder]

// FinderRunOpt is one thing you can pass to RunFinder.
type FinderRunOpt interface {
	applyTo(*finderRunConfig)
}

type finderRunConfig struct {
	suite.Bundle[Finder]

	// rows are the consumer's own checks, bound against the run's
	// fixture once the options are folded — which is why they are held
	// here rather than lowered on arrival: a row bound before the
	// fixture is known would draw from a fixture no run uses.
	rows FinderChecks
}

// FinderHarness declares one Finder implementation under test.
type FinderHarness[T Finder] struct {
	Name string

	// Exactly one constructor.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this subject structurally cannot take.
	Excuse []suite.ID

	// Oracle marks this subject as the run's reference. At most one.
	Oracle bool

	// Serial keeps this subject out of the parallel group.
	Serial bool

	// Provide answers open capabilities beyond the named fields — the
	// doors only this interface's checks know. The runner's gate reads
	// it for any capability without a dedicated field.
	Provide map[suite.Capability]any
}

// Subject lowers the declaration into what the runner consumes.
func (h FinderHarness[T]) Subject() (suite.Subject[Finder], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[Finder]{}, err
	}
	return suite.Subject[Finder]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) Finder { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h FinderHarness[T]) applyTo(rc *finderRunConfig) {
	rc.AddSubject(h.Subject())
}

type finderDropOpt []suite.ID

func (d finderDropOpt) applyTo(rc *finderRunConfig) {
	rc.AddDrops(d...)
}

// finderWithout drops checks by identity.
func finderWithout(ids ...suite.ID) FinderRunOpt {
	return finderDropOpt(ids)
}

// --- The veneer -------------------------------------------------------------

// FinderSuite is the entry a consumer names checks through.
var FinderSuite = finderVeneer{Checks: finderCheckIndex}

type finderVeneer struct {
	// Checks is the check index — the constants a Without call is
	// written against.
	Checks finderCheckIndexT
}

// Without drops a check by ID.
func (finderVeneer) Without(ids ...suite.ID) FinderRunOpt {
	return finderWithout(ids...)
}

// Suite returns the checks as data, for tooling or a runner of your own.
//
// The way in from outside this package: the assembler and the table it
// builds are unexported, because a caller reaching them is doing tooling
// and tooling wants one name rather than one per interface.
func (finderVeneer) Suite(fx FinderFixture) suite.Suite[Finder] {
	return finderSuite(fx)
}

// --- Drop hints -------------------------------------------------------------

// finderIndexPath spells every emitted ID as the path a
// consumer would write to drop it, so a run that declines something can
// say what to type rather than what failed.
var finderIndexPath = map[suite.ID]string{
	finderCheckIndex.Find.Smoke():                "FinderSuite.Checks.Find.Smoke()",
	finderCheckIndex.Find.Cancels():              "FinderSuite.Checks.Find.Cancels()",
	finderCheckIndex.Find.NilContext():           "FinderSuite.Checks.Find.NilContext()",
	finderCheckIndex.Find.Deadline():             "FinderSuite.Checks.Find.Deadline()",
	finderCheckIndex.Find.ZeroOnError():          "FinderSuite.Checks.Find.ZeroOnError()",
	finderCheckIndex.FindWithLimit.Smoke():       "FinderSuite.Checks.FindWithLimit.Smoke()",
	finderCheckIndex.FindWithLimit.Cancels():     "FinderSuite.Checks.FindWithLimit.Cancels()",
	finderCheckIndex.FindWithLimit.NilContext():  "FinderSuite.Checks.FindWithLimit.NilContext()",
	finderCheckIndex.FindWithLimit.Deadline():    "FinderSuite.Checks.FindWithLimit.Deadline()",
	finderCheckIndex.FindWithLimit.ZeroOnError(): "FinderSuite.Checks.FindWithLimit.ZeroOnError()",
}

var finderDropHint = suite.DropHinter(
	"FinderSuite", finderIndexPath,
)

// The names this file spells more than once: one home each.
const (
	finderFind          = "Find"
	finderFindWithLimit = "FindWithLimit"
)

// finderCheckIndex indexes every check this package emits, by
// method and then by check.
var finderCheckIndex = finderCheckIndexT{
	Find:          finderFindChecks{},
	FindWithLimit: finderFindWithLimitChecks{},
}

type finderCheckIndexT struct {
	Find          finderFindChecks
	FindWithLimit finderFindWithLimitChecks
}

// All returns every ID this package emits.
func (finderCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, finderFindChecks{}.All()...)
	out = append(out, finderFindWithLimitChecks{}.All()...)
	return out
}

type finderFindChecks struct{}

func (finderFindChecks) Smoke() suite.ID {
	return suite.MethodID(finderFind, suite.SegSmoke)
}

func (finderFindChecks) Cancels() suite.ID {
	return suite.MethodID(finderFind, suite.SegCancel)
}

func (finderFindChecks) NilContext() suite.ID {
	return suite.MethodID(finderFind, suite.SegNilContext)
}

func (finderFindChecks) Deadline() suite.ID {
	return suite.MethodID(finderFind, suite.SegDeadline)
}

func (finderFindChecks) ZeroOnError() suite.ID {
	return suite.MethodID(finderFind, suite.SegZeroValue)
}

func (finderFindChecks) All() []suite.ID {
	return []suite.ID{
		finderFindChecks{}.Smoke(),
		finderFindChecks{}.Cancels(),
		finderFindChecks{}.NilContext(),
		finderFindChecks{}.Deadline(),
		finderFindChecks{}.ZeroOnError(),
	}
}

type finderFindWithLimitChecks struct{}

func (finderFindWithLimitChecks) Smoke() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegSmoke)
}

func (finderFindWithLimitChecks) Cancels() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegCancel)
}

func (finderFindWithLimitChecks) NilContext() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegNilContext)
}

func (finderFindWithLimitChecks) Deadline() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegDeadline)
}

func (finderFindWithLimitChecks) ZeroOnError() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegZeroValue)
}

func (finderFindWithLimitChecks) All() []suite.ID {
	return []suite.ID{
		finderFindWithLimitChecks{}.Smoke(),
		finderFindWithLimitChecks{}.Cancels(),
		finderFindWithLimitChecks{}.NilContext(),
		finderFindWithLimitChecks{}.Deadline(),
		finderFindWithLimitChecks{}.ZeroOnError(),
	}
}

// finderSuite returns the checks as data, drawn from f.
//
// The seam the proofs companion binds to, and the one a runner of your
// own would. It takes the fixture rather than a config because the
// fixture is what a check draws from; a config that derives one is the
// pool work, and until that lands a caller passes what a default run
// passes.
func finderSuite(fx FinderFixture) suite.Suite[Finder] {
	return suite.Suite[Finder]{
		Name:     "Finder",
		DropHint: finderDropHint,
		Checks:   finderSignatureChecks(fx),
	}
}

// finderSignatureChecks builds every check this run derived.
//
// sig is the one shape they share; the literals below state only what
// differs. Falsifiable is Proven wherever a defect rule reached the
// claim AND the companion beside this file spells that defect — the
// parity gate refuses the stamp without the evidence, so a claim this
// run cannot yet plant is argued rather than asserted.
func finderSignatureChecks(fx FinderFixture) []suite.Check[Finder] {
	sig := suite.ProvenCheck[Finder]
	ix := finderCheckIndex
	return []suite.Check[Finder]{
		sig(ix.Find.Smoke(), suite.ClassSmoke,
			"Find survives a call with a seeded keys",
			func(tb testing.TB, f Finder) {
				finderAssertFindSmoke(tb, f, fx)
			}),
		sig(ix.Find.Cancels(), suite.ClassCancel,
			"Find reports a cancelled context as cancelled",
			func(tb testing.TB, f Finder) {
				finderAssertFindCancels(tb, f, fx)
			}),
		sig(ix.Find.NilContext(), suite.ClassNilContext,
			"Find returns an error rather than panicking on a nil context",
			func(tb testing.TB, f Finder) {
				finderAssertFindToleratesNilContext(tb, f, fx)
			}),
		sig(ix.Find.Deadline(), suite.ClassDeadline,
			"Find reports an expired deadline as exceeded",
			func(tb testing.TB, f Finder) {
				finderAssertFindHonoursDeadline(tb, f, fx)
			}),
		sig(ix.Find.ZeroOnError(), suite.ClassZeroValue,
			"Find returns nothing alongside any error",
			func(tb testing.TB, f Finder) {
				finderAssertFindZeroOnError(tb, f, fx)
			}),
		sig(ix.FindWithLimit.Smoke(), suite.ClassSmoke,
			"FindWithLimit survives a call with seeded inputs",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitSmoke(tb, f, fx)
			}),
		sig(ix.FindWithLimit.Cancels(), suite.ClassCancel,
			"FindWithLimit reports a cancelled context as cancelled",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitCancels(tb, f, fx)
			}),
		sig(ix.FindWithLimit.NilContext(), suite.ClassNilContext,
			"FindWithLimit returns an error rather than panicking on a nil context",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitToleratesNilContext(tb, f, fx)
			}),
		sig(ix.FindWithLimit.Deadline(), suite.ClassDeadline,
			"FindWithLimit reports an expired deadline as exceeded",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitHonoursDeadline(tb, f, fx)
			}),
		sig(ix.FindWithLimit.ZeroOnError(), suite.ClassZeroValue,
			"FindWithLimit returns nothing alongside any error",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitZeroOnError(tb, f, fx)
			}),
	}
}

// finderAssertFindSmoke asserts Find survives a call with a seeded keys.
func finderAssertFindSmoke(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.Survives(tb, finderFind, func(ctx context.Context) {
		_, _ = f.Find(ctx, fx.Keys())
	})
}

// finderAssertFindCancels asserts Find reports a cancelled context as cancelled.
func finderAssertFindCancels(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, finderFind, func(ctx context.Context) error {
		_, err := f.Find(ctx, fx.Keys())
		return err
	})
}

// finderAssertFindToleratesNilContext asserts Find returns an error rather than panicking on a nil context.
func finderAssertFindToleratesNilContext(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, finderFind, func(ctx context.Context) error {
		_, err := f.Find(ctx, fx.Keys())
		return err
	})
}

// finderAssertFindHonoursDeadline asserts Find reports an expired deadline as exceeded.
func finderAssertFindHonoursDeadline(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, finderFind, func(ctx context.Context) error {
		_, err := f.Find(ctx, fx.Keys())
		return err
	})
}

// finderAssertFindZeroOnError asserts Find returns nothing alongside any error.
func finderAssertFindZeroOnError(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := f.Find(ctx, fx.Keys())
	if err == nil {
		tb.Skip("Find answered for a cancelled context, so this check has no error to inspect")
	}

	if got != nil {
		tb.Errorf("Find must return nothing alongside an error (err %v)", err)
	}
}

// finderAssertFindWithLimitSmoke asserts FindWithLimit survives a call with seeded inputs.
func finderAssertFindWithLimitSmoke(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.Survives(tb, finderFindWithLimit, func(ctx context.Context) {
		_, _ = f.FindWithLimit(ctx, fx.Limit(), fx.Keys())
	})
}

// finderAssertFindWithLimitCancels asserts FindWithLimit reports a cancelled context as cancelled.
func finderAssertFindWithLimitCancels(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, finderFindWithLimit, func(ctx context.Context) error {
		_, err := f.FindWithLimit(ctx, fx.Limit(), fx.Keys())
		return err
	})
}

// finderAssertFindWithLimitToleratesNilContext asserts FindWithLimit returns an error rather than panicking on a nil context.
func finderAssertFindWithLimitToleratesNilContext(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, finderFindWithLimit, func(ctx context.Context) error {
		_, err := f.FindWithLimit(ctx, fx.Limit(), fx.Keys())
		return err
	})
}

// finderAssertFindWithLimitHonoursDeadline asserts FindWithLimit reports an expired deadline as exceeded.
func finderAssertFindWithLimitHonoursDeadline(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, finderFindWithLimit, func(ctx context.Context) error {
		_, err := f.FindWithLimit(ctx, fx.Limit(), fx.Keys())
		return err
	})
}

// finderAssertFindWithLimitZeroOnError asserts FindWithLimit returns nothing alongside any error.
func finderAssertFindWithLimitZeroOnError(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := f.FindWithLimit(ctx, fx.Limit(), fx.Keys())
	if err == nil {
		tb.Skip("FindWithLimit answered for a cancelled context, so this check has no error to inspect")
	}

	if got != nil {
		tb.Errorf("FindWithLimit must return nothing alongside an error (err %v)", err)
	}
}

// FinderDefect is anything that can stand as a planted defect for a
// row — in practice a FinderHarness over the generated double.
type FinderDefect interface {
	Subject() (FinderSubject, error)
}

// BrokenFinder names a planted defect.
//
// Sugar over the harness, because a defect IS a subject — one built to
// fail exactly one claim. Its own constructor is what keeps a proofs
// table readable beside a run's.
func BrokenFinder[T Finder](
	name string, build func() T,
) FinderHarness[T] {
	return FinderHarness[T]{
		Name: name, New: build,
	}
}

// FinderChecks is the table of this package's own checks.
type FinderChecks []FinderCheck

func (c FinderChecks) applyTo(rc *finderRunConfig) {
	rc.rows = append(rc.rows, c...)
}

// FinderCheck is one row. The body is a plain named function; which
// field it goes in decides what it receives.
type FinderCheck struct {
	// Method scopes Run's ID: "Find" makes it Find/<name>.
	// A body that fixes its own scope leaves this empty.
	Method string

	// Name is the ID's slug — the stable handle a drop and a rerun use.
	Name string

	// Claim is the sentence the manifest records and the report reads
	// out. A claim wider than its assertion is the one failure this
	// surface cannot catch for you.
	Claim string

	// Exactly one body.
	//
	// Run gets one fresh instance, which is nearly every check. RunWith
	// gets the subject itself, for a claim one instance cannot state:
	// build two, move the clock, induce a failure.
	//
	// Both take the fixture whether or not any DERIVED check draws one,
	// so the row seam has one shape across every package and a fixture
	// that later grows a field does not change a signature consumers
	// have already written against.
	Run     func(tb testing.TB, s Finder, fx FinderFixture)
	RunWith func(tb testing.TB, sub FinderSubject, fx FinderFixture)

	// Class buckets the report. Empty means hand-written.
	Class suite.Class

	// Needs declares capabilities. A harness that cannot meet one fails
	// this check by name with the fix in the message, never skips — a
	// check that skipped for want of wiring reads as coverage.
	Needs suite.Caps

	// ProvenBy is the planted defect that fails this check and nothing
	// else. Setting it is the claim AND the evidence: the row reports
	// Proven, and ProveFinder fails unless the defect turns the check
	// red. ProvenReason, when set, is a substring that red must contain,
	// so a defect dying on an incidental guard stops counting as one.
	//
	// Argued records why no defect can be constructed — the honest third
	// answer. At most one of ProvenBy and Argued; neither means unproven,
	// which is what the report says about a check nobody has driven
	// against anything.
	ProvenBy     FinderDefect
	ProvenReason string
	Argued       string
}

// finderMethods is the interface's method set, for naming a Method typo
// at run start.
//
// A misspelled method starts with a capital too, so the ID grammar alone
// would file a check under a method that does not exist and report it
// under a path no drop can name.
var finderMethods = suite.NewNameSet("Finder", finderFind, finderFindWithLimit)

// bind lowers one row onto the runtime check type, against the run's own
// fixture — which is what lets a row's body draw what the run draws.
func (c FinderCheck) bind(
	fx FinderFixture,
) (suite.Check[Finder], error) {
	out := suite.Check[Finder]{
		Claim: c.Claim, Class: c.Class, Needs: c.Needs,
	}
	if out.Class == "" {
		out.Class = suite.ClassHandWritten
	}

	var err error
	bodies := 0
	if c.Run != nil {
		bodies++
		if out.ID, err = suite.RowID("Run", c.Method, c.Name, finderMethods); err != nil {
			return out, err
		}
		run := c.Run
		out.Run = func(tb testing.TB, s Finder) {
			run(tb, s, fx)
		}
	}
	if c.RunWith != nil {
		bodies++
		out.ID = suite.HandRowID(c.Name)
		rw := c.RunWith
		out.RunWith = func(tb testing.TB, sub FinderSubject) {
			rw(tb, sub, fx)
		}
	}
	if err := suite.OneBody(c.Name, bodies, "Run, RunWith"); err != nil {
		return out, err
	}
	if c.Method != "" && c.Run == nil {
		return out, fmt.Errorf(
			"check %q sets Method, but its body fixes its own scope; drop Method", c.Name)
	}
	if out.Falsifiable, err = suite.Falsify(c.Name, c.ProvenBy != nil, c.Argued); err != nil {
		return out, err
	}
	return out, nil
}

// RunFinder runs every check — generated and yours — against every
// harness.
//
//	RunFinder(t,
//		FinderHarness[*InMemory]{Name: "in-memory", New: NewInMemory},
//		FinderSuite.Without(FinderSuite.Checks.Find.Smoke()),
//	)
func RunFinder(
	t *testing.T, opts ...FinderRunOpt,
) {
	t.Helper()
	var rc finderRunConfig
	for _, o := range opts {
		o.applyTo(&rc)
	}
	fx := finderNewFixture()
	for _, row := range rc.rows {
		rc.AddCheck(row.bind(fx))
	}
	// Between folding and running: a misused run reports every fix it
	// needs and executes nothing, rather than reporting one and leaving
	// the rest to be found a cycle at a time.
	rc.Fail(t, "RunFinder")
	suite.Run(t,
		finderSuite(fx).With(rc.Extra...).Without(rc.Drops...),
		rc.Subjects...)
}

// ProveFinder drives each of your rows against the defect it names.
//
// A row with no ProvenBy is not skipped — it is held to saying why
// through Argued. The parity gate refuses a Proven claim with no
// evidence and evidence for a claim nobody made, in both directions, so
// this is where "proven able to fail" stops being prose.
func ProveFinder(
	t *testing.T, checks FinderChecks,
) {
	t.Helper()
	// The RUN's config, not the derived one: a check proven at default
	// pools carries no evidence about the pools a run actually uses.
	fx := finderNewFixture()
	bound := make([]suite.Check[Finder], 0, len(checks))
	defects := prove.Defects[Finder]{}
	for _, row := range checks {
		bd, err := row.bind(fx)
		if err != nil {
			t.Fatalf("ProveFinder: %v", err)
		}
		bound = append(bound, bd)
		if row.ProvenBy == nil {
			continue
		}
		sub, err := row.ProvenBy.Subject()
		if err != nil {
			t.Fatalf("ProveFinder: check %q: defect: %v", bd.ID, err)
		}
		defects[bd.ID] = prove.Defect[Finder]{
			Subject: sub, Reason: row.ProvenReason,
		}
	}
	prove.All(t, bound, defects)
}

// testkit: end of generated content.
// testkit:provenance 49bbf80766a9f221538bc424b32f32c77b2f8e7391f9e5d8d1375d0823eb3047
