// Code generated by testkit. DO NOT EDIT.
//
// Source:    conformance/corpus/iface/lang/variadic/iface.go
// Plugins:   golang 1.0.0, suite 1.16.0, backend.golang 1.0.0
// Command:   testkit run ./conformance/corpus/...

package variadictest

import (
	"context"
	"slices"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/lang/variadic"
	"go.thesmos.sh/testkit/engine/suite"
)

// FinderFindCheck is one assertion about Find.
//
// Every generated check for Find is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
//
// keys is one element of Find's variadic parameter, not the list.
// The fixture derives one value per parameter, so every generated check calls
// Find with exactly one — which leaves everything about *several* to a
// check written here, including the empty call no derivation reaches.
type FinderFindCheck func(tb testing.TB, subject variadic.Finder, keys string)

// FinderFindWithLimitCheck is one assertion about FindWithLimit.
//
// Every generated check for FindWithLimit is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
//
// keys is one element of FindWithLimit's variadic parameter, not the list.
// The fixture derives one value per parameter, so every generated check calls
// FindWithLimit with exactly one — which leaves everything about *several* to a
// check written here, including the empty call no derivation reaches.
type FinderFindWithLimitCheck func(tb testing.TB, subject variadic.Finder, limit int, keys string)

// FinderFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through FinderWithFixture
// and the check a consumer writes has something to use.
type FinderFixture struct {
	// Keys is one element of a variadic parameter, not the list. Every
	// generated check passes it alone; what a method does with several is a
	// claim only a check written by hand can make.
	Keys       string
	KeysOther  string
	Limit      int
	LimitOther int
}

// DefaultFinderFixture is what this run derived. Replace any field through
// FinderWithFixture; the rest keep these values.
func DefaultFinderFixture() FinderFixture {
	return FinderFixture{
		Keys:       "test-keys",
		KeysOther:  "other-keys",
		Limit:      1,
		LimitOther: 2,
	}
}

// Finder is the witnessed instantiation.
//
// A generic interface aliases with its own parameters, which Go admits
// since 1.24 — so every declaration below names Finder and
// the arguments follow, exactly as they do for a concrete one.
type Finder = variadic.Finder

// FinderRunOpt is one thing you can pass to RunFinder.
type FinderRunOpt interface {
	applyTo(*finderRunConfig)
}

type finderRunConfig struct {
	suite.Bundle[Finder]
}

// FinderHarness declares one Finder implementation under test.
type FinderHarness[T Finder] struct {
	Name string

	// Exactly one constructor.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this subject structurally cannot take.
	Excuse []suite.ID

	// Oracle marks this subject as the run's reference. At most one.
	Oracle bool

	// Serial keeps this subject out of the parallel group.
	Serial bool

	// Provide answers open capabilities beyond the named fields — the
	// doors only this interface's checks know. The runner's gate reads
	// it for any capability without a dedicated field.
	Provide map[suite.Capability]any
}

// Subject lowers the declaration into what the runner consumes.
func (h FinderHarness[T]) Subject() (suite.Subject[Finder], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[Finder]{}, err
	}
	return suite.Subject[Finder]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) Finder { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h FinderHarness[T]) applyTo(rc *finderRunConfig) {
	rc.AddSubject(h.Subject())
}

type finderDropOpt []suite.ID

func (d finderDropOpt) applyTo(rc *finderRunConfig) {
	rc.AddDrops(d...)
}

// finderWithout drops checks by identity.
func finderWithout(ids ...suite.ID) FinderRunOpt {
	return finderDropOpt(ids)
}

// --- The veneer -------------------------------------------------------------

// FinderSuite is the entry a consumer names checks through.
var FinderSuite = finderVeneer{Checks: finderCheckIndex}

type finderVeneer struct {
	// Checks is the check index — the constants a Without call is
	// written against.
	Checks finderCheckIndexT
}

// Without drops a check by ID.
func (finderVeneer) Without(ids ...suite.ID) FinderRunOpt {
	return finderWithout(ids...)
}

// --- Drop hints -------------------------------------------------------------

// finderIndexPath spells every emitted ID as the path a
// consumer would write to drop it, so a run that declines something can
// say what to type rather than what failed.
var finderIndexPath = map[suite.ID]string{
	finderCheckIndex.Find.Smoke():                "FinderSuite.Checks.Find.Smoke()",
	finderCheckIndex.Find.Cancels():              "FinderSuite.Checks.Find.Cancels()",
	finderCheckIndex.Find.NilContext():           "FinderSuite.Checks.Find.NilContext()",
	finderCheckIndex.Find.Deadline():             "FinderSuite.Checks.Find.Deadline()",
	finderCheckIndex.Find.ZeroOnError():          "FinderSuite.Checks.Find.ZeroOnError()",
	finderCheckIndex.FindWithLimit.Smoke():       "FinderSuite.Checks.FindWithLimit.Smoke()",
	finderCheckIndex.FindWithLimit.Cancels():     "FinderSuite.Checks.FindWithLimit.Cancels()",
	finderCheckIndex.FindWithLimit.NilContext():  "FinderSuite.Checks.FindWithLimit.NilContext()",
	finderCheckIndex.FindWithLimit.Deadline():    "FinderSuite.Checks.FindWithLimit.Deadline()",
	finderCheckIndex.FindWithLimit.ZeroOnError(): "FinderSuite.Checks.FindWithLimit.ZeroOnError()",
}

var finderDropHint = suite.DropHinter(
	"FinderSuite", finderIndexPath,
)

// The names this file spells more than once: one home each.
const (
	finderFind          = "Find"
	finderFindWithLimit = "FindWithLimit"
)

// finderCheckIndex indexes every check this package emits, by
// method and then by check.
var finderCheckIndex = finderCheckIndexT{
	Find:          finderFindChecks{},
	FindWithLimit: finderFindWithLimitChecks{},
}

type finderCheckIndexT struct {
	Find          finderFindChecks
	FindWithLimit finderFindWithLimitChecks
}

// All returns every ID this package emits.
func (finderCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, finderFindChecks{}.All()...)
	out = append(out, finderFindWithLimitChecks{}.All()...)
	return out
}

type finderFindChecks struct{}

func (finderFindChecks) Smoke() suite.ID {
	return suite.MethodID(finderFind, suite.SegSmoke)
}

func (finderFindChecks) Cancels() suite.ID {
	return suite.MethodID(finderFind, suite.SegCancel)
}

func (finderFindChecks) NilContext() suite.ID {
	return suite.MethodID(finderFind, suite.SegNilContext)
}

func (finderFindChecks) Deadline() suite.ID {
	return suite.MethodID(finderFind, suite.SegDeadline)
}

func (finderFindChecks) ZeroOnError() suite.ID {
	return suite.MethodID(finderFind, suite.SegZeroValue)
}

func (finderFindChecks) All() []suite.ID {
	return []suite.ID{
		finderFindChecks{}.Smoke(),
		finderFindChecks{}.Cancels(),
		finderFindChecks{}.NilContext(),
		finderFindChecks{}.Deadline(),
		finderFindChecks{}.ZeroOnError(),
	}
}

type finderFindWithLimitChecks struct{}

func (finderFindWithLimitChecks) Smoke() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegSmoke)
}

func (finderFindWithLimitChecks) Cancels() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegCancel)
}

func (finderFindWithLimitChecks) NilContext() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegNilContext)
}

func (finderFindWithLimitChecks) Deadline() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegDeadline)
}

func (finderFindWithLimitChecks) ZeroOnError() suite.ID {
	return suite.MethodID(finderFindWithLimit, suite.SegZeroValue)
}

func (finderFindWithLimitChecks) All() []suite.ID {
	return []suite.ID{
		finderFindWithLimitChecks{}.Smoke(),
		finderFindWithLimitChecks{}.Cancels(),
		finderFindWithLimitChecks{}.NilContext(),
		finderFindWithLimitChecks{}.Deadline(),
		finderFindWithLimitChecks{}.ZeroOnError(),
	}
}

// finderSignatureChecks builds every check this run derived.
//
// sig is the one shape they share; the literals below state only what
// differs. Falsifiable is Proven wherever a defect rule reached the
// claim, which the parity gate refuses to stamp without one.
func finderSignatureChecks(fx FinderFixture) []suite.Check[Finder] {
	sig := suite.ProvenCheck[Finder]
	ix := finderCheckIndex
	return []suite.Check[Finder]{
		sig(ix.Find.Smoke(), suite.ClassSmoke,
			"Find survives a call with a seeded keys",
			func(tb testing.TB, f Finder) {
				finderAssertFindSmoke(tb, f, fx)
			}),
		sig(ix.Find.Cancels(), suite.ClassCancel,
			"Find reports a cancelled context as cancelled",
			func(tb testing.TB, f Finder) {
				finderAssertFindCancels(tb, f, fx)
			}),
		sig(ix.Find.NilContext(), suite.ClassNilContext,
			"Find returns an error rather than panicking on a nil context",
			func(tb testing.TB, f Finder) {
				finderAssertFindToleratesNilContext(tb, f, fx)
			}),
		sig(ix.Find.Deadline(), suite.ClassDeadline,
			"Find reports an expired deadline as exceeded",
			func(tb testing.TB, f Finder) {
				finderAssertFindHonoursDeadline(tb, f, fx)
			}),
		sig(ix.Find.ZeroOnError(), suite.ClassZeroValue,
			"Find returns nothing alongside any error",
			func(tb testing.TB, f Finder) {
				finderAssertFindZeroOnError(tb, f, fx)
			}),
		sig(ix.FindWithLimit.Smoke(), suite.ClassSmoke,
			"FindWithLimit survives a call with seeded inputs",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitSmoke(tb, f, fx)
			}),
		sig(ix.FindWithLimit.Cancels(), suite.ClassCancel,
			"FindWithLimit reports a cancelled context as cancelled",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitCancels(tb, f, fx)
			}),
		sig(ix.FindWithLimit.NilContext(), suite.ClassNilContext,
			"FindWithLimit returns an error rather than panicking on a nil context",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitToleratesNilContext(tb, f, fx)
			}),
		sig(ix.FindWithLimit.Deadline(), suite.ClassDeadline,
			"FindWithLimit reports an expired deadline as exceeded",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitHonoursDeadline(tb, f, fx)
			}),
		sig(ix.FindWithLimit.ZeroOnError(), suite.ClassZeroValue,
			"FindWithLimit returns nothing alongside any error",
			func(tb testing.TB, f Finder) {
				finderAssertFindWithLimitZeroOnError(tb, f, fx)
			}),
	}
}

// finderAssertFindSmoke asserts Find survives a call with a seeded keys.
func finderAssertFindSmoke(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.Survives(tb, finderFind, func(ctx context.Context) {
		_, _ = f.Find(ctx, fx.Keys)
	})
}

// finderAssertFindCancels asserts Find reports a cancelled context as cancelled.
func finderAssertFindCancels(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, finderFind, func(ctx context.Context) error {
		_, err := f.Find(ctx, fx.Keys)
		return err
	})
}

// finderAssertFindToleratesNilContext asserts Find returns an error rather than panicking on a nil context.
func finderAssertFindToleratesNilContext(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, finderFind, func(ctx context.Context) error {
		_, err := f.Find(ctx, fx.Keys)
		return err
	})
}

// finderAssertFindHonoursDeadline asserts Find reports an expired deadline as exceeded.
func finderAssertFindHonoursDeadline(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, finderFind, func(ctx context.Context) error {
		_, err := f.Find(ctx, fx.Keys)
		return err
	})
}

// finderAssertFindZeroOnError asserts Find returns nothing alongside any error.
func finderAssertFindZeroOnError(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := f.Find(ctx, fx.Keys)
	if err == nil {
		tb.Skip("Find answered for a cancelled context, so this check has no error to inspect")
	}

	if got != nil {
		tb.Errorf("Find must return nothing alongside an error (err %v)", err)
	}
}

// finderAssertFindWithLimitSmoke asserts FindWithLimit survives a call with seeded inputs.
func finderAssertFindWithLimitSmoke(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.Survives(tb, finderFindWithLimit, func(ctx context.Context) {
		_, _ = f.FindWithLimit(ctx, fx.Limit, fx.Keys)
	})
}

// finderAssertFindWithLimitCancels asserts FindWithLimit reports a cancelled context as cancelled.
func finderAssertFindWithLimitCancels(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, finderFindWithLimit, func(ctx context.Context) error {
		_, err := f.FindWithLimit(ctx, fx.Limit, fx.Keys)
		return err
	})
}

// finderAssertFindWithLimitToleratesNilContext asserts FindWithLimit returns an error rather than panicking on a nil context.
func finderAssertFindWithLimitToleratesNilContext(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, finderFindWithLimit, func(ctx context.Context) error {
		_, err := f.FindWithLimit(ctx, fx.Limit, fx.Keys)
		return err
	})
}

// finderAssertFindWithLimitHonoursDeadline asserts FindWithLimit reports an expired deadline as exceeded.
func finderAssertFindWithLimitHonoursDeadline(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, finderFindWithLimit, func(ctx context.Context) error {
		_, err := f.FindWithLimit(ctx, fx.Limit, fx.Keys)
		return err
	})
}

// finderAssertFindWithLimitZeroOnError asserts FindWithLimit returns nothing alongside any error.
func finderAssertFindWithLimitZeroOnError(
	tb testing.TB,
	f Finder,
	fx FinderFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := f.FindWithLimit(ctx, fx.Limit, fx.Keys)
	if err == nil {
		tb.Skip("FindWithLimit answered for a cancelled context, so this check has no error to inspect")
	}

	if got != nil {
		tb.Errorf("FindWithLimit must return nothing alongside an error (err %v)", err)
	}
}

// AssertFinderContract runs every generated check against every declared subject.
//
//	Subjects: declare each with FinderSubject
//	Extend:   FinderOnFind, FinderOnFindWithLimit
//	Drop:     FinderWithout, by the path each check reports under
//	Unseeded: every check here runs against a fresh subject, because
//	          no method here is classified as a write.
//	          A read over an empty subject cannot tell a miss from a bug;
//	          FinderSeed is what closes it.
func AssertFinderContract(t *testing.T, opts ...FinderOption) {
	t.Helper()
	cfg := newFinderConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertFinderContract was given no subject; declare one with " +
			"FinderSubject(name, factory)")
	}
	for _, p := range cfg.phantoms() {
		t.Errorf("FinderWithout(%q) declines nothing: no check here reports "+
			"under that path, so this suite asserts one thing more than its "+
			"author believes", p)
	}
	for _, s := range cfg.subjects {
		runFinderChecks(t, cfg, s.name, s.factory, nil)
	}
}

// runFinderChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runFinderChecks(
	t *testing.T,
	cfg *finderConfig,
	label string,
	factory func() variadic.Finder,
	wrap func(tb testing.TB, subject variadic.Finder) variadic.Finder,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run(finderFind, func(t *testing.T) {
			t.Parallel()

			for _, c := range cfg.onFind {
				cfg.run(t, string(suite.MethodID(finderFind, c.name)), c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Keys)
				})
			}
		})

		t.Run(finderFindWithLimit, func(t *testing.T) {
			t.Parallel()

			for _, c := range cfg.onFindWithLimit {
				cfg.run(t, string(suite.MethodID(finderFindWithLimit, c.name)), c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Limit, cfg.Fixture.Keys)
				})
			}
		})

		// The extra bodies of checks this run was given, each reporting under its
		// own name and dropped by it.
		//
		// The plain subject only. The wrapped pass exists to prove the double
		// faithful and the per-method checks above already do that, so running one
		// through the wrapper prices the wrapper and says nothing new about the
		// subject.
		if wrap == nil {
			for _, e := range cfg.extensions {
				if cfg.declined(e.name) {
					t.Run(e.name, func(t *testing.T) {
						t.Skipf("dropped through FinderWithout(%q)", e.name)
					})
					continue
				}
				t.Run(e.name, func(t *testing.T) {
					t.Parallel()
					e.run(t, label, factory, cfg)
				})
			}
		}
	})
}

// FinderOption configures a contract run.
type FinderOption func(*finderConfig)

// FinderSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func FinderSubject(name string, factory func() variadic.Finder) FinderOption {
	return func(c *finderConfig) {
		c.subjects = append(c.subjects, namedFinderSubject{name, factory})
	}
}

// FinderWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func FinderWithClock(c clock.Clock) FinderOption {
	return func(cfg *finderConfig) { cfg.clock = c }
}

// FinderWithFixture replaces the derived inputs.
func FinderWithFixture(f FinderFixture) FinderOption {
	return func(c *finderConfig) { c.Fixture = f }
}

// FinderSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func FinderSeed(fn func(ctx context.Context, subject variadic.Finder) error) FinderOption {
	return func(c *finderConfig) {
		c.seed = fn
	}
}

// FinderOnFind adds a named check to Find.
func FinderOnFind(name string, fn FinderFindCheck) FinderOption {
	return func(c *finderConfig) {
		c.onFind = append(c.onFind, namedFinderFindCheck{name, fn})
	}
}

// FinderOnFindWithLimit adds a named check to FindWithLimit.
func FinderOnFindWithLimit(name string, fn FinderFindWithLimitCheck) FinderOption {
	return func(c *finderConfig) {
		c.onFindWithLimit = append(c.onFindWithLimit, namedFinderFindWithLimitCheck{name, fn})
	}
}

// FinderWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func FinderWithout(paths ...string) FinderOption {
	return func(c *finderConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedFinderFindCheck struct {
	name string
	fn   FinderFindCheck
}

type namedFinderFindWithLimitCheck struct {
	name string
	fn   FinderFindWithLimitCheck
}

type namedFinderSubject struct {
	name    string
	factory func() variadic.Finder
}

// finderContractExtension is a body of checks a generated sibling adds through an option.
//
// A sibling declares the option and closes over whatever configures it, so
// everything that varies per run is typed and private to the file that owns it
// — this file understands only the name and the call. Nothing arrives except
// through an option, which is what keeps the set fixed before the first subtest
// starts.
type finderContractExtension struct {
	// name is the path this reports under, and the one FinderWithout drops
	// it by. Anything nested beneath it is the extension's own to name.
	name string

	// run takes the factory rather than a subject. One that drives sequences
	// builds a subject per iteration, and one that compares against a reference
	// needs the unseeded subject a factory returns — which
	// finderConfig.subject is not.
	//
	// Called once per subject, in parallel, sharing the config. Anything it
	// mutates has to be built inside the call: state captured when the option
	// was declared is state two subjects write at once.
	run func(
		t *testing.T,
		subject string,
		factory func() variadic.Finder,
		cfg *finderConfig,
	)
}

type finderConfig struct {
	Fixture         FinderFixture
	subjects        []namedFinderSubject
	clock           clock.Clock
	seed            func(ctx context.Context, subject variadic.Finder) error
	without         map[string]struct{}
	extensions      []finderContractExtension
	onFind          []namedFinderFindCheck
	onFindWithLimit []namedFinderFindWithLimitCheck
}

func newFinderConfig(opts ...FinderOption) *finderConfig {
	c := &finderConfig{
		Fixture: DefaultFinderFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *finderConfig) subject(
	tb testing.TB,
	factory func() variadic.Finder,
	wrap func(tb testing.TB, subject variadic.Finder) variadic.Finder,
) variadic.Finder {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			tb.Fatalf("the seed supplied through FinderSeed failed: %v", err)
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// dropped reports whether a path was declined through FinderWithout.
//
// Named rather than inlined because the drop set is read from two places: here,
// and by whatever registered through the seam — which reports under paths this
// file has never heard of and must answer the same question about them.
func (c *finderConfig) declined(path string) bool {
	_, ok := c.without[path]
	return ok
}

// finderPaths is every path this file reports a check under.
//
// The set a FinderWithout argument has to be a member of. Declared
// rather than observed: a check that did not run is not a check that does not
// exist — an integration-only method skips without ever consulting the drop
// set, and reading that as a phantom would fail a correct suite on a machine
// with the environment unset.
//
//nolint:gochecknoglobals // the emitted check paths, read-only after init.
var finderPaths = map[string]struct{}{}

// phantoms names every FinderWithout path that declines nothing.
//
// A drop that drops nothing is this option's silent half: the consumer wrote
// it against a check since renamed, or never emitted for that method at all,
// and every run after reads green while asserting one thing more than its
// author believes. Extensions carry their own names — the seam reports under
// paths this file has never heard of — so they count as known too.
func (c *finderConfig) phantoms() []string {
	known := func(p string) bool {
		if _, ok := finderPaths[p]; ok {
			return true
		}
		for _, e := range c.extensions {
			if e.name == p {
				return true
			}
		}
		for _, on := range c.onFind {
			if string(suite.MethodID(finderFind, on.name)) == p {
				return true
			}
		}
		for _, on := range c.onFindWithLimit {
			if string(suite.MethodID(finderFindWithLimit, on.name)) == p {
				return true
			}
		}
		return false
	}
	var out []string
	for p := range c.without {
		if !known(p) {
			out = append(out, p)
		}
	}
	slices.Sort(out)
	return out
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *finderConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if c.declined(path) {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through FinderWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance 754cd5b2c7c03e51630d4e4de333fce7beeeeb498f9d68313c000bc9bd4ee094
