// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/mutator/iface.go
// Plugins:   golang 1.0.0, suite 1.13.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package mutatortest

import (
	"context"
	"slices"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/mutator"
)

// MutatorTouchCheck is one assertion about Touch.
//
// Every generated check for Touch is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type MutatorTouchCheck func(tb testing.TB, subject mutator.Mutator, key string)

// MutatorFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through MutatorWithFixture
// and the check a consumer writes has something to use.
type MutatorFixture struct {
	Key      string
	KeyOther string
}

// DefaultMutatorFixture is what this run derived. Replace any field through
// MutatorWithFixture; the rest keep these values.
func DefaultMutatorFixture() MutatorFixture {
	return MutatorFixture{
		Key:      "test-key",
		KeyOther: "other-key",
	}
}

// AssertMutatorContract runs every generated check against every declared subject.
//
//	Checks:   2 across 1 method, per subject
//	Subjects: declare each with MutatorSubject
//	Double:   every subject runs a second time wrapped in MutatorStub, so
//	          anything the wrapper fails that the subject passes is the double
//	          lying. MutatorWithoutDouble declines it.
//	Extend:   MutatorOnTouch
//	Drop:     MutatorWithout, by the path each check reports under
//	Unseeded: every check here runs against a fresh subject, because
//	          no method here is classified as a write.
//	          A read over an empty subject cannot tell a miss from a bug;
//	          MutatorSeed is what closes it.
//
// # What this file does not check
//
// The interface declares these and nothing here asserts them. Each is statable
// against a subject you can build, so the check is yours to write:
//
//   - mutator, on Touch — write it with MutatorOnTouch
func AssertMutatorContract(t *testing.T, opts ...MutatorOption) {
	t.Helper()
	cfg := newMutatorConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertMutatorContract was given no subject; declare one with " +
			"MutatorSubject(name, factory)")
	}
	for _, p := range cfg.phantoms() {
		t.Errorf("MutatorWithout(%q) declines nothing: no check here reports "+
			"under that path, so this suite asserts one thing more than its "+
			"author believes", p)
	}
	for _, s := range cfg.subjects {
		runMutatorChecks(t, cfg, s.name, s.factory, nil)
		if !cfg.withoutDouble {
			runMutatorChecks(t, cfg, s.name+" through the double", s.factory,
				func(tb testing.TB, subject mutator.Mutator) mutator.Mutator {
					return NewMutatorStub(tb, MutatorStubDelegateTo(subject))
				})
		}
	}
}

// runMutatorChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runMutatorChecks(
	t *testing.T,
	cfg *mutatorConfig,
	label string,
	factory func() mutator.Mutator,
	wrap func(tb testing.TB, subject mutator.Mutator) mutator.Mutator,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run("Touch", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Touch/smoke", "smoke", func(tb testing.TB) {
				AssertMutatorTouchSmoke(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			cfg.run(t, "Touch/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertMutatorTouchToleratesNilContext(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
			})
			for _, c := range cfg.onTouch {
				cfg.run(t, "Touch"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
				})
			}
		})

		// The extra bodies of checks this run was given, each reporting under its
		// own name and dropped by it.
		//
		// The plain subject only. The wrapped pass exists to prove the double
		// faithful and the per-method checks above already do that, so running one
		// through the wrapper prices the wrapper and says nothing new about the
		// subject.
		if wrap == nil {
			for _, e := range cfg.extensions {
				if cfg.declined(e.name) {
					t.Run(e.name, func(t *testing.T) {
						t.Skipf("dropped through MutatorWithout(%q)", e.name)
					})
					continue
				}
				t.Run(e.name, func(t *testing.T) {
					t.Parallel()
					e.run(t, label, factory, cfg)
				})
			}
		}
	})
}

// AssertMutatorTouchSmoke asserts Touch survives a call with derived inputs.
//
// Fails when: Touch panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertMutatorTouchSmoke(tb testing.TB, subject mutator.Mutator, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Touch panicked on a derived value (%v); supply one it "+
				"accepts through MutatorWithFixture", r)
		}
	}()
	ctx := tb.Context()
	subject.Touch(ctx, key)
}

// AssertMutatorTouchToleratesNilContext asserts Touch does not panic on a nil context.
//
// Fails when: Touch panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertMutatorTouchToleratesNilContext(tb testing.TB, subject mutator.Mutator, key string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Touch panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	subject.Touch(ctx, key)
}

// MutatorOption configures a contract run.
type MutatorOption func(*mutatorConfig)

// MutatorSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func MutatorSubject(name string, factory func() mutator.Mutator) MutatorOption {
	return func(c *mutatorConfig) {
		c.subjects = append(c.subjects, namedMutatorSubject{name, factory})
	}
}

// MutatorWithoutDouble declines the second run through MutatorStub.
//
// The double run proves the stand-in is faithful, and costs a second pass over
// every check. Decline it where the double is not used.
func MutatorWithoutDouble() MutatorOption {
	return func(c *mutatorConfig) { c.withoutDouble = true }
}

// MutatorWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func MutatorWithClock(c clock.Clock) MutatorOption {
	return func(cfg *mutatorConfig) { cfg.clock = c }
}

// MutatorWithFixture replaces the derived inputs.
func MutatorWithFixture(f MutatorFixture) MutatorOption {
	return func(c *mutatorConfig) { c.Fixture = f }
}

// MutatorSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func MutatorSeed(fn func(ctx context.Context, subject mutator.Mutator) error) MutatorOption {
	return func(c *mutatorConfig) {
		c.seed = fn
	}
}

// MutatorOnTouch adds a named check to Touch.
func MutatorOnTouch(name string, fn MutatorTouchCheck) MutatorOption {
	return func(c *mutatorConfig) {
		c.onTouch = append(c.onTouch, namedMutatorTouchCheck{name, fn})
	}
}

// MutatorWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func MutatorWithout(paths ...string) MutatorOption {
	return func(c *mutatorConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedMutatorTouchCheck struct {
	name string
	fn   MutatorTouchCheck
}

type namedMutatorSubject struct {
	name    string
	factory func() mutator.Mutator
}

// mutatorContractExtension is a body of checks a generated sibling adds through an option.
//
// A sibling declares the option and closes over whatever configures it, so
// everything that varies per run is typed and private to the file that owns it
// — this file understands only the name and the call. Nothing arrives except
// through an option, which is what keeps the set fixed before the first subtest
// starts.
type mutatorContractExtension struct {
	// name is the path this reports under, and the one MutatorWithout drops
	// it by. Anything nested beneath it is the extension's own to name.
	name string

	// run takes the factory rather than a subject. One that drives sequences
	// builds a subject per iteration, and one that compares against a reference
	// needs the unseeded subject a factory returns — which
	// mutatorConfig.subject is not.
	//
	// Called once per subject, in parallel, sharing the config. Anything it
	// mutates has to be built inside the call: state captured when the option
	// was declared is state two subjects write at once.
	run func(
		t *testing.T,
		subject string,
		factory func() mutator.Mutator,
		cfg *mutatorConfig,
	)
}

type mutatorConfig struct {
	Fixture       MutatorFixture
	subjects      []namedMutatorSubject
	withoutDouble bool
	clock         clock.Clock
	seed          func(ctx context.Context, subject mutator.Mutator) error
	without       map[string]struct{}
	extensions    []mutatorContractExtension
	onTouch       []namedMutatorTouchCheck
}

func newMutatorConfig(opts ...MutatorOption) *mutatorConfig {
	c := &mutatorConfig{
		Fixture: DefaultMutatorFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *mutatorConfig) subject(
	tb testing.TB,
	factory func() mutator.Mutator,
	wrap func(tb testing.TB, subject mutator.Mutator) mutator.Mutator,
) mutator.Mutator {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			tb.Fatalf("the seed supplied through MutatorSeed failed: %v", err)
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// dropped reports whether a path was declined through MutatorWithout.
//
// Named rather than inlined because the drop set is read from two places: here,
// and by whatever registered through the seam — which reports under paths this
// file has never heard of and must answer the same question about them.
func (c *mutatorConfig) declined(path string) bool {
	_, ok := c.without[path]
	return ok
}

// mutatorPaths is every path this file reports a check under.
//
// The set a MutatorWithout argument has to be a member of. Declared
// rather than observed: a check that did not run is not a check that does not
// exist — an integration-only method skips without ever consulting the drop
// set, and reading that as a phantom would fail a correct suite on a machine
// with the environment unset.
//
//nolint:gochecknoglobals // the emitted check paths, read-only after init.
var mutatorPaths = map[string]struct{}{
	"Touch/smoke":                   {},
	"Touch/tolerates a nil context": {},
}

// phantoms names every MutatorWithout path that declines nothing.
//
// A drop that drops nothing is this option's silent half: the consumer wrote
// it against a check since renamed, or never emitted for that method at all,
// and every run after reads green while asserting one thing more than its
// author believes. Extensions carry their own names — the seam reports under
// paths this file has never heard of — so they count as known too.
func (c *mutatorConfig) phantoms() []string {
	known := func(p string) bool {
		if _, ok := mutatorPaths[p]; ok {
			return true
		}
		for _, e := range c.extensions {
			if e.name == p {
				return true
			}
		}
		for _, on := range c.onTouch {
			if "Touch"+"/"+on.name == p {
				return true
			}
		}
		return false
	}
	var out []string
	for p := range c.without {
		if !known(p) {
			out = append(out, p)
		}
	}
	slices.Sort(out)
	return out
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *mutatorConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if c.declined(path) {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through MutatorWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance c2ff2591b9774013c18bb776423662725d553f04d626210622cf096732efa84f
