// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/lifecycle/iface.go
// Plugins:   golang 1.0.0, suite 1.0.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package lifecycletest

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/lifecycle"
)

// LifecycleCloseCheck is one assertion about Close.
//
// Every generated check for Close is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type LifecycleCloseCheck func(tb testing.TB, subject lifecycle.Lifecycle)

// LifecycleFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through LifecycleWithFixture
// and the check a consumer writes has something to use.
type LifecycleFixture struct {
}

// DefaultLifecycleFixture is what this run derived. Replace any field through
// LifecycleWithFixture; the rest keep these values.
func DefaultLifecycleFixture() LifecycleFixture {
	return LifecycleFixture{}
}

// AssertLifecycleContract runs every generated check against every declared subject.
//
//	Checks:   4 across 1 method, per subject
//	Subjects: declare each with LifecycleSubject
//	Double:   every subject runs a second time wrapped in LifecycleStub, so
//	          anything the wrapper fails that the subject passes is the double
//	          lying. LifecycleWithoutDouble declines it.
//	Extend:   LifecycleOnClose
//	Drop:     LifecycleWithout, by the path each check reports under
//
// # What is checked somewhere else
//
// These need a reference implementation to compare against, which a suite run
// has no way to build. Nothing here asserts them and nothing here should:
//
//   - lifecycle, on Close
//
// //testkit:model on the interface derives that reference, and the
// LifecycleModel option it generates runs them here under "model".
func AssertLifecycleContract(t *testing.T, opts ...LifecycleOption) {
	t.Helper()
	cfg := newLifecycleConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertLifecycleContract was given no subject; declare one with " +
			"LifecycleSubject(name, factory)")
	}
	for _, s := range cfg.subjects {
		runLifecycleChecks(t, cfg, s.name, s.factory, nil)
		if !cfg.withoutDouble {
			runLifecycleChecks(t, cfg, s.name+" through the double", s.factory,
				func(tb testing.TB, subject lifecycle.Lifecycle) lifecycle.Lifecycle {
					return NewLifecycleStub(tb, LifecycleStubDelegateTo(subject))
				})
		}
	}
}

// runLifecycleChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runLifecycleChecks(
	t *testing.T,
	cfg *lifecycleConfig,
	label string,
	factory func() lifecycle.Lifecycle,
	wrap func(tb testing.TB, subject lifecycle.Lifecycle) lifecycle.Lifecycle,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run("Close", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Close/smoke", "smoke", func(tb testing.TB) {
				AssertLifecycleCloseSmoke(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Close/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertLifecycleCloseCancels(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Close/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertLifecycleCloseHonoursDeadline(tb, cfg.subject(tb, factory, wrap))
			})
			cfg.run(t, "Close/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertLifecycleCloseToleratesNilContext(tb, cfg.subject(tb, factory, wrap))
			})
			for _, c := range cfg.onClose {
				cfg.run(t, "Close"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap))
				})
			}
		})

		// The extra bodies of checks this run was given, each reporting under its
		// own name and dropped by it.
		//
		// The plain subject only. The wrapped pass exists to prove the double
		// faithful and the per-method checks above already do that, so running one
		// through the wrapper prices the wrapper and says nothing new about the
		// subject.
		if wrap == nil {
			for _, e := range cfg.extensions {
				if cfg.dropped(e.name) {
					t.Run(e.name, func(t *testing.T) {
						t.Skipf("dropped through LifecycleWithout(%q)", e.name)
					})
					continue
				}
				t.Run(e.name, func(t *testing.T) {
					t.Parallel()
					e.run(t, label, factory, cfg)
				})
			}
		}
	})
}

// AssertLifecycleCloseSmoke asserts Close survives a call with derived inputs.
//
// Fails when: Close panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertLifecycleCloseSmoke(tb testing.TB, subject lifecycle.Lifecycle) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Close panicked on a derived value (%v); supply one it "+
				"accepts through LifecycleWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_ = subject.Close(ctx)
}

// AssertLifecycleCloseCancels asserts Close reports a cancelled context as cancelled.
//
// Fails when: Close returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertLifecycleCloseCancels(tb testing.TB, subject lifecycle.Lifecycle) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	err := subject.Close(ctx)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Close must report a cancelled context as context.Canceled")
}

// AssertLifecycleCloseHonoursDeadline asserts Close reports an expired deadline as exceeded.
//
// Fails when: Close returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertLifecycleCloseHonoursDeadline(tb testing.TB, subject lifecycle.Lifecycle) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	err := subject.Close(ctx)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Close must report an expired deadline as context.DeadlineExceeded")
}

// AssertLifecycleCloseToleratesNilContext asserts Close does not panic on a nil context.
//
// Fails when: Close panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertLifecycleCloseToleratesNilContext(tb testing.TB, subject lifecycle.Lifecycle) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Close panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_ = subject.Close(ctx)
}

// LifecycleOption configures a contract run.
type LifecycleOption func(*lifecycleConfig)

// LifecycleSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func LifecycleSubject(name string, factory func() lifecycle.Lifecycle) LifecycleOption {
	return func(c *lifecycleConfig) {
		c.subjects = append(c.subjects, namedLifecycleSubject{name, factory})
	}
}

// LifecycleWithoutDouble declines the second run through LifecycleStub.
//
// The double run proves the stand-in is faithful, and costs a second pass over
// every check. Decline it where the double is not used.
func LifecycleWithoutDouble() LifecycleOption {
	return func(c *lifecycleConfig) { c.withoutDouble = true }
}

// LifecycleWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func LifecycleWithClock(c clock.Clock) LifecycleOption {
	return func(cfg *lifecycleConfig) { cfg.clock = c }
}

// LifecycleWithFixture replaces the derived inputs.
func LifecycleWithFixture(f LifecycleFixture) LifecycleOption {
	return func(c *lifecycleConfig) { c.Fixture = f }
}

// LifecycleSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func LifecycleSeed(fn func(ctx context.Context, subject lifecycle.Lifecycle) error) LifecycleOption {
	return func(c *lifecycleConfig) {
		c.seed = fn
	}
}

// LifecycleOnClose adds a named check to Close.
func LifecycleOnClose(name string, fn LifecycleCloseCheck) LifecycleOption {
	return func(c *lifecycleConfig) {
		c.onClose = append(c.onClose, namedLifecycleCloseCheck{name, fn})
	}
}

// LifecycleWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func LifecycleWithout(paths ...string) LifecycleOption {
	return func(c *lifecycleConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedLifecycleCloseCheck struct {
	name string
	fn   LifecycleCloseCheck
}

type namedLifecycleSubject struct {
	name    string
	factory func() lifecycle.Lifecycle
}

// lifecycleContractExtension is a body of checks a generated sibling adds through an option.
//
// A sibling declares the option and closes over whatever configures it, so
// everything that varies per run is typed and private to the file that owns it
// — this file understands only the name and the call. Nothing arrives except
// through an option, which is what keeps the set fixed before the first subtest
// starts.
type lifecycleContractExtension struct {
	// name is the path this reports under, and the one LifecycleWithout drops
	// it by. Anything nested beneath it is the extension's own to name.
	name string

	// run takes the factory rather than a subject. One that drives sequences
	// builds a subject per iteration, and one that compares against a reference
	// needs the unseeded subject a factory returns — which
	// lifecycleConfig.subject is not.
	//
	// Called once per subject, in parallel, sharing the config. Anything it
	// mutates has to be built inside the call: state captured when the option
	// was declared is state two subjects write at once.
	run func(
		t *testing.T,
		subject string,
		factory func() lifecycle.Lifecycle,
		cfg *lifecycleConfig,
	)
}

type lifecycleConfig struct {
	Fixture       LifecycleFixture
	subjects      []namedLifecycleSubject
	withoutDouble bool
	clock         clock.Clock
	seed          func(ctx context.Context, subject lifecycle.Lifecycle) error
	without       map[string]struct{}
	extensions    []lifecycleContractExtension
	onClose       []namedLifecycleCloseCheck
}

func newLifecycleConfig(opts ...LifecycleOption) *lifecycleConfig {
	c := &lifecycleConfig{
		Fixture: DefaultLifecycleFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *lifecycleConfig) subject(
	tb testing.TB,
	factory func() lifecycle.Lifecycle,
	wrap func(tb testing.TB, subject lifecycle.Lifecycle) lifecycle.Lifecycle,
) lifecycle.Lifecycle {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			tb.Fatalf("the seed supplied through LifecycleSeed failed: %v", err)
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// dropped reports whether a path was declined through LifecycleWithout.
//
// Named rather than inlined because the drop set is read from two places: here,
// and by whatever registered through the seam — which reports under paths this
// file has never heard of and must answer the same question about them.
func (c *lifecycleConfig) dropped(path string) bool {
	_, ok := c.without[path]
	return ok
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *lifecycleConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if c.dropped(path) {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through LifecycleWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance a5b164229af802c0c04bf8e0e66a4262a453a9f22d2f2a7eb26715fa8c409821
