// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/detector/lifecycle/iface.go
// Plugins:   golang 1.0.0, model 0.26.2, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package lifecycletest

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync/atomic"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/detector/lifecycle"
	"go.thesmos.sh/testkit/engine/model"
	"go.thesmos.sh/testkit/engine/model/action"
	"go.thesmos.sh/testkit/engine/model/law"
)

// LifecycleModel runs random sequences of Lifecycle's methods against every
// subject and a known-good in-memory reference side by side, comparing after
// every call. Pass it to AssertLifecycleContract; it reports under
// "model/twin", and LifecycleWithout("model/twin") declines it.
//
//	Reference: the subject's own factory — no reader/writer pair derives a store,
//	           so a second instance driven identically stands in: twins must
//	           agree, which catches nondeterminism and hidden shared state but
//	           not a subject wrong the same way twice; ref= raises the floor
//	Sequences: Close (lifecycle)
//	Laws:      AUTO-LIFECYCLE-RESPECTS-CONTEXT
//	Not bound:
//	           AUTO-IDEMPOTENT-LIFECYCLE — observes state through no method here — no drain, no aggregate, no keyed read
func LifecycleModel(opts ...LifecycleModelOption) LifecycleOption {
	return func(c *lifecycleConfig) {
		c.extensions = append(c.extensions, lifecycleContractExtension{
			name: "model/twin",
			run: func(t *testing.T, _ string, factory func() lifecycle.Lifecycle, _ *lifecycleConfig) {
				model.Check(t, LifecycleModelProperty(factory, opts...))
			},
		})
	}
}

// LifecycleModelProperty builds the property the option runs — exported because a
// bespoke harness composes from here: model.Check for a test, model.MakeFuzz
// for a coverage-guided fuzz target, both over this one derivation.
func LifecycleModelProperty(factory func() lifecycle.Lifecycle, opts ...LifecycleModelOption) func(*model.T) {
	cfg := newLifecycleModelConfig(opts...)
	reference := cfg.reference
	if reference == nil {
		reference = factory
	}
	// The laws the classifications earned, each reporting under its AUTO-
	// identifier when it fails. Observational: a law never mutates, so running
	// them inside the sequences is safe for every step that follows.
	laws := model.NewRegistry[lifecycle.Lifecycle]()
	laws.Add(law.LifecycleRespectsContext[lifecycle.Lifecycle]{
		Op: func(ctx context.Context, s lifecycle.Lifecycle) error {
			return s.Close(ctx)
		},
	})
	return model.Property(factory,
		model.WithReference(reference),
		model.WithLaws(laws),
		model.WithActions(
			action.Lifecycle("Close",
				func(ctx context.Context, s lifecycle.Lifecycle) error {
					return s.Close(ctx)
				}),
		),
	)
}

// LifecycleModelFuzz hands a subject's sequence space to the
// coverage-guided engine: the fuzzer's bytes replay as rapid's choice
// stream, so mutating them mutates the action ordering and every drawn
// input at once — and the engine's coverage feedback climbs the subject's
// own branches, which is what no fixed seed can do. Wire it from a fuzz
// target beside the subject:
//
//	func FuzzLifecycle(f *testing.F) {
//		LifecycleModelFuzz(f, func() Lifecycle { return NewMine() })
//	}
func LifecycleModelFuzz(f *testing.F, factory func() lifecycle.Lifecycle, opts ...LifecycleModelOption) {
	f.Add([]byte{})
	f.Fuzz(model.MakeFuzz(LifecycleModelProperty(factory, opts...)))
}

// LifecycleModelOption configures the model run.
type LifecycleModelOption func(*lifecycleModelConfig)

// LifecycleModelReference replaces the derived reference — for an
// interface whose semantics outrun its shape.
func LifecycleModelReference(factory func() lifecycle.Lifecycle) LifecycleModelOption {
	return func(c *lifecycleModelConfig) { c.reference = factory }
}

// LifecycleSatWear is one wearable defect: a kind, and the wrap that
// dresses a subject in it.
type lifecycleSatWear struct {
	kind string
	wrap func(fx LifecycleFixture, s lifecycle.Lifecycle) lifecycle.Lifecycle
}

//nolint:gochecknoglobals // the prover's wardrobe, read-only after init.
var lifecycleSatWears = map[string][]lifecycleSatWear{}

//nolint:gochecknoinits // the wardrobe fills once, keyed by method.
func init() { //nolint:staticcheck // an empty wardrobe leaves dress unused by design.
	dress := func(method, kind string, wrap func(fx LifecycleFixture, s lifecycle.Lifecycle) lifecycle.Lifecycle) {
		lifecycleSatWears[method] = append(lifecycleSatWears[method],
			lifecycleSatWear{kind: kind, wrap: wrap})
	}
	dress("Close", "inert", func(_ LifecycleFixture, s lifecycle.Lifecycle) lifecycle.Lifecycle {
		return lifecycleSatInertClose{s}
	})
	dress("Close", "sputter", func(_ LifecycleFixture, s lifecycle.Lifecycle) lifecycle.Lifecycle {
		return &lifecycleSatSputterClose{Lifecycle: s}
	})
}

// LifecycleModelSaturation proves the bound laws can fail: per law, a
// defect is worn on each method the law's closures reach — zeros, the
// fixture pair alternated, a waning count — and at least one worn run must
// fail naming the law's own identifier, with the clean factory standing as
// reference. A law every defect survives is bound but unsaturatable, and
// fails here by name. Pass the same options that arm the tier: a law behind
// an unarmed door or the clocked factory is skipped visibly, never counted.
func LifecycleModelSaturation(t *testing.T, factory func() lifecycle.Lifecycle, opts ...LifecycleModelOption) {
	t.Helper()
	cfg := newLifecycleModelConfig(opts...)
	_ = cfg
	fx := DefaultLifecycleFixture()
	_ = fx
	t.Run("AUTO-LIFECYCLE-RESPECTS-CONTEXT", func(t *testing.T) {
		killed := func() bool {
			for _, method := range []string{"Close"} {
				for _, wear := range lifecycleSatWears[method] {
					surrogate := "LifecycleSat_AUTO-LIFECYCLE-RESPECTS-CONTEXT_" + method + "_" + wear.kind
					t.Cleanup(func() {
						_ = os.RemoveAll(filepath.Join("testdata", "rapid", surrogate))
						_ = os.Remove(filepath.Join(
							model.ResolveArtifactDir(""), "failure-"+surrogate+".json"))
					})
					f := testkit.NewFailableTB().WithName(surrogate)
					worn := append(slices.Clone(opts),
						LifecycleModelReference(factory))
					model.Check(f, LifecycleModelProperty(func() lifecycle.Lifecycle {
						return wear.wrap(fx, factory())
					}, worn...))
					if f.Failed() && (strings.Contains(f.Msg(), "AUTO-LIFECYCLE-RESPECTS-CONTEXT")) {
						return true
					}
				}
			}
			return false
		}()
		if !killed {
			t.Errorf("AUTO-LIFECYCLE-RESPECTS-CONTEXT survived every defect worn on its own methods — bound but unsaturatable")
		}
	})
}

// lifecycleSatInertClose answers zeros where Close should act.
type lifecycleSatInertClose struct{ lifecycle.Lifecycle }

func (lifecycleSatInertClose) Close(_ context.Context) (z0 error) {
	return
}

// lifecycleSatSputterClose alternates a minted refusal
// with the real answer where Close should be steady.
type lifecycleSatSputterClose struct {
	lifecycle.Lifecycle
	flip atomic.Int64
}

func (m *lifecycleSatSputterClose) Close(p0 context.Context) (z0 error) {
	if m.flip.Add(1)%2 == 1 {
		z0 = errors.New("lifecycletest: saturation sputtered a refusal")
		return
	}
	return m.Lifecycle.Close(p0)
}

type lifecycleModelConfig struct {
	reference func() lifecycle.Lifecycle
}

func newLifecycleModelConfig(opts ...LifecycleModelOption) *lifecycleModelConfig {
	c := &lifecycleModelConfig{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// testkit: end of generated content.
// testkit:provenance fd04c547ee8bbb7a866fcc8a12a3db72f21e0c9a0c9375c3544a15453dbd4936
