// Code generated by testkit. DO NOT EDIT.
//
// Source:    conformance/corpus/iface/mixin/validates/iface.go
// Plugins:   golang 1.0.0, suite 1.16.0, backend.golang 1.0.0
// Command:   testkit run ./conformance/corpus/...

package validatestest

import (
	"context"
	"slices"
	"testing"

	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/validates"
	"go.thesmos.sh/testkit/engine/suite"
)

// MixedStoreCheck is one assertion about Store.
//
// Every generated check for Store is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type MixedStoreCheck func(tb testing.TB, subject validates.Mixed, v validates.Payload)

// MixedValidateCheck is one assertion about Validate.
//
// Every generated check for Validate is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type MixedValidateCheck func(tb testing.TB, subject validates.Mixed, v validates.Payload)

// MixedReadCheck is one assertion about Read.
//
// Every generated check for Read is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type MixedReadCheck func(tb testing.TB, subject validates.Mixed, key string)

// MixedFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through MixedWithFixture
// and the check a consumer writes has something to use.
type MixedFixture struct {
	Payload      validates.Payload
	PayloadOther validates.Payload
	Key          string
	KeyOther     string
}

// DefaultMixedFixture is what this run derived. Replace any field through
// MixedWithFixture; the rest keep these values.
func DefaultMixedFixture() MixedFixture {
	return MixedFixture{
		Payload:      validates.Payload{Key: "test-key", Body: "test-body"},
		PayloadOther: validates.Payload{Key: "other-key", Body: "other-body"},
		Key:          "test-key",
		KeyOther:     "other-key",
	}
}

// Mixed is the witnessed instantiation.
//
// A generic interface aliases with its own parameters, which Go admits
// since 1.24 — so every declaration below names Mixed and
// the arguments follow, exactly as they do for a concrete one.
type Mixed = validates.Mixed

// MixedRunOpt is one thing you can pass to RunMixed.
type MixedRunOpt interface {
	applyTo(*mixedRunConfig)
}

type mixedRunConfig struct {
	suite.Bundle[Mixed]
}

// MixedHarness declares one Mixed implementation under test.
type MixedHarness[T Mixed] struct {
	Name string

	// Exactly one constructor.
	New   func() T
	Start func(tb testing.TB) T

	// Excuse lists checks this subject structurally cannot take.
	Excuse []suite.ID

	// Oracle marks this subject as the run's reference. At most one.
	Oracle bool

	// Serial keeps this subject out of the parallel group.
	Serial bool

	// Provide answers open capabilities beyond the named fields — the
	// doors only this interface's checks know. The runner's gate reads
	// it for any capability without a dedicated field.
	Provide map[suite.Capability]any
}

// Subject lowers the declaration into what the runner consumes.
func (h MixedHarness[T]) Subject() (suite.Subject[Mixed], error) {
	build, err := suite.OneCtor(h.Name, h.New, h.Start)
	if err != nil {
		return suite.Subject[Mixed]{}, err
	}
	return suite.Subject[Mixed]{
		Name:     h.Name,
		Provides: h.Provide,
		New:      func(tb testing.TB) Mixed { return build(tb) },
		Oracle:   h.Oracle,
		Serial:   h.Serial,
		Excused:  suite.ExcuseSet(h.Excuse),
	}, nil
}

func (h MixedHarness[T]) applyTo(rc *mixedRunConfig) {
	rc.AddSubject(h.Subject())
}

type mixedDropOpt []suite.ID

func (d mixedDropOpt) applyTo(rc *mixedRunConfig) {
	rc.AddDrops(d...)
}

// mixedWithout drops checks by identity.
func mixedWithout(ids ...suite.ID) MixedRunOpt {
	return mixedDropOpt(ids)
}

// --- The veneer -------------------------------------------------------------

// MixedSuite is the entry a consumer names checks through.
var MixedSuite = mixedVeneer{Checks: mixedCheckIndex}

type mixedVeneer struct {
	// Checks is the check index — the constants a Without call is
	// written against.
	Checks mixedCheckIndexT
}

// Without drops a check by ID.
func (mixedVeneer) Without(ids ...suite.ID) MixedRunOpt {
	return mixedWithout(ids...)
}

// --- Drop hints -------------------------------------------------------------

// mixedIndexPath spells every emitted ID as the path a
// consumer would write to drop it, so a run that declines something can
// say what to type rather than what failed.
var mixedIndexPath = map[suite.ID]string{
	mixedCheckIndex.Store.Smoke():      "MixedSuite.Checks.Store.Smoke()",
	mixedCheckIndex.Store.Cancels():    "MixedSuite.Checks.Store.Cancels()",
	mixedCheckIndex.Store.NilContext(): "MixedSuite.Checks.Store.NilContext()",
	mixedCheckIndex.Store.Deadline():   "MixedSuite.Checks.Store.Deadline()",
	mixedCheckIndex.Validate.Smoke():   "MixedSuite.Checks.Validate.Smoke()",
	mixedCheckIndex.Read.Smoke():       "MixedSuite.Checks.Read.Smoke()",
	mixedCheckIndex.Read.Cancels():     "MixedSuite.Checks.Read.Cancels()",
	mixedCheckIndex.Read.NilContext():  "MixedSuite.Checks.Read.NilContext()",
	mixedCheckIndex.Read.Deadline():    "MixedSuite.Checks.Read.Deadline()",
	mixedCheckIndex.Read.ZeroOnError(): "MixedSuite.Checks.Read.ZeroOnError()",
	mixedCheckIndex.Read.Miss():        "MixedSuite.Checks.Read.Miss()",
	mixedCheckIndex.Model.Laws():       "MixedSuite.Checks.Model.Laws()",
	mixedCheckIndex.Model.Agrees():     "MixedSuite.Checks.Model.Agrees()",
}

var mixedDropHint = suite.DropHinter(
	"MixedSuite", mixedIndexPath,
)

// The names this file spells more than once: one home each.
const (
	mixedStore    = "Store"
	mixedValidate = "Validate"
	mixedRead     = "Read"

	// The interface's word inside a family-scoped identity.
	mixedQualifier = "mixed"
)

// mixedCheckIndex indexes every check this package emits, by
// method and then by check.
var mixedCheckIndex = mixedCheckIndexT{
	Store:    mixedStoreChecks{},
	Validate: mixedValidateChecks{},
	Read:     mixedReadChecks{},
	Model:    mixedModelChecks{},
}

type mixedCheckIndexT struct {
	Store    mixedStoreChecks
	Validate mixedValidateChecks
	Read     mixedReadChecks
	Model    mixedModelChecks
}

// All returns every ID this package emits.
func (mixedCheckIndexT) All() []suite.ID {
	var out []suite.ID
	out = append(out, mixedStoreChecks{}.All()...)
	out = append(out, mixedValidateChecks{}.All()...)
	out = append(out, mixedReadChecks{}.All()...)
	out = append(out, mixedModelChecks{}.All()...)
	return out
}

type mixedStoreChecks struct{}

func (mixedStoreChecks) Smoke() suite.ID {
	return suite.MethodID(mixedStore, suite.SegSmoke)
}

func (mixedStoreChecks) Cancels() suite.ID {
	return suite.MethodID(mixedStore, suite.SegCancel)
}

func (mixedStoreChecks) NilContext() suite.ID {
	return suite.MethodID(mixedStore, suite.SegNilContext)
}

func (mixedStoreChecks) Deadline() suite.ID {
	return suite.MethodID(mixedStore, suite.SegDeadline)
}

func (mixedStoreChecks) All() []suite.ID {
	return []suite.ID{
		mixedStoreChecks{}.Smoke(),
		mixedStoreChecks{}.Cancels(),
		mixedStoreChecks{}.NilContext(),
		mixedStoreChecks{}.Deadline(),
	}
}

type mixedValidateChecks struct{}

func (mixedValidateChecks) Smoke() suite.ID {
	return suite.MethodID(mixedValidate, suite.SegSmoke)
}

func (mixedValidateChecks) All() []suite.ID {
	return []suite.ID{
		mixedValidateChecks{}.Smoke(),
	}
}

type mixedReadChecks struct{}

func (mixedReadChecks) Smoke() suite.ID {
	return suite.MethodID(mixedRead, suite.SegSmoke)
}

func (mixedReadChecks) Cancels() suite.ID {
	return suite.MethodID(mixedRead, suite.SegCancel)
}

func (mixedReadChecks) NilContext() suite.ID {
	return suite.MethodID(mixedRead, suite.SegNilContext)
}

func (mixedReadChecks) Deadline() suite.ID {
	return suite.MethodID(mixedRead, suite.SegDeadline)
}

func (mixedReadChecks) ZeroOnError() suite.ID {
	return suite.MethodID(mixedRead, suite.SegZeroValue)
}

func (mixedReadChecks) Miss() suite.ID {
	return suite.MethodID(mixedRead, suite.SegMiss)
}

func (mixedReadChecks) All() []suite.ID {
	return []suite.ID{
		mixedReadChecks{}.Smoke(),
		mixedReadChecks{}.Cancels(),
		mixedReadChecks{}.NilContext(),
		mixedReadChecks{}.Deadline(),
		mixedReadChecks{}.ZeroOnError(),
		mixedReadChecks{}.Miss(),
	}
}

type mixedModelChecks struct{}

func (mixedModelChecks) Laws() suite.ID {
	return suite.FamilyID(suite.FamilyModel, mixedQualifier, suite.SegLaws)
}

func (mixedModelChecks) Agrees() suite.ID {
	return suite.FamilyID(suite.FamilyModel, mixedQualifier, suite.SegDifferential)
}

func (mixedModelChecks) All() []suite.ID {
	return []suite.ID{
		mixedModelChecks{}.Laws(),
		mixedModelChecks{}.Agrees(),
	}
}

// mixedSignatureChecks builds every check this run derived.
//
// sig is the one shape they share; the literals below state only what
// differs. Falsifiable is Proven wherever a defect rule reached the
// claim, which the parity gate refuses to stamp without one.
func mixedSignatureChecks(fx MixedFixture) []suite.Check[Mixed] {
	sig := suite.ProvenCheck[Mixed]
	ix := mixedCheckIndex
	return []suite.Check[Mixed]{
		sig(ix.Store.Smoke(), suite.ClassSmoke,
			"Store survives a call with a derived payload",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreSmoke(tb, m, fx)
			}),
		sig(ix.Store.Cancels(), suite.ClassCancel,
			"Store reports a cancelled context as cancelled",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreCancels(tb, m, fx)
			}),
		sig(ix.Store.NilContext(), suite.ClassNilContext,
			"Store returns an error rather than panicking on a nil context",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreToleratesNilContext(tb, m, fx)
			}),
		sig(ix.Store.Deadline(), suite.ClassDeadline,
			"Store reports an expired deadline as exceeded",
			func(tb testing.TB, m Mixed) {
				mixedAssertStoreHonoursDeadline(tb, m, fx)
			}),
		sig(ix.Validate.Smoke(), suite.ClassSmoke,
			"Validate survives a call with a derived payload",
			func(tb testing.TB, m Mixed) {
				mixedAssertValidateSmoke(tb, m, fx)
			}),
		sig(ix.Read.Smoke(), suite.ClassSmoke,
			"Read survives a call with a derived key",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadSmoke(tb, m, fx)
			}),
		sig(ix.Read.Cancels(), suite.ClassCancel,
			"Read reports a cancelled context as cancelled",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadCancels(tb, m, fx)
			}),
		sig(ix.Read.NilContext(), suite.ClassNilContext,
			"Read returns an error rather than panicking on a nil context",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadToleratesNilContext(tb, m, fx)
			}),
		sig(ix.Read.Deadline(), suite.ClassDeadline,
			"Read reports an expired deadline as exceeded",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadHonoursDeadline(tb, m, fx)
			}),
		sig(ix.Read.ZeroOnError(), suite.ClassZeroValue,
			"Read returns the zero Payload alongside any error",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadZeroOnError(tb, m, fx)
			}),
		sig(ix.Read.Miss(), suite.ClassReader,
			"Read reports zero for a key nothing has written",
			func(tb testing.TB, m Mixed) {
				mixedAssertReadMiss(tb, m, fx)
			}),
	}
}

// mixedAssertStoreSmoke asserts Store survives a call with a derived payload.
func mixedAssertStoreSmoke(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.Survives(tb, mixedStore, func(ctx context.Context) {
		_ = m.Store(ctx, fx.Payload)
	})
}

// mixedAssertStoreCancels asserts Store reports a cancelled context as cancelled.
func mixedAssertStoreCancels(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, mixedStore, func(ctx context.Context) error {
		return m.Store(ctx, fx.Payload)
	})
}

// mixedAssertStoreToleratesNilContext asserts Store returns an error rather than panicking on a nil context.
func mixedAssertStoreToleratesNilContext(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, mixedStore, func(ctx context.Context) error {
		return m.Store(ctx, fx.Payload)
	})
}

// mixedAssertStoreHonoursDeadline asserts Store reports an expired deadline as exceeded.
func mixedAssertStoreHonoursDeadline(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, mixedStore, func(ctx context.Context) error {
		return m.Store(ctx, fx.Payload)
	})
}

// mixedAssertValidateSmoke asserts Validate survives a call with a derived payload.
func mixedAssertValidateSmoke(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.Survives(tb, mixedValidate, func(ctx context.Context) {
		_ = m.Validate(fx.Payload)
	})
}

// mixedAssertReadSmoke asserts Read survives a call with a derived key.
func mixedAssertReadSmoke(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.Survives(tb, mixedRead, func(ctx context.Context) {
		_, _ = m.Read(ctx, fx.Key)
	})
}

// mixedAssertReadCancels asserts Read reports a cancelled context as cancelled.
func mixedAssertReadCancels(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsCancelled(tb, mixedRead, func(ctx context.Context) error {
		_, err := m.Read(ctx, fx.Key)
		return err
	})
}

// mixedAssertReadToleratesNilContext asserts Read returns an error rather than panicking on a nil context.
func mixedAssertReadToleratesNilContext(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ToleratesNilContext(tb, mixedRead, func(ctx context.Context) error {
		_, err := m.Read(ctx, fx.Key)
		return err
	})
}

// mixedAssertReadHonoursDeadline asserts Read reports an expired deadline as exceeded.
func mixedAssertReadHonoursDeadline(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	suite.ReportsDeadlineExceeded(tb, mixedRead, func(ctx context.Context) error {
		_, err := m.Read(ctx, fx.Key)
		return err
	})
}

// mixedAssertReadZeroOnError asserts Read returns the zero Payload alongside any error.
func mixedAssertReadZeroOnError(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	got, err := m.Read(ctx, fx.Key)
	if err == nil {
		tb.Skip("Read answered for a cancelled context, so this check has no error to inspect")
	}

	var zero validates.Payload
	if got != zero {
		tb.Errorf("Read must return the zero value alongside an error: got %+v, want %+v (err %v)",
			got, zero, err)
	}
}

// mixedAssertReadMiss asserts Read reports zero for a key nothing has written.
func mixedAssertReadMiss(
	tb testing.TB,
	m Mixed,
	fx MixedFixture,
) {
	tb.Helper()
	ctx := tb.Context()

	got, err := m.Read(ctx, fx.KeyOther)
	if err != nil {
		tb.Fatalf("Read for an input nothing supplied must answer: %v", err)
	}

	var zero validates.Payload
	if got != zero {
		tb.Errorf("Read must return the zero value alongside an error: got %+v, want %+v (err %v)",
			got, zero, err)
	}
}

// AssertMixedContract runs every generated check against every declared subject.
//
//	Subjects: declare each with MixedSubject
//	Extend:   MixedOnStore, MixedOnValidate, MixedOnRead
//	Drop:     MixedWithout, by the path each check reports under
func AssertMixedContract(t *testing.T, opts ...MixedOption) {
	t.Helper()
	cfg := newMixedConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertMixedContract was given no subject; declare one with " +
			"MixedSubject(name, factory)")
	}
	for _, p := range cfg.phantoms() {
		t.Errorf("MixedWithout(%q) declines nothing: no check here reports "+
			"under that path, so this suite asserts one thing more than its "+
			"author believes", p)
	}
	for _, s := range cfg.subjects {
		runMixedChecks(t, cfg, s.name, s.factory, nil)
	}
}

// runMixedChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runMixedChecks(
	t *testing.T,
	cfg *mixedConfig,
	label string,
	factory func() validates.Mixed,
	wrap func(tb testing.TB, subject validates.Mixed) validates.Mixed,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run(mixedStore, func(t *testing.T) {
			t.Parallel()

			for _, c := range cfg.onStore {
				cfg.run(t, string(suite.MethodID(mixedStore, c.name)), c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Payload)
				})
			}
		})

		t.Run(mixedValidate, func(t *testing.T) {
			t.Parallel()

			for _, c := range cfg.onValidate {
				cfg.run(t, string(suite.MethodID(mixedValidate, c.name)), c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Payload)
				})
			}
		})

		t.Run(mixedRead, func(t *testing.T) {
			t.Parallel()

			for _, c := range cfg.onRead {
				cfg.run(t, string(suite.MethodID(mixedRead, c.name)), c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.Key)
				})
			}
		})

		// The extra bodies of checks this run was given, each reporting under its
		// own name and dropped by it.
		//
		// The plain subject only. The wrapped pass exists to prove the double
		// faithful and the per-method checks above already do that, so running one
		// through the wrapper prices the wrapper and says nothing new about the
		// subject.
		if wrap == nil {
			for _, e := range cfg.extensions {
				if cfg.declined(e.name) {
					t.Run(e.name, func(t *testing.T) {
						t.Skipf("dropped through MixedWithout(%q)", e.name)
					})
					continue
				}
				t.Run(e.name, func(t *testing.T) {
					t.Parallel()
					e.run(t, label, factory, cfg)
				})
			}
		}
	})
}

// MixedOption configures a contract run.
type MixedOption func(*mixedConfig)

// MixedSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func MixedSubject(name string, factory func() validates.Mixed) MixedOption {
	return func(c *mixedConfig) {
		c.subjects = append(c.subjects, namedMixedSubject{name, factory})
	}
}

// MixedWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func MixedWithClock(c clock.Clock) MixedOption {
	return func(cfg *mixedConfig) { cfg.clock = c }
}

// MixedWithFixture replaces the derived inputs.
func MixedWithFixture(f MixedFixture) MixedOption {
	return func(c *mixedConfig) { c.Fixture = f }
}

// MixedSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func MixedSeed(fn func(ctx context.Context, subject validates.Mixed) error) MixedOption {
	return func(c *mixedConfig) {
		c.seed = fn
		c.seedIsDerived = false
	}
}

// MixedOnStore adds a named check to Store.
func MixedOnStore(name string, fn MixedStoreCheck) MixedOption {
	return func(c *mixedConfig) {
		c.onStore = append(c.onStore, namedMixedStoreCheck{name, fn})
	}
}

// MixedOnValidate adds a named check to Validate.
func MixedOnValidate(name string, fn MixedValidateCheck) MixedOption {
	return func(c *mixedConfig) {
		c.onValidate = append(c.onValidate, namedMixedValidateCheck{name, fn})
	}
}

// MixedOnRead adds a named check to Read.
func MixedOnRead(name string, fn MixedReadCheck) MixedOption {
	return func(c *mixedConfig) {
		c.onRead = append(c.onRead, namedMixedReadCheck{name, fn})
	}
}

// MixedWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func MixedWithout(paths ...string) MixedOption {
	return func(c *mixedConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedMixedStoreCheck struct {
	name string
	fn   MixedStoreCheck
}

type namedMixedValidateCheck struct {
	name string
	fn   MixedValidateCheck
}

type namedMixedReadCheck struct {
	name string
	fn   MixedReadCheck
}

type namedMixedSubject struct {
	name    string
	factory func() validates.Mixed
}

// mixedContractExtension is a body of checks a generated sibling adds through an option.
//
// A sibling declares the option and closes over whatever configures it, so
// everything that varies per run is typed and private to the file that owns it
// — this file understands only the name and the call. Nothing arrives except
// through an option, which is what keeps the set fixed before the first subtest
// starts.
type mixedContractExtension struct {
	// name is the path this reports under, and the one MixedWithout drops
	// it by. Anything nested beneath it is the extension's own to name.
	name string

	// run takes the factory rather than a subject. One that drives sequences
	// builds a subject per iteration, and one that compares against a reference
	// needs the unseeded subject a factory returns — which
	// mixedConfig.subject is not.
	//
	// Called once per subject, in parallel, sharing the config. Anything it
	// mutates has to be built inside the call: state captured when the option
	// was declared is state two subjects write at once.
	run func(
		t *testing.T,
		subject string,
		factory func() validates.Mixed,
		cfg *mixedConfig,
	)
}

type mixedConfig struct {
	Fixture  MixedFixture
	subjects []namedMixedSubject
	clock    clock.Clock
	seed     func(ctx context.Context, subject validates.Mixed) error
	// seedIsDerived is what lets a failed seed name the right culprit. The
	// derived seed and a consumer's are the same field, and the advice for one
	// is useless for the other.
	seedIsDerived bool
	without       map[string]struct{}
	extensions    []mixedContractExtension
	onStore       []namedMixedStoreCheck
	onValidate    []namedMixedValidateCheck
	onRead        []namedMixedReadCheck
}

func newMixedConfig(opts ...MixedOption) *mixedConfig {
	c := &mixedConfig{
		Fixture: DefaultMixedFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	// Derived: Store is classified writer, so the interface
	// populates itself and a reader has something to read.
	c.seed = func(ctx context.Context, subject validates.Mixed) error {
		return subject.Store(ctx, c.Fixture.Payload)
	}
	c.seedIsDerived = true
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *mixedConfig) subject(
	tb testing.TB,
	factory func() validates.Mixed,
	wrap func(tb testing.TB, subject validates.Mixed) validates.Mixed,
) validates.Mixed {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			if c.seedIsDerived {
				tb.Fatalf("seeding through Store failed: %v; "+
					"supply a value it accepts through MixedWithFixture, or a "+
					"whole seed through MixedSeed", err)
			} else {
				tb.Fatalf("the seed supplied through MixedSeed failed: %v", err)
			}
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// dropped reports whether a path was declined through MixedWithout.
//
// Named rather than inlined because the drop set is read from two places: here,
// and by whatever registered through the seam — which reports under paths this
// file has never heard of and must answer the same question about them.
func (c *mixedConfig) declined(path string) bool {
	_, ok := c.without[path]
	return ok
}

// mixedPaths is every path this file reports a check under.
//
// The set a MixedWithout argument has to be a member of. Declared
// rather than observed: a check that did not run is not a check that does not
// exist — an integration-only method skips without ever consulting the drop
// set, and reading that as a phantom would fail a correct suite on a machine
// with the environment unset.
//
//nolint:gochecknoglobals // the emitted check paths, read-only after init.
var mixedPaths = map[string]struct{}{}

// phantoms names every MixedWithout path that declines nothing.
//
// A drop that drops nothing is this option's silent half: the consumer wrote
// it against a check since renamed, or never emitted for that method at all,
// and every run after reads green while asserting one thing more than its
// author believes. Extensions carry their own names — the seam reports under
// paths this file has never heard of — so they count as known too.
func (c *mixedConfig) phantoms() []string {
	known := func(p string) bool {
		if _, ok := mixedPaths[p]; ok {
			return true
		}
		for _, e := range c.extensions {
			if e.name == p {
				return true
			}
		}
		for _, on := range c.onStore {
			if string(suite.MethodID(mixedStore, on.name)) == p {
				return true
			}
		}
		for _, on := range c.onValidate {
			if string(suite.MethodID(mixedValidate, on.name)) == p {
				return true
			}
		}
		for _, on := range c.onRead {
			if string(suite.MethodID(mixedRead, on.name)) == p {
				return true
			}
		}
		return false
	}
	var out []string
	for p := range c.without {
		if !known(p) {
			out = append(out, p)
		}
	}
	slices.Sort(out)
	return out
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *mixedConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if c.declined(path) {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through MixedWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance 9db781201686be57fd0ebc4ef76d6215bec1fbd1e3b88a529a44034c8c8d3a52
