// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/cache/iface.go
// Plugins:   golang 1.0.0, suite 1.0.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package cachetest_test

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/cache"
	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/cache/cachetest"
)

// Every generated check for Contract, driven against a stand-in built
// to violate it.
//
//	Proved:   10 checks
//
// Each guard asserts the *reason* the check rejected, not merely that it did. A
// stand-in that failed for some unrelated reason — a nil map, a closed channel
// — would satisfy a guard reading only the fact, which is the vacuity this file
// exists to catch, one level up.

// TestAssertContractLookupSmokeCanFail holds AssertContractLookupSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertContractLookupSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractLookup(func(context.Context, string) (cache.Value, error) {
			panic("Contract.Lookup: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractLookupSmoke(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertContractLookupCancelsCanFail holds AssertContractLookupCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertContractLookupCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractLookup(func(context.Context, string) (cache.Value, error) {
			var r0 cache.Value
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractLookupCancels(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("must report a cancelled context",
		"and rejects it for the reason the check is about")
}

// TestAssertContractLookupHonoursDeadlineCanFail holds AssertContractLookupHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertContractLookupHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractLookup(func(context.Context, string) (cache.Value, error) {
			var r0 cache.Value
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractLookupHonoursDeadline(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("must report an expired deadline",
		"and rejects it for the reason the check is about")
}

// TestAssertContractLookupToleratesNilContextCanFail holds AssertContractLookupToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertContractLookupToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractLookup(func(context.Context, string) (cache.Value, error) {
			panic("Contract.Lookup: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractLookupToleratesNilContext(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// TestAssertContractLookupZeroOnErrorCanFail holds AssertContractLookupZeroOnError to being able to fail.
//
// The stand-in succeeds for the input the check chose so it would miss. A check
// that let that pass would never reach the comparison it exists to make, and
// would report success without having compared anything.
func TestAssertContractLookupZeroOnErrorCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractLookup(func(context.Context, string) (cache.Value, error) {
			var r0 cache.Value
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that succeeds for an input it should miss",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractLookupZeroOnError(tb, subject, fixture.KeyOther)
		})
	testkit.Assert(t, got).Contains("supply inputs it misses",
		"and rejects it for the reason the check is about")
}

// TestAssertContractFetchSmokeCanFail holds AssertContractFetchSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertContractFetchSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractFetch(func(context.Context, string) (cache.Value, error) {
			panic("Contract.Fetch: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractFetchSmoke(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertContractFetchCancelsCanFail holds AssertContractFetchCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertContractFetchCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractFetch(func(context.Context, string) (cache.Value, error) {
			var r0 cache.Value
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractFetchCancels(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("must report a cancelled context",
		"and rejects it for the reason the check is about")
}

// TestAssertContractFetchHonoursDeadlineCanFail holds AssertContractFetchHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertContractFetchHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractFetch(func(context.Context, string) (cache.Value, error) {
			var r0 cache.Value
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractFetchHonoursDeadline(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("must report an expired deadline",
		"and rejects it for the reason the check is about")
}

// TestAssertContractFetchToleratesNilContextCanFail holds AssertContractFetchToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertContractFetchToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractFetch(func(context.Context, string) (cache.Value, error) {
			panic("Contract.Fetch: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractFetchToleratesNilContext(tb, subject, fixture.Key)
		})
	testkit.Assert(t, got).Contains("panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// TestAssertContractFetchZeroOnErrorCanFail holds AssertContractFetchZeroOnError to being able to fail.
//
// The stand-in succeeds for the input the check chose so it would miss. A check
// that let that pass would never reach the comparison it exists to make, and
// would report success without having compared anything.
func TestAssertContractFetchZeroOnErrorCanFail(t *testing.T) {
	t.Parallel()

	fixture := cachetest.DefaultContractFixture()
	subject := cachetest.NewContractStub(t,
		cachetest.WithContractFetch(func(context.Context, string) (cache.Value, error) {
			var r0 cache.Value
			return r0, nil
		}))

	got := testkit.Rejects(t, "a method that succeeds for an input it should miss",
		func(tb testing.TB) {
			tb.Helper()
			cachetest.AssertContractFetchZeroOnError(tb, subject, fixture.KeyOther)
		})
	testkit.Assert(t, got).Contains("supply inputs it misses",
		"and rejects it for the reason the check is about")
}

// testkit: end of generated content.
// testkit:provenance 9ea0d0d720f9f6f36abdccdd73939ec3c743b7065d0e74baa3e2636368fb7362
