// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/contract/updater/iface.go
// Plugins:   golang 1.0.0, model 0.5.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package updatertest_test

import (
	"testing"

	"go.thesmos.sh/testkit/conformance/corpus/iface/contract/updater/updatertest"
	"go.thesmos.sh/testkit/engine/model"
)

// TestContractModelReference holds the reference to the tier it
// anchors: two independent instances driven through the full property, one as
// subject and one as oracle. A failure here is the derivation's own — before
// any consumer's implementation is in the room.
//
// The supplied-option path rides along, so the option, the config and the
// constructor are all exercised by the file that ships them.
func TestContractModelReference(t *testing.T) {
	t.Parallel()
	model.Check(t, updatertest.ContractModelProperty(
		updatertest.NewContractModelReference,
		updatertest.ContractModelReference(updatertest.NewContractModelReference),
	))
}

// TestContractModelConcurrent holds the linearizability leg to the
// derived reference: a mutex-guarded store is linearizable, so a red run
// here is the wiring's own fault — before any consumer's subject is in the
// room.
func TestContractModelConcurrent(t *testing.T) {
	t.Parallel()
	updatertest.ContractModelConcurrent(t, updatertest.NewContractModelReference)
}

// testkit: end of generated content.
// testkit:provenance ec1edd5cca97b16dbd9d0c9d94515a6f7fc3a5cad861fc682c525ef3d2e8c6da
