// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/total/iface.go
// Plugins:   golang 1.0.0, suite 1.1.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package totaltest

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/total"
)

// MixedClassifyCheck is one assertion about Classify.
//
// Every generated check for Classify is a value of it, and so is one you
// write — so they compose, reorder, and each runs standalone. testing.TB rather
// than *testing.T is what lets a stand-in drive it and prove it can fail.
type MixedClassifyCheck func(tb testing.TB, subject total.Mixed, in string)

// MixedFixture holds every input the generated checks run against.
//
// Derived from each method's parameter names and types. Every field has a
// companion holding a second, different value: a check comparing a result
// against a single input passes whenever the subject happened to be seeded with
// it, and a miss check whose key happens to hit asserts nothing.
//
// A field whose type admits no literal — a func, a channel, a type from a
// package this run never read — is declared and left at its zero value, and
// every generated check that needed it was dropped rather than emitted against
// a value nobody could write. Supply one through MixedWithFixture
// and the check a consumer writes has something to use.
type MixedFixture struct {
	In      string
	InOther string
}

// DefaultMixedFixture is what this run derived. Replace any field through
// MixedWithFixture; the rest keep these values.
func DefaultMixedFixture() MixedFixture {
	return MixedFixture{
		In:      "test-in",
		InOther: "other-in",
	}
}

// AssertMixedContract runs every generated check against every declared subject.
//
//	Checks:   4 across 1 method, per subject
//	Subjects: declare each with MixedSubject
//	Double:   every subject runs a second time wrapped in MixedStub, so
//	          anything the wrapper fails that the subject passes is the double
//	          lying. MixedWithoutDouble declines it.
//	Extend:   MixedOnClassify
//	Drop:     MixedWithout, by the path each check reports under
//
// # What this file does not check
//
// The interface declares these and nothing here asserts them. Each is statable
// against a subject you can build, so the check is yours to write:
//
//   - reader, on Classify — write it with MixedOnClassify
//
// # What is checked somewhere else
//
// These need a reference implementation to compare against, which a suite run
// has no way to build. Nothing here asserts them and nothing here should:
//
//   - total, on Classify
//
// //testkit:model on the interface derives that reference, and the
// MixedModel option it generates runs them here under "model".
func AssertMixedContract(t *testing.T, opts ...MixedOption) {
	t.Helper()
	cfg := newMixedConfig(opts...)
	if len(cfg.subjects) == 0 {
		t.Fatalf("AssertMixedContract was given no subject; declare one with " +
			"MixedSubject(name, factory)")
	}
	for _, s := range cfg.subjects {
		runMixedChecks(t, cfg, s.name, s.factory, nil)
		if !cfg.withoutDouble {
			runMixedChecks(t, cfg, s.name+" through the double", s.factory,
				func(tb testing.TB, subject total.Mixed) total.Mixed {
					return NewMixedStub(tb, MixedStubDelegateTo(subject))
				})
		}
	}
}

// runMixedChecks runs the whole contract against one subject.
//
// wrap is applied after the subject is built and seeded, so a wrapper is
// transparent to the seed and every failure it causes is its own.
func runMixedChecks(
	t *testing.T,
	cfg *mixedConfig,
	label string,
	factory func() total.Mixed,
	wrap func(tb testing.TB, subject total.Mixed) total.Mixed,
) {
	t.Helper()
	t.Run(label, func(t *testing.T) {
		t.Parallel()

		t.Run("Classify", func(t *testing.T) {
			t.Parallel()
			cfg.run(t, "Classify/smoke", "smoke", func(tb testing.TB) {
				AssertMixedClassifySmoke(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.In)
			})
			cfg.run(t, "Classify/reports a cancelled context", "reports a cancelled context", func(tb testing.TB) {
				AssertMixedClassifyCancels(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.In)
			})
			cfg.run(t, "Classify/reports an expired deadline", "reports an expired deadline", func(tb testing.TB) {
				AssertMixedClassifyHonoursDeadline(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.In)
			})
			cfg.run(t, "Classify/tolerates a nil context", "tolerates a nil context", func(tb testing.TB) {
				AssertMixedClassifyToleratesNilContext(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.In)
			})
			for _, c := range cfg.onClassify {
				cfg.run(t, "Classify"+"/"+c.name, c.name, func(tb testing.TB) {
					c.fn(tb, cfg.subject(tb, factory, wrap), cfg.Fixture.In)
				})
			}
		})

		// The extra bodies of checks this run was given, each reporting under its
		// own name and dropped by it.
		//
		// The plain subject only. The wrapped pass exists to prove the double
		// faithful and the per-method checks above already do that, so running one
		// through the wrapper prices the wrapper and says nothing new about the
		// subject.
		if wrap == nil {
			for _, e := range cfg.extensions {
				if cfg.dropped(e.name) {
					t.Run(e.name, func(t *testing.T) {
						t.Skipf("dropped through MixedWithout(%q)", e.name)
					})
					continue
				}
				t.Run(e.name, func(t *testing.T) {
					t.Parallel()
					e.run(t, label, factory, cfg)
				})
			}
		}
	})
}

// AssertMixedClassifySmoke asserts Classify survives a call with derived inputs.
//
// Fails when: Classify panics. The weakest check in this file and the one
// that catches the most — a method that panics on a derived value is one no
// other check here reaches.
func AssertMixedClassifySmoke(tb testing.TB, subject total.Mixed, in string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Fatalf("Classify panicked on a derived value (%v); supply one it "+
				"accepts through MixedWithFixture", r)
		}
	}()
	ctx := tb.Context()
	_, _ = subject.Classify(ctx, in)
}

// AssertMixedClassifyCancels asserts Classify reports a cancelled context as cancelled.
//
// Fails when: Classify returns nil for a context cancelled before the
// call, or returns an error that does not answer to context.Canceled. Both
// matter and they are different defects: the first is work done that the caller
// asked not to be, the second is a caller who wrote
// `errors.Is(err, context.Canceled)` and gets false for a call that was.
//
// The error rather than merely its presence is what separates this from the
// deadline check. Asserting only that something came back makes the two one
// check written twice.
func AssertMixedClassifyCancels(tb testing.TB, subject total.Mixed, in string) {
	tb.Helper()
	ctx, cancel := context.WithCancel(tb.Context())
	cancel()
	_, err := subject.Classify(ctx, in)
	testkit.ErrorIs(tb, err, context.Canceled,
		"Classify must report a cancelled context as context.Canceled")
}

// AssertMixedClassifyHonoursDeadline asserts Classify reports an expired deadline as exceeded.
//
// Fails when: Classify returns nil for a context whose deadline has
// passed, or returns an error that does not answer to
// context.DeadlineExceeded. Distinct from cancellation in what the caller
// learns: a cancelled call was called off, an expired one ran out of time, and
// only the second is worth retrying.
//
// The deadline is the zero time, which is unconditionally in the past. No clock
// is read: a generated check that consults the wall clock is one whose subject
// is partly the machine it runs on.
func AssertMixedClassifyHonoursDeadline(tb testing.TB, subject total.Mixed, in string) {
	tb.Helper()
	ctx, cancel := context.WithDeadline(tb.Context(), time.Time{})
	defer cancel()
	_, err := subject.Classify(ctx, in)
	testkit.ErrorIs(tb, err, context.DeadlineExceeded,
		"Classify must report an expired deadline as context.DeadlineExceeded")
}

// AssertMixedClassifyToleratesNilContext asserts Classify does not panic on a nil context.
//
// Fails when: Classify panics. Returning an error is correct and
// succeeding is correct — a nil context reaches production through a caller
// that forgot one, and a panic turns that into an outage rather than a failed
// request.
func AssertMixedClassifyToleratesNilContext(tb testing.TB, subject total.Mixed, in string) {
	tb.Helper()
	defer func() {
		if r := recover(); r != nil {
			tb.Errorf("Classify panicked on a nil context (%v); return an error instead", r)
		}
	}()
	//nolint:staticcheck // passing nil is the check.
	var ctx context.Context
	_, _ = subject.Classify(ctx, in)
}

// MixedOption configures a contract run.
type MixedOption func(*mixedConfig)

// MixedSubject declares an implementation to hold to the contract.
//
// Repeat it for every implementation that claims to satisfy the interface — an
// in-memory one, the one backed by a database, the one behind a network. Every
// check and every option is stated once and runs against all of them, which is
// what a conformance suite is for.
func MixedSubject(name string, factory func() total.Mixed) MixedOption {
	return func(c *mixedConfig) {
		c.subjects = append(c.subjects, namedMixedSubject{name, factory})
	}
}

// MixedWithoutDouble declines the second run through MixedStub.
//
// The double run proves the stand-in is faithful, and costs a second pass over
// every check. Decline it where the double is not used.
func MixedWithoutDouble() MixedOption {
	return func(c *mixedConfig) { c.withoutDouble = true }
}

// MixedWithClock supplies the clock every time-reading check measures on.
//
// Defaults to the real one, so an implementation that does not take a clock
// behaves as it would have. Supply a [clock.TestClock] — the same one the
// factory builds the subject with — and a budget becomes a claim about the time
// the implementation means to spend rather than about how loaded the machine
// was.
func MixedWithClock(c clock.Clock) MixedOption {
	return func(cfg *mixedConfig) { cfg.clock = c }
}

// MixedWithFixture replaces the derived inputs.
func MixedWithFixture(f MixedFixture) MixedOption {
	return func(c *mixedConfig) { c.Fixture = f }
}

// MixedSeed replaces the derived seed.
//
// For an interface with no writer to seed itself through, which is the one
// input a conformance run cannot derive: a reader over an empty subject
// asserts nothing.
//
// Returning an error rather than swallowing one. A seed that failed quietly
// leaves every check after it asserting nothing and reporting success.
func MixedSeed(fn func(ctx context.Context, subject total.Mixed) error) MixedOption {
	return func(c *mixedConfig) {
		c.seed = fn
	}
}

// MixedOnClassify adds a named check to Classify.
func MixedOnClassify(name string, fn MixedClassifyCheck) MixedOption {
	return func(c *mixedConfig) {
		c.onClassify = append(c.onClassify, namedMixedClassifyCheck{name, fn})
	}
}

// MixedWithout drops generated checks by the path each reports under.
//
// For a subject that legitimately violates one. Without this the only recourse
// is to stop running the suite, which costs every other check in the file — so
// a dropped check is reported as skipped rather than silently omitted.
func MixedWithout(paths ...string) MixedOption {
	return func(c *mixedConfig) {
		for _, p := range paths {
			c.without[p] = struct{}{}
		}
	}
}

type namedMixedClassifyCheck struct {
	name string
	fn   MixedClassifyCheck
}

type namedMixedSubject struct {
	name    string
	factory func() total.Mixed
}

// mixedContractExtension is a body of checks a generated sibling adds through an option.
//
// A sibling declares the option and closes over whatever configures it, so
// everything that varies per run is typed and private to the file that owns it
// — this file understands only the name and the call. Nothing arrives except
// through an option, which is what keeps the set fixed before the first subtest
// starts.
type mixedContractExtension struct {
	// name is the path this reports under, and the one MixedWithout drops
	// it by. Anything nested beneath it is the extension's own to name.
	name string

	// run takes the factory rather than a subject. One that drives sequences
	// builds a subject per iteration, and one that compares against a reference
	// needs the unseeded subject a factory returns — which
	// mixedConfig.subject is not.
	//
	// Called once per subject, in parallel, sharing the config. Anything it
	// mutates has to be built inside the call: state captured when the option
	// was declared is state two subjects write at once.
	run func(
		t *testing.T,
		subject string,
		factory func() total.Mixed,
		cfg *mixedConfig,
	)
}

type mixedConfig struct {
	Fixture       MixedFixture
	subjects      []namedMixedSubject
	withoutDouble bool
	clock         clock.Clock
	seed          func(ctx context.Context, subject total.Mixed) error
	without       map[string]struct{}
	extensions    []mixedContractExtension
	onClassify    []namedMixedClassifyCheck
}

func newMixedConfig(opts ...MixedOption) *mixedConfig {
	c := &mixedConfig{
		Fixture: DefaultMixedFixture(),
		clock:   clock.RealClock(),
		without: map[string]struct{}{},
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// subject builds a fresh implementation and seeds it, so every check runs
// against state no other check touched.
func (c *mixedConfig) subject(
	tb testing.TB,
	factory func() total.Mixed,
	wrap func(tb testing.TB, subject total.Mixed) total.Mixed,
) total.Mixed {
	tb.Helper()
	s := factory()
	if c.seed != nil {
		// Reported rather than ignored. A seed that silently failed would leave
		// every check after it running against an empty subject — passing, and
		// asserting nothing.
		//
		// Which seed ran decides what the message can usefully say. The derived
		// one fails for one of two reasons and both are fixable from here, so it
		// names them. A seed the caller supplied is theirs, and telling them to
		// supply one is advice they already took.
		if err := c.seed(tb.Context(), s); err != nil {
			tb.Fatalf("the seed supplied through MixedSeed failed: %v", err)
		}
	}
	if wrap != nil {
		s = wrap(tb, s)
	}
	return s
}

// dropped reports whether a path was declined through MixedWithout.
//
// Named rather than inlined because the drop set is read from two places: here,
// and by whatever registered through the seam — which reports under paths this
// file has never heard of and must answer the same question about them.
func (c *mixedConfig) dropped(path string) bool {
	_, ok := c.without[path]
	return ok
}

// run executes one check unless it was dropped, reporting the drop rather than
// silently omitting it.
func (c *mixedConfig) run(t *testing.T, path, name string, fn func(tb testing.TB)) {
	t.Helper()
	if c.dropped(path) {
		t.Run(name, func(t *testing.T) {
			t.Skipf("dropped through MixedWithout(%q)", path)
		})
		return
	}
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		fn(t)
	})
}

// testkit: end of generated content.
// testkit:provenance 00639664431cc0ff00d39bdf5e9e1d4bdc7d420850d870841b8e4704e5a312c7
