// Code generated by testkit. DO NOT EDIT.
//
// Source:    corpus/iface/mixin/integrationonly/iface.go
// Plugins:   golang 1.0.0, suite 1.15.0, backend.golang 1.0.0
// Command:   testkit run ./corpus/...

package integrationonlytest_test

import (
	"context"
	"testing"

	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/conformance/corpus/iface/mixin/integrationonly/integrationonlytest"
)

// Every generated check for Mixed, driven against a stand-in built
// to violate it.
//
//	Proved:   4 checks
//
// Each guard asserts the *reason* the check rejected, not merely that it did. A
// stand-in that failed for some unrelated reason — a nil map, a closed channel
// — would satisfy a guard reading only the fact, which is the vacuity this file
// exists to catch, one level up.

// TestAssertMixedConnectSmokeCanFail holds AssertMixedConnectSmoke to being able to fail.
//
// The stand-in panics on the value the fixture derived. A check that let that
// pass would leave a panicking method reported as a crashed run rather than as
// a failed assertion — with no line naming the method that did it.
func TestAssertMixedConnectSmokeCanFail(t *testing.T) {
	t.Parallel()

	fixture := integrationonlytest.DefaultMixedFixture()
	subject := integrationonlytest.NewMixedStub(t,
		integrationonlytest.WithMixedConnect(func(context.Context, string) error {
			panic("Mixed.Connect: violating the smoke check")
		}))

	got := testkit.Rejects(t, "a method that panics on a derived value",
		func(tb testing.TB) {
			tb.Helper()
			integrationonlytest.AssertMixedConnectSmoke(tb, subject, fixture.Dsn)
		})
	testkit.Assert(t, got).Contains("Connect panicked on a derived value",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedConnectCancelsCanFail holds AssertMixedConnectCancels to being able to fail.
//
// The stand-in answers a cancelled context as though nothing were wrong. A
// check that let that pass would report success for a subject doing work its
// caller had already abandoned.
func TestAssertMixedConnectCancelsCanFail(t *testing.T) {
	t.Parallel()

	fixture := integrationonlytest.DefaultMixedFixture()
	subject := integrationonlytest.NewMixedStub(t,
		integrationonlytest.WithMixedConnect(func(context.Context, string) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for a cancelled context",
		func(tb testing.TB) {
			tb.Helper()
			integrationonlytest.AssertMixedConnectCancels(tb, subject, fixture.Dsn)
		})
	testkit.Assert(t, got).Contains("Connect must report a cancelled context as context.Canceled",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedConnectHonoursDeadlineCanFail holds AssertMixedConnectHonoursDeadline to being able to fail.
//
// The stand-in answers an expired deadline as though nothing were wrong. A
// check that let that pass would report success for a subject that keeps
// working past the point its caller stopped waiting.
func TestAssertMixedConnectHonoursDeadlineCanFail(t *testing.T) {
	t.Parallel()

	fixture := integrationonlytest.DefaultMixedFixture()
	subject := integrationonlytest.NewMixedStub(t,
		integrationonlytest.WithMixedConnect(func(context.Context, string) error {
			return nil
		}))

	got := testkit.Rejects(t, "a method that reports nothing for an expired deadline",
		func(tb testing.TB) {
			tb.Helper()
			integrationonlytest.AssertMixedConnectHonoursDeadline(tb, subject, fixture.Dsn)
		})
	testkit.Assert(t, got).Contains("Connect must report an expired deadline as context.DeadlineExceeded",
		"and rejects it for the reason the check is about")
}

// TestAssertMixedConnectToleratesNilContextCanFail holds AssertMixedConnectToleratesNilContext to being able to fail.
//
// The stand-in panics rather than reporting. A check that let that pass would
// leave a caller who forgot a context taking the process down instead of
// getting an error back.
func TestAssertMixedConnectToleratesNilContextCanFail(t *testing.T) {
	t.Parallel()

	fixture := integrationonlytest.DefaultMixedFixture()
	subject := integrationonlytest.NewMixedStub(t,
		integrationonlytest.WithMixedConnect(func(context.Context, string) error {
			panic("Mixed.Connect: violating the nil-context check")
		}))

	got := testkit.Rejects(t, "a method that panics on a nil context",
		func(tb testing.TB) {
			tb.Helper()
			integrationonlytest.AssertMixedConnectToleratesNilContext(tb, subject, fixture.Dsn)
		})
	testkit.Assert(t, got).Contains("Connect panicked on a nil context",
		"and rejects it for the reason the check is about")
}

// testkit: end of generated content.
// testkit:provenance 124ebfa28bb535d5709d2f715570a55b35405a22c8858606364ef45a2b9ed661
